---
sidebar: sidebar 
permalink: upgrade/task_hcc_upgrade_element_software.html 
summary: Como parte de una actualización del sistema NetApp SolidFire , se actualiza el software NetApp Element . 
keywords: netapp, solidfire, cluster, element, H610S upgrade, hcc, upgrade role 
---
= Actualizar el software Element
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para actualizar el software NetApp Element , puede utilizar la interfaz de usuario de NetApp Hybrid Cloud Control o la API REST.  Ciertas operaciones se suprimen durante una actualización de software de Element, como agregar y quitar nodos, agregar y quitar unidades y comandos asociados con iniciadores, grupos de acceso a volúmenes y redes virtuales, entre otros.

[CAUTION]
====
El paquete de servicios de administración 2.27 incluye el complemento Element para vCenter Server 5.5, que solo es compatible con el nodo de administración 12.8. Cuando actualiza a los servicios de administración 2.27, debe cambiar la secuencia de actualización y actualizar el paquete de servicios de administración _después_ de actualizar a Element 12.8 para tener compatibilidad entre el nodo de administración y los servicios de administración.

Si está actualizando a los servicios de administración 2.21.61 a 2.26.40, debe actualizar el paquete de servicios de administración _antes_ de actualizar a Element 12.8.

====
.Antes de empezar
* *Privilegios de administrador*: Usted tiene permisos de administrador del clúster de almacenamiento para realizar la actualización.
* *Ruta de actualización válida*: Ha comprobado la información de la ruta de actualización para la versión de Element a la que está actualizando y ha verificado que la ruta de actualización es válida.https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software%3F["Base de conocimientos de NetApp : Matriz de actualización para clústeres de almacenamiento que ejecutan el software NetApp Element ."^]
+
A partir de Element 12.5, NetApp HealthTools ya no es compatible con las actualizaciones de software de Element.  Si está utilizando Element 11.0 o 11.1, primero debelink:https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Actualizar a Element 12.3.x usando HealthTools"^] y luego actualice a Element 12.5 o posterior utilizando NetApp Hybrid Cloud Control.

* *Sincronización de la hora del sistema*: Se ha asegurado de que la hora del sistema en todos los nodos esté sincronizada y de que NTP esté configurado correctamente para el clúster de almacenamiento y los nodos.  Cada nodo debe configurarse con un servidor de nombres DNS en la interfaz web de cada nodo.(`https://[IP address]:442` ) sin fallos de clúster sin resolver relacionados con la asimetría temporal.
* *Puertos del sistema*: Si utiliza NetApp Hybrid Cloud Control para las actualizaciones, se ha asegurado de que los puertos necesarios estén abiertos. Verlink:../storage/reference_prereq_network_port_requirements.html["puertos de red"] Para más información.
* *Nodo de administración*: Para la interfaz de usuario y la API de NetApp Hybrid Cloud Control, el nodo de administración de su entorno ejecuta la versión 11.3.
* *Estado del clúster*: Ha verificado que el clúster está listo para actualizarse. Verlink:task_hcc_upgrade_element_prechecks.html["Ejecute las comprobaciones de estado del almacenamiento de Element antes de actualizar el almacenamiento."] .
* *Controlador de administración de placa base (BMC) actualizado para nodos de almacenamiento H610S*: Ha actualizado la versión del BMC para sus nodos H610S. Ver ellink:https://docs.netapp.com/us-en/hci/docs/rn_H610S_BMC_3.84.07.html["Notas de la versión e instrucciones de actualización"^] .


[[element-upgrade-tim]]
* *Tiempo del proceso de actualización*: Ha programado tiempo suficiente para realizar su actualización.  Cuando actualice al software Element 12.5 o posterior, el tiempo del proceso de actualización variará según su versión actual del software Element y las actualizaciones de firmware.
+
[cols="20,20,20,20,20"]
|===
| Nodo de almacenamiento | Versión actual del software Element | Tiempo aproximado de instalación de software y firmware por nodo^1^ | Tiempo aproximado de sincronización de datos por nodo^2^ | Tiempo total aproximado de actualización por nodo 


| Todos los nodos SolidFire y NetApp de la serie H con firmware actualizado^3^ | 12.x | 15 minutos | De 10 a 15 minutos | De 20 a 30 minutos 


| H610S y H410S | 12.x y 11.8 | 60 minutos | De 30 a 60 minutos | De 90 a 120 minutos 


| H610S | 11.7 y anteriores | 90 minutos | De 40 a 70 minutos | De 130 a 160 minutos También debes https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Realizar un apagado completo del nodo y una desconexión de la alimentación"^] para cada nodo H610S. 
|===
+
^1^Para obtener una matriz completa de firmware y firmware de controladores para su hardware, consultelink:../hardware/fw_storage_nodes.html["Versiones de firmware de almacenamiento compatibles para nodos de almacenamiento SolidFire"] .

+
^2^Si se combina un clúster con una carga de IOPS de escritura elevada con un tiempo de actualización de firmware más largo, el tiempo de sincronización de datos aumentará.

+
^3^ Los siguientes nodos no son compatibles.  Si intenta actualizar uno de estos nodos a una versión de Element no compatible, verá un error que indica que el nodo no es compatible con Element 12.x:

+
** Comenzando con los nodos de almacenamiento Element 12.8, SF4805, SF9605, SF19210 y SF38410.
** Comenzando con los nodos de almacenamiento Element 12.7, SF2405 y SF9608 y los nodos FC FC0025 y SF-FCN-01.


* *Acuerdo de licencia de usuario final (EULA)*: A partir de los servicios de administración 2.20.69, debe aceptar y guardar el EULA antes de utilizar la interfaz de usuario o la API de NetApp Hybrid Cloud Control para actualizar el software Element:
+
.. Abra la dirección IP del nodo de administración en un navegador web:
+
[listing]
----
https://<ManagementNodeIP>
----
.. Inicie sesión en NetApp Hybrid Cloud Control proporcionando las credenciales de administrador del clúster de almacenamiento.
.. Seleccione *Actualizar*, situado en la parte superior derecha de la interfaz.
.. Aparece el EULA.  Desplácese hacia abajo, seleccione *Acepto las actualizaciones actuales y futuras* y seleccione *Guardar*.




.Opciones de actualización
Elija una de las siguientes opciones de actualización de software de Element:

* <<Utilice la interfaz de usuario de NetApp Hybrid Cloud Control para actualizar el almacenamiento de Element.>>
* <<Utilice la API de NetApp Hybrid Cloud Control para actualizar el almacenamiento de Element.>>



IMPORTANT: Si está actualizando un nodo de la serie H610S a Element 12.5 o posterior y el nodo ejecuta una versión de Element anterior a la 11.8, deberá realizar los pasos de actualización adicionales que se describen en este documento. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artículo de la base de conocimientos"^] para cada nodo de almacenamiento.  Si está utilizando Element 11.8 o posterior, no se requieren pasos de actualización adicionales.



== Utilice la interfaz de usuario de NetApp Hybrid Cloud Control para actualizar el almacenamiento de Element.

Mediante la interfaz de usuario de NetApp Hybrid Cloud Control, puede actualizar un clúster de almacenamiento.


CAUTION: Para conocer los posibles problemas que puedan surgir al actualizar clústeres de almacenamiento mediante NetApp Hybrid Cloud Control y sus soluciones alternativas, consulte este documento. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["Artículo de la base de conocimientos"^] .

.Pasos
. Abra la dirección IP del nodo de administración en un navegador web:
+
[listing]
----
https://<ManagementNodeIP>
----
. Inicie sesión en NetApp Hybrid Cloud Control proporcionando las credenciales de administrador del clúster de almacenamiento.
. Seleccione *Actualizar*, situado en la parte superior derecha de la interfaz.
. En la página *Actualizaciones*, seleccione *Almacenamiento*.
+
La pestaña *Almacenamiento* muestra los clústeres de almacenamiento que forman parte de su instalación.  Si un clúster es inaccesible para NetApp Hybrid Cloud Control, no se mostrará en la página *Actualizaciones*.

. Elija entre las siguientes opciones y realice el conjunto de pasos que correspondan a su clúster:
+
[cols="2*"]
|===
| Opción | Pasos 


| Todos los clústeres que ejecutan Element 11.8 y versiones posteriores.  a| 
.. Seleccione *Examinar* para cargar el paquete de actualización que descargó.
.. Espere a que finalice la carga.  Una barra de progreso muestra el estado de la carga.
+

CAUTION: Si abandona la ventana del navegador, se perderá la carga del archivo.

+
Aparece un mensaje en pantalla una vez que el archivo se ha cargado y validado correctamente.  La validación puede tardar varios minutos.  Si abandona la ventana del navegador en este momento, la carga del archivo se conservará.

.. Seleccione *Iniciar actualización*.
+

TIP: El *Estado de actualización* cambia durante la actualización para reflejar el estado del proceso.  También cambia en respuesta a las acciones que realice, como pausar la actualización, o si la actualización devuelve un error. Ver<<Cambios en el estado de la actualización>> .

+

NOTE: Mientras la actualización está en curso, puede abandonar la página y volver a ella más tarde para continuar supervisando el progreso.  La página no actualiza dinámicamente el estado ni la versión actual si la fila del clúster está contraída.  Para actualizar la tabla, debe expandir la fila del clúster o bien actualizar la página.

+
Podrá descargar los registros una vez finalizada la actualización.





| Estás actualizando un clúster H610S que ejecuta una versión de Element anterior a la 11.8.  a| 
.. Seleccione la flecha desplegable junto al clúster que está actualizando y seleccione una de las versiones de actualización disponibles.
.. Seleccione *Iniciar actualización*.  Una vez finalizada la actualización, la interfaz de usuario le solicitará que realice pasos de actualización adicionales.
.. Complete los pasos adicionales requeridos en el https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artículo de la base de conocimientos"^] , y confirmar en la interfaz de usuario que ha completado la fase 2.


Podrá descargar los registros una vez finalizada la actualización.  Para obtener información sobre los distintos cambios en el estado de las actualizaciones, consulte<<Cambios en el estado de la actualización>> .

|===




=== Cambios en el estado de la actualización

Aquí están los diferentes estados que muestra la columna *Estado de actualización* en la interfaz de usuario antes, durante y después del proceso de actualización:

[cols="2*"]
|===
| Estado de actualización | Descripción 


| A hoy | El clúster se actualizó a la última versión disponible de Element. 


| Versiones disponibles | Hay disponibles versiones más recientes del firmware de Element y/o del almacenamiento para su actualización. 


| En curso | La actualización está en curso.  Una barra de progreso muestra el estado de la actualización.  Los mensajes en pantalla también muestran fallos a nivel de nodo y el ID de cada nodo del clúster a medida que avanza la actualización.  Puede supervisar el estado de cada nodo utilizando la interfaz de usuario de Element o el complemento NetApp Element para la interfaz de usuario de vCenter Server. 


| Pausa de actualización | Puedes optar por pausar la actualización.  Dependiendo del estado del proceso de actualización, la operación de pausa puede tener éxito o fracasar.  Verás una ventana emergente en la interfaz de usuario que te pedirá que confirmes la operación de pausa.  Para garantizar que el clúster se encuentre en un lugar seguro antes de pausar una actualización, la operación de actualización puede tardar hasta dos horas en pausarse por completo.  Para reanudar la actualización, seleccione *Reanudar*. 


| Paused | Has pausado la actualización.  Seleccione *Reanudar* para reanudar el proceso. 


| Error | Se ha producido un error durante la actualización.  Puede descargar el registro de errores y enviarlo al soporte de NetApp .  Una vez resuelto el error, puede volver a la página y seleccionar *Reanudar*.  Al reanudar la actualización, la barra de progreso retrocede durante unos minutos mientras el sistema realiza la comprobación de estado y verifica el estado actual de la actualización. 


| Completo con seguimiento | Solo para nodos H610S que se actualicen desde una versión de Element anterior a la 11.8.  Una vez completada la fase 1 del proceso de actualización, este estado le solicita que realice pasos de actualización adicionales (consulte la sección correspondiente). https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artículo de la base de conocimientos"^] ).  Después de completar la fase 2 y confirmar que la ha completado, el estado cambia a *Actualizado*. 
|===


== Utilice la API de NetApp Hybrid Cloud Control para actualizar el almacenamiento de Element.

Puede utilizar las API para actualizar los nodos de almacenamiento de un clúster a la última versión del software Element.  Puedes utilizar la herramienta de automatización que prefieras para ejecutar las API.  El flujo de trabajo de la API que se documenta aquí utiliza como ejemplo la interfaz de usuario de la API REST disponible en el nodo de administración.

.Pasos
. Descargue el paquete de actualización de almacenamiento en un dispositivo que sea accesible para el nodo de administración.
+
Acceda al software Element. https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["página de descargas"^] y descarga la última imagen del nodo de almacenamiento.

. Cargue el paquete de actualización de almacenamiento al nodo de administración:
+
.. Abra la interfaz de usuario de la API REST del nodo de administración en el nodo de administración:
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
.. Seleccione *Autorizar* y complete lo siguiente:
+
... Introduzca el nombre de usuario y la contraseña del clúster.
... Introduzca el ID del cliente como `mnode-client` .
... Seleccione *Autorizar* para iniciar una sesión.
... Cierre la ventana de autorización.


.. Desde la interfaz de usuario de la API REST, seleccione *POST /packages*.
.. Seleccione *Probarlo*.
.. Seleccione *Examinar* y elija el paquete de actualización.
.. Seleccione *Ejecutar* para iniciar la carga.
.. A partir de la respuesta, copie y guarde el ID del paquete.(`"id"` ) para su uso en un paso posterior.


. Verifique el estado de la carga.
+
.. Desde la interfaz de usuario de la API REST, seleccione *GET​ /packages​/{id}​/status*.
.. Seleccione *Probarlo*.
.. Introduzca el ID del paquete que copió en el paso anterior en *id*.
.. Seleccione *Ejecutar* para iniciar la solicitud de estado.
+
La respuesta indica `state` como `SUCCESS` cuando esté completo.



. Localice el ID del clúster de almacenamiento:
+
.. Abra la interfaz de usuario de la API REST del nodo de administración en el nodo de administración:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Seleccione *Autorizar* y complete lo siguiente:
+
... Introduzca el nombre de usuario y la contraseña del clúster.
... Introduzca el ID del cliente como `mnode-client` .
... Seleccione *Autorizar* para iniciar una sesión.
... Cierre la ventana de autorización.


.. Desde la interfaz de usuario de la API REST, seleccione *GET /installations*.
.. Seleccione *Probarlo*.
.. Seleccione *Ejecutar*.
.. Copie el ID del recurso de instalación de la respuesta.(`"id"` ).
.. Desde la interfaz de usuario de la API REST, seleccione *GET /installations/{id}*.
.. Seleccione *Probarlo*.
.. Pegue el ID del activo de instalación en el campo *id*.
.. Seleccione *Ejecutar*.
.. A partir de la respuesta, copie y guarde el ID del clúster de almacenamiento.(`"id"` ) del clúster que pretende actualizar para su uso en un paso posterior.


. Ejecutar la actualización de almacenamiento:
+
.. Abra la interfaz de usuario de la API REST de almacenamiento en el nodo de administración:
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. Seleccione *Autorizar* y complete lo siguiente:
+
... Introduzca el nombre de usuario y la contraseña del clúster.
... Introduzca el ID del cliente como `mnode-client` .
... Seleccione *Autorizar* para iniciar una sesión.
... Cierre la ventana de autorización.


.. Seleccione *POST /actualizaciones*.
.. Seleccione *Probarlo*.
.. Introduzca el ID del paquete de actualización en el campo de parámetros.
.. Introduzca el ID del clúster de almacenamiento en el campo de parámetros.
+
La carga útil debería ser similar al siguiente ejemplo:

+
[listing]
----
{
  "config": {},
  "packageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4",
  "storageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4"
}
----
.. Seleccione *Ejecutar* para iniciar la actualización.
+
La respuesta debe indicar el estado como `initializing` :

+
[listing]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055`-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  "state": "initializing",
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. Copie el ID de actualización(`"upgradeId"` ) eso forma parte de la respuesta.


. Verifique el progreso y los resultados de la actualización:
+
.. Seleccione *GET ​/upgrades/{upgradeId}*.
.. Seleccione *Probarlo*.
.. Introduzca el ID de actualización del paso anterior en *upgradeId*.
.. Seleccione *Ejecutar*.
.. Realice una de las siguientes acciones si surgen problemas o requisitos especiales durante la actualización:
+
[cols="2*"]
|===
| Opción | Pasos 


| Debe corregir los problemas de salud del clúster debido a `failedHealthChecks` mensaje en el cuerpo de la respuesta.  a| 
... Consulte el artículo de la base de conocimientos específico que se indica para cada problema o realice la solución indicada.
... Si se especifica un KB, complete el proceso descrito en el artículo KB correspondiente.
... Después de haber resuelto los problemas del clúster, vuelva a autenticarse si es necesario y seleccione *PUT ​/upgrades/{upgradeId}*.
... Seleccione *Probarlo*.
... Introduzca el ID de actualización del paso anterior en *upgradeId*.
... Ingresar `"action":"resume"` en el cuerpo de la solicitud.
+
[listing]
----
{
  "action": "resume"
}
----
... Seleccione *Ejecutar*.




| Debe pausar la actualización porque la ventana de mantenimiento está finalizando o por otro motivo.  a| 
... Vuelva a autenticarse si es necesario y seleccione *PUT ​/upgrades/{upgradeId}*.
... Seleccione *Probarlo*.
... Introduzca el ID de actualización del paso anterior en *upgradeId*.
... Ingresar `"action":"pause"` en el cuerpo de la solicitud.
+
[listing]
----
{
  "action": "pause"
}
----
... Seleccione *Ejecutar*.




| Si está actualizando un clúster H610S que ejecuta una versión de Element anterior a la 11.8, verá el estado `finishedNeedsAck` en el cuerpo de la respuesta. Debe realizar pasos de actualización adicionales para cada nodo de almacenamiento H610S.  a| 
... Complete los pasos de actualización adicionales en este https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artículo de la base de conocimientos"^] para cada nodo.
... Vuelva a autenticarse si es necesario y seleccione *PUT ​/upgrades/{upgradeId}*.
... Seleccione *Probarlo*.
... Introduzca el ID de actualización del paso anterior en *upgradeId*.
... Ingresar `"action":"acknowledge"` en el cuerpo de la solicitud.
+
[listing]
----
{
  "action": "acknowledge"
}
----
... Seleccione *Ejecutar*.


|===
.. Ejecute la API *GET /upgrades/{upgradeId}* varias veces, según sea necesario, hasta que el proceso esté completo.
+
Durante la actualización, `status` indica `running` si no se producen errores.  A medida que se actualiza cada nodo, el `step` cambios de valor a `NodeFinished` .

+
La actualización finalizó correctamente cuando `percent` El valor es `100` y el `state` indica `finished` .







== ¿Qué ocurre si falla una actualización utilizando NetApp Hybrid Cloud Control?

Si una unidad o un nodo falla durante una actualización, la interfaz de usuario de Element mostrará fallos del clúster.  El proceso de actualización no pasa al siguiente nodo y espera a que se resuelvan los fallos del clúster.  La barra de progreso en la interfaz de usuario muestra que la actualización está esperando a que se resuelvan los fallos del clúster.  En esta etapa, seleccionar *Pausar* en la interfaz de usuario no funcionará, porque la actualización espera a que el clúster esté en buen estado.  Deberá ponerse en contacto con el soporte de NetApp para que le ayuden con la investigación del fallo.

NetApp Hybrid Cloud Control tiene un período de espera preestablecido de tres horas, durante el cual puede ocurrir uno de los siguientes escenarios:

* Los fallos del clúster se resuelven en un plazo de tres horas y se reanuda la actualización.  En este caso, no es necesario que tome ninguna medida.
* El problema persiste después de tres horas y el estado de la actualización muestra *Error* con un banner rojo.  Puede reanudar la actualización seleccionando *Reanudar* una vez resuelto el problema.
* El soporte de NetApp ha determinado que es necesario interrumpir temporalmente la actualización para tomar medidas correctivas antes de que transcurran las tres horas.  El soporte técnico utilizará la API para cancelar la actualización.



CAUTION: Si se interrumpe la actualización del clúster mientras se está actualizando un nodo, es posible que las unidades se extraigan del nodo de forma incorrecta.  Si las unidades se extraen de forma incorrecta, volver a agregarlas durante una actualización requerirá la intervención manual del soporte de NetApp .  Es posible que el nodo esté tardando más en realizar las actualizaciones de firmware o las actividades de sincronización posteriores a la actualización.  Si el progreso de la actualización parece estancado, póngase en contacto con el soporte de NetApp para obtener ayuda.

[discrete]
== Encuentra más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

