---
sidebar: sidebar 
permalink: mnode/task_mnode_install_add_storage_NIC.html 
summary: Si utiliza una NIC adicional para almacenamiento, deberá configurar una interfaz de red sin etiquetar o etiquetada. 
keywords: netapp, element, management node, mnode, network, nic, storage nic 
---
= Configurar un controlador de interfaz de red (NIC) de almacenamiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si está utilizando una NIC adicional para almacenamiento, puede conectarse mediante SSH al nodo de administración o utilizar la consola de vCenter y ejecutar un comando curl para configurar una interfaz de red etiquetada o no etiquetada.

.Antes de empezar
* Conoces tu dirección IP eth0.
* Su versión de clúster ejecuta el software NetApp Element 11.3 o posterior.
* Has implementado un nodo de administración versión 11.3 o posterior.


.Opciones de configuración
Elige la opción que sea relevante para tu entorno:

* <<Configure un controlador de interfaz de red (NIC) de almacenamiento para una interfaz de red sin etiquetar.>>
* <<Configure un controlador de interfaz de red (NIC) de almacenamiento para una interfaz de red etiquetada.>>




== Configure un controlador de interfaz de red (NIC) de almacenamiento para una interfaz de red sin etiquetar.

.Pasos
. Abra una consola SSH o vCenter.
. Sustituya los valores en la siguiente plantilla de comando y ejecute el comando:
+

NOTE: Los valores están representados por `$` para cada uno de los parámetros requeridos para su nueva interfaz de red de almacenamiento.  El `cluster` El objeto de la siguiente plantilla es obligatorio y se puede utilizar para cambiar el nombre del host del nodo de administración. `--insecure` o `-k` Estas opciones no deben utilizarse en entornos de producción.

+
[listing]
----
curl -u $mnode_user_name:$mnode_password --insecure -X POST \
https://$mnode_IP:442/json-rpc/10.0 \
-H 'Content-Type: application/json' \
-H 'cache-control: no-cache' \
-d ' {
     "params": {
               "network": {
                          "$eth1": {
                                   "#default" : false,
                                   "address" : "$storage_IP",
                                   "auto" : true,
                                   "family" : "inet",
                                   "method" : "static",
                                   "mtu" : "9000",
                                   "netmask" : "$subnet_mask",
                                   "status" : "Up"
                                   }
                          },
               "cluster": {
                         "name": "$mnode_host_name"
                         }
             },
    "method": "SetConfig"
}
'
----




== Configure un controlador de interfaz de red (NIC) de almacenamiento para una interfaz de red etiquetada.

.Pasos
. Abra una consola SSH o vCenter.
. Sustituya los valores en la siguiente plantilla de comando y ejecute el comando:
+

NOTE: Los valores están representados por `$` para cada uno de los parámetros requeridos para su nueva interfaz de red de almacenamiento.  El `cluster` El objeto de la siguiente plantilla es obligatorio y se puede utilizar para cambiar el nombre del host del nodo de administración. `--insecure` o `-k` Estas opciones no deben utilizarse en entornos de producción.

+
[listing]
----
curl -u $mnode_user_name:$mnode_password --insecure -X POST \
https://$mnode_IP:442/json-rpc/10.0 \
-H 'Content-Type: application/json' \
-H 'cache-control: no-cache' \
-d ' {
     "params": {
               "network": {
                          "$eth1": {
                                   "#default" : false,
                                   "address" : "$storage_IP",
                                   "auto" : true,
                                   "family" : "inet",
                                   "method" : "static",
                                   "mtu" : "9000",
                                   "netmask" : "$subnet_mask",
                                   "status" : "Up",
                                   "virtualNetworkTag" : "$vlan_id"
                                   }
                          },
               "cluster": {
                         "name": "$mnode_host_name",
                         "cipi": "$eth1.$vlan_id",
                         "sipi": "$eth1.$vlan_id"
                         }
             },
    "method": "SetConfig"
}
'
----


[discrete]
== Encuentra más información

* link:task_mnode_add_assets.html["Agregar un activo de controlador al nodo de administración"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]

