= Parámetro
:allow-uri-read: 


Puedes usar el `GetNodeFipsDrivesReport` Método para comprobar el estado de la capacidad de cifrado de la unidad FIPS 140-2 de un único nodo en el clúster de almacenamiento.  Debe ejecutar este método en un nodo de almacenamiento individual.



== Parámetro

Este método no tiene parámetros de entrada.



== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
Unidades fips
 a| 
Un objeto JSON que contiene el estado de la compatibilidad con la característica FIPS 140-2 para este nodo. Valores posibles:

* Ninguno: El nodo no es compatible con FIPS.
* Parcial: El nodo es compatible con FIPS, pero no todas las unidades del nodo son unidades FIPS.
* Listo: El nodo es compatible con FIPS y todas las unidades del nodo son unidades FIPS (o no hay unidades presentes).

 a| 
cadena

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "GetNodeFipsDrivesReport",
  "params": {},
  "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
    "id": 1,
    "result": {
        "fipsDrives": "None"
    }
}
----


== Nueva versión

11,5
