---
permalink: concepts/concept_solidfire_concepts_accounts_and_permissions.html 
sidebar: sidebar 
keywords: solidfire, element, cluster admin, storage, account, authoritative cluster 
summary: Para administrar y proporcionar acceso a los recursos de almacenamiento de su sistema, deberá configurar cuentas para los recursos del sistema. 
---
= Cuentas y permisos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para administrar y proporcionar acceso a los recursos de almacenamiento de su sistema, deberá configurar cuentas para los recursos del sistema.

Con el almacenamiento de Element, puede crear y administrar los siguientes tipos de cuentas:

* <<cuentas de administrador de clúster de almacenamiento,Cuentas de usuario administrador para el clúster de almacenamiento>>
* <<Cuentas de usuario,Cuentas de usuario para el acceso al volumen de almacenamiento>>
* <<cuentas de usuario de clúster autorizadas,Cuentas de usuario de clúster autorizadas para NetApp Hybrid Cloud Control>>




== cuentas de administrador de clúster de almacenamiento

En un clúster de almacenamiento que ejecuta el software NetApp Element, pueden existir dos tipos de cuentas de administrador:

* *Cuenta de administrador principal del clúster*: Esta cuenta de administrador se crea cuando se crea el clúster.  Esta cuenta es la cuenta administrativa principal con el nivel más alto de acceso al clúster.  Esta cuenta es análoga a un usuario root en un sistema Linux.  Puedes cambiar la contraseña de esta cuenta de administrador.
* *Cuenta de administrador de clúster*: Puede otorgar a una cuenta de administrador de clúster un rango limitado de acceso administrativo para realizar tareas específicas dentro de un clúster.  Las credenciales asignadas a cada cuenta de administrador del clúster se utilizan para autenticar las solicitudes de API y de la interfaz de usuario de Element dentro del sistema de almacenamiento.



NOTE: Se requiere una cuenta de administrador de clúster local (no LDAP) para acceder a los nodos activos de un clúster a través de la interfaz de usuario por nodo.  No se requieren credenciales de cuenta para acceder a un nodo que aún no forma parte de un clúster.

Puedelink:../storage/concept_system_manage_manage_cluster_administrator_users.html["administrar cuentas de administrador de clúster"] mediante la creación, eliminación y edición de cuentas de administrador de clúster, el cambio de la contraseña de administrador de clúster y la configuración de los ajustes LDAP para gestionar el acceso al sistema para los usuarios.



== Cuentas de usuario

Las cuentas de usuario se utilizan para controlar el acceso a los recursos de almacenamiento en una red basada en software NetApp Element .  Se requiere al menos una cuenta de usuario antes de poder crear un volumen.

Cuando se crea un volumen, este se asigna a una cuenta.  Si ha creado un volumen virtual, la cuenta es el contenedor de almacenamiento.

Aquí hay algunas consideraciones adicionales:

* La cuenta contiene la autenticación CHAP necesaria para acceder a los volúmenes que le han sido asignados.
* Una cuenta puede tener asignados hasta 2000 volúmenes, pero un volumen solo puede pertenecer a una cuenta.
* Las cuentas de usuario se pueden administrar desde el punto de extensión NetApp Element Management.




== cuentas de usuario de clúster autorizadas

Las cuentas de usuario autorizadas del clúster pueden autenticarse frente a cualquier recurso de almacenamiento asociado con la instancia de nodos y clústeres de NetApp Hybrid Cloud Control.  Con esta cuenta, puede administrar volúmenes, cuentas, grupos de acceso y más en todos los clústeres.

Las cuentas de usuario autorizadas se gestionan desde la opción "Gestión de usuarios" del menú superior derecho en NetApp Hybrid Cloud Control.

Ellink:../concepts/concept_intro_clusters.html#authoritative-storage-clusters["clúster de almacenamiento autorizado"] es el clúster de almacenamiento que NetApp Hybrid Cloud Control utiliza para autenticar a los usuarios.

Todos los usuarios creados en el clúster de almacenamiento autorizado pueden iniciar sesión en NetApp Hybrid Cloud Control.  Los usuarios creados en otros clústeres de almacenamiento _no_ pueden iniciar sesión en Hybrid Cloud Control.

* Si su nodo de administración solo tiene un clúster de almacenamiento, entonces ese es el clúster autoritativo.
* Si su nodo de administración tiene dos o más clústeres de almacenamiento, uno de esos clústeres se asigna como clúster autorizado y solo los usuarios de ese clúster pueden iniciar sesión en NetApp Hybrid Cloud Control.


Si bien muchas funciones de NetApp Hybrid Cloud Control funcionan con múltiples clústeres de almacenamiento, la autenticación y la autorización tienen limitaciones necesarias.  La limitación en torno a la autenticación y autorización es que los usuarios del clúster autoritativo pueden ejecutar acciones en otros clústeres vinculados a NetApp Hybrid Cloud Control incluso si no son usuarios de los otros clústeres de almacenamiento.  Antes de proceder a administrar varios clústeres de almacenamiento, debe asegurarse de que los usuarios definidos en los clústeres autorizados estén definidos en todos los demás clústeres de almacenamiento con los mismos permisos.  Puede administrar los usuarios desde NetApp Hybrid Cloud Control.



== Cuentas de volumen

Las cuentas específicas de volumen son específicas únicamente del clúster de almacenamiento en el que se crearon.  Estas cuentas permiten establecer permisos en volúmenes específicos de la red, pero no tienen efecto fuera de esos volúmenes.

Las cuentas de volumen se gestionan dentro de la tabla de volúmenes de control de la nube híbrida de NetApp .
