---
permalink: storage/concept_data_protection_volume_snapshot_backup_operations.html 
sidebar: sidebar 
keywords: volume snapshot, backup operations, back up volume snapshot, cluster, object store 
summary: Puede utilizar la función de copia de seguridad integrada para realizar una copia de seguridad de una instantánea de volumen.  Puede realizar copias de seguridad de instantáneas desde un clúster SolidFire a un almacenamiento de objetos externo o a otro clúster SolidFire .  Cuando se realiza una copia de seguridad de una instantánea en un almacenamiento de objetos externo, es necesario disponer de una conexión con dicho almacenamiento que permita operaciones de lectura/escritura. 
---
= Realizar una copia de seguridad de una instantánea de volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la función de copia de seguridad integrada para realizar una copia de seguridad de una instantánea de volumen.  Puede realizar copias de seguridad de instantáneas desde un clúster SolidFire a un almacenamiento de objetos externo o a otro clúster SolidFire .  Cuando se realiza una copia de seguridad de una instantánea en un almacenamiento de objetos externo, es necesario disponer de una conexión con dicho almacenamiento que permita operaciones de lectura/escritura.

* link:task_data_protection_back_up_a_volume_snapshot_to_an_amazon_s3_object_store["Realizar una copia de seguridad de una instantánea de volumen en un almacenamiento de objetos de Amazon S3"]
* link:task_data_protection_back_up_a_volume_snapshot_to_openstack_swift["Realizar una copia de seguridad de una instantánea de volumen en un almacén de objetos Swift de OpenStack"]
* link:task_data_protection_back_up_volume_to_solidfire["Realizar una copia de seguridad de una instantánea de volumen en un clúster SolidFire"]

