---
permalink: storage/concept_system_manage_drives_managing_drives.html 
sidebar: sidebar 
keywords: drives, manage, cluster, element ui, remove drives 
summary: Cada nodo contiene una o más unidades físicas que se utilizan para almacenar una parte de los datos del clúster.  El clúster utiliza la capacidad y el rendimiento de la unidad después de que esta se haya agregado correctamente al clúster.  Puedes utilizar la interfaz de usuario de Element para administrar las unidades. 
---
= Administrar unidades
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada nodo contiene una o más unidades físicas que se utilizan para almacenar una parte de los datos del clúster.  El clúster utiliza la capacidad y el rendimiento de la unidad después de que esta se haya agregado correctamente al clúster.  Puedes utilizar la interfaz de usuario de Element para administrar las unidades.



== Detalles de las unidades

La página Unidades en la pestaña Clúster proporciona una lista de las unidades activas en el clúster.  Puede filtrar la página seleccionando entre las pestañas Activos, Disponibles, Eliminando, Borrando y Fallidos.

Cuando se inicializa un clúster por primera vez, la lista de unidades activas está vacía.  Puede agregar unidades que no estén asignadas a un clúster y que aparezcan en la pestaña Disponible después de crear un nuevo clúster SolidFire .

Los siguientes elementos aparecen en la lista de unidades activas.

* *Identificador de unidad*
+
El número secuencial asignado a la unidad.

* *ID del nodo*
+
El número de nodo asignado cuando el nodo se agrega al clúster.

* *Nombre del nodo*
+
El nombre del nodo que aloja la unidad.

* *Ranura*
+
El número de ranura donde se encuentra físicamente la unidad.

* *Capacidad*
+
Tamaño de la unidad, en GB.

* *De serie*
+
El número de serie de la unidad.

* *Desgaste restante*
+
El indicador del nivel de desgaste.

+
El sistema de almacenamiento informa la cantidad aproximada de desgaste disponible en cada unidad de estado sólido (SSD) para la escritura y el borrado de datos.  Una unidad que ha consumido el 5 por ciento de sus ciclos de escritura y borrado diseñados reporta un desgaste restante del 95 por ciento.  El sistema no actualiza automáticamente la información sobre el desgaste de la unidad; puede actualizar la página o cerrarla y volver a cargarla para actualizar la información.

* *Tipo*
+
El tipo de transmisión.  El tipo puede ser bloque o metadatos.





== Para más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

