---
permalink: storage/concept_intro_storage_nodes.html 
sidebar: sidebar 
keywords: storage nodes, management nodes, block space, metadata space, data management, storage management, Bond10G, network interface, network, metadata, data storage, storage, drives, network interfaces 
summary: Un nodo de almacenamiento SolidFire es un servidor que contiene una colección de unidades que se comunican entre sí a través de la interfaz de red Bond10G.  Las unidades del nodo contienen espacio de bloques y metadatos para el almacenamiento y la gestión de datos. 
---
= nodos de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un nodo de almacenamiento SolidFire es un servidor que contiene una colección de unidades que se comunican entre sí a través de la interfaz de red Bond10G.  Las unidades del nodo contienen espacio de bloques y metadatos para el almacenamiento y la gestión de datos.

Los nodos de almacenamiento tienen las siguientes características:

* Cada nodo tiene un nombre único.  Si un administrador no especifica un nombre de nodo, se utilizará por defecto SF-XXXX, donde XXXX son cuatro caracteres aleatorios generados por el sistema.
* Cada nodo tiene su propia memoria caché de escritura de memoria de acceso aleatorio no volátil (NVRAM) de alto rendimiento para mejorar el rendimiento general del sistema y reducir la latencia de escritura.
* Cada nodo está conectado a dos redes, una de almacenamiento y otra de gestión, cada una con dos enlaces independientes para redundancia y rendimiento.  Cada nodo requiere una dirección IP en cada red.
* Puede crear un clúster con nuevos nodos de almacenamiento o agregar nodos de almacenamiento a un clúster existente para aumentar la capacidad y el rendimiento del almacenamiento.
* Puede agregar o eliminar nodos del clúster en cualquier momento sin interrumpir el servicio.

