---
permalink: storage/concept_system_manage_key_get_started_with_external_key_management.html 
sidebar: sidebar 
keywords: kmip, master key, key management, encryption at rest, software encryption at rest, ekm, ak, eks, seds 
summary: 'La gestión de claves externas (EKM) proporciona una gestión segura de claves de autenticación (AK) junto con un servidor de claves externo fuera del clúster (EKS).  Las claves de acceso (AK) se utilizan para bloquear y desbloquear las unidades de autocifrado (SED) cuando el cifrado en reposo está habilitado en el clúster.' 
---
= Comience con la administración de claves externas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La gestión de claves externas (EKM) proporciona una gestión segura de claves de autenticación (AK) junto con un servidor de claves externas fuera del clúster (EKS).  Las AK se utilizan para bloquear y desbloquear unidades de autocifrado (SED) cuandolink:../concepts/concept_solidfire_concepts_security.html["cifrado en reposo"] está habilitado en el clúster.  El EKS proporciona generación y almacenamiento seguros de los AK.  El clúster utiliza el protocolo de interoperabilidad de gestión de claves (KMIP), un protocolo estándar definido por OASIS, para comunicarse con el EKS.

* link:task_system_manage_key_set_up_external_key_management.html["Establecer la gestión externa"]
* link:task_system_manage_rekey_software_ear_master_key.html["Rekey cifrado de software en reposo clave maestra"]
* link:concept_system_manage_key_recover_inaccessible_or_invalid_authentication_keys["Recuperar claves de autenticación inaccesibles o no válidas"]
* link:concept_system_manage_key_external_key_management_api_commands.html["Comandos de la API de administración de claves externas"]


[discrete]
== Encuentra más información

* link:../api/reference_element_api_createcluster.html["API CreateCluster que se puede usar para habilitar el cifrado de software en reposo"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de los productos NetApp SolidFire y Element"^]

