---
permalink: storage/concept_system_manage_nodes_manage_nodes.html 
sidebar: sidebar 
keywords: nodes, manage, cluster, capacity rule, pairs, stranded nodes 
summary: Puede administrar el almacenamiento SolidFire y los nodos Fibre Channel desde la página Nodos de la pestaña Clúster. 
---
= Gestionar nodos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede administrar el almacenamiento SolidFire y los nodos Fibre Channel desde la página Nodos de la pestaña Clúster.

Si un nodo recién agregado representa más del 50 por ciento de la capacidad total del clúster, parte de la capacidad de este nodo se vuelve inutilizable ("varada"), de modo que cumpla con la regla de capacidad.  Esto seguirá siendo así hasta que se añada más capacidad de almacenamiento.  Si se añade un nodo muy grande que también incumple la regla de capacidad, el nodo que antes estaba aislado dejará de estarlo, mientras que el nodo recién añadido quedará aislado.  La capacidad siempre debe añadirse por pares para evitar que esto ocurra.  Cuando un nodo queda aislado, se genera un fallo de clúster apropiado.



== Encuentra más información

xref:task_system_manage_nodes_adding_a_node_to_a_cluster.adoc[Agregar un nodo a un clúster]
