---
permalink: storage/reference_copyright.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Copyright
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Copyright © 2021 NetApp, Inc. Todos los derechos reservados. Impreso en EE. UU.

Ninguna parte de este documento protegido por derechos de autor puede ser reproducida de ninguna forma ni por ningún medio —gráfico, electrónico o mecánico, incluyendo fotocopiado, grabación, transferencia electrónica o almacenamiento en un sistema de recuperación electrónica— sin la autorización previa por escrito del propietario de los derechos de autor.

El software derivado de material protegido por derechos de autor de NetApp está sujeto a la siguiente licencia y exención de responsabilidad:

ESTE SOFTWARE ES PROPORCIONADO POR NETAPP "TAL CUAL" Y SIN NINGUNA GARANTÍA EXPRESA O IMPLÍCITA, INCLUIDAS, ENTRE OTRAS, LAS GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD E IDONEIDAD PARA UN PROPÓSITO PARTICULAR, LAS CUALES QUEDAN EXCLUIDAS POR LA PRESENTE.  EN NINGÚN CASO NETAPP SERÁ RESPONSABLE DE NINGÚN DAÑO DIRECTO, INDIRECTO, INCIDENTAL, ESPECIAL, EJEMPLAR O CONSECUENCIAL (INCLUIDOS, ENTRE OTROS, LA ADQUISICIÓN DE BIENES O SERVICIOS SUSTITUTOS; LA PÉRDIDA DE USO, DATOS O BENEFICIOS; O LA INTERRUPCIÓN DEL NEGOCIO), INDEPENDIENTEMENTE DE SU CAUSA Y DE LA TEORÍA DE RESPONSABILIDAD APLICABLE, YA SEA CONTRACTUAL, OBJETIVA O EXTRACONTRACTUAL (INCLUIDA LA NEGLIGENCIA), QUE SURJA DE CUALQUIER FORMA DEL USO DE ESTE SOFTWARE, INCLUSO SI SE HA INFORMADO DE LA POSIBILIDAD DE DICHO DAÑO.

NetApp se reserva el derecho de modificar cualquiera de los productos descritos en este documento en cualquier momento y sin previo aviso.  NetApp no ​​asume ninguna responsabilidad derivada del uso de los productos aquí descritos, salvo que NetApp lo acepte expresamente por escrito.  El uso o la compra de este producto no otorga ninguna licencia bajo derechos de patente, derechos de marca registrada ni ningún otro derecho de propiedad intelectual de NetApp.

Es posible que el producto que se describe en el presente manual esté protegido por una o más patentes de EE. UU., patentes de otros países o aplicaciones pendientes.

Los datos aquí contenidos pertenecen a un artículo comercial (según se define en FAR 2.101) y son propiedad de NetApp, Inc. El Gobierno de los Estados Unidos tiene una licencia no exclusiva, intransferible, no sublicenciable, mundial, limitada e irrevocable para usar los datos únicamente en relación con y en apoyo del contrato del Gobierno de los Estados Unidos bajo el cual se entregaron los datos.  Excepto según lo dispuesto en el presente documento, los Datos no podrán ser utilizados, divulgados, reproducidos, modificados, ejecutados o mostrados sin la aprobación previa por escrito de NetApp, Inc. Los derechos de licencia del Gobierno de los Estados Unidos para el Departamento de Defensa se limitan a los derechos identificados en la cláusula DFARS 252.227-7015(b).
