---
permalink: storage/reference_system_manage_fips_ssl_cipher_changes.html 
sidebar: sidebar 
keywords: fips, ssl ciphers, 140-2, encryption algorithms 
summary: Los cifrados SSL son algoritmos de cifrado utilizados por los hosts para establecer una comunicación segura.  Existen cifrados estándar que admite el software Element y cifrados no estándar cuando está habilitado el modo FIPS 140-2. 
---
= cifrados SSL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los cifrados SSL son algoritmos de cifrado utilizados por los hosts para establecer una comunicación segura.  Existen cifrados estándar que admite el software Element y cifrados no estándar cuando está habilitado el modo FIPS 140-2.

Las siguientes listas proporcionan los cifrados SSL (Secure Socket Layer) estándar compatibles con el software Element y los cifrados SSL compatibles cuando el modo FIPS 140-2 está habilitado:

* *FIPS 140-2 desactivado*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A

+
TLS_ECDHE_RSA_CON_AES_128_CBC_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_CON_AES_128_GCM_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_CON_AES_256_CBC_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_CON_AES_256_GCM_SHA384 (secp256r1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C

+
TLS_RSA_CON_AES_128_CBC_SHA (rsa 2048) - A

+
TLS_RSA_CON_AES_128_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_CON_AES_128_GCM_SHA256 (rsa 2048) - A

+
TLS_RSA_CON_AES_256_CBC_SHA (rsa 2048) - A

+
TLS_RSA_CON_AES_256_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_CON_AES_256_GCM_SHA384 (rsa 2048) - A

+
TLS_RSA_CON_CAMELLIA_128_CBC_SHA (rsa 2048) - A

+
TLS_RSA_CON_CAMELLIA_256_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_IDEA_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_RC4_128_MD5 (rsa 2048) - C

+
TLS_RSA_CON_RC4_128_SHA (rsa 2048) - C

+
TLS_RSA_WITH_SEED_CBC_SHA (rsa 2048) - A

* *FIPS 140-2 habilitado*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A

+
TLS_ECDHE_RSA_CON_AES_128_CBC_SHA256 (sección 571r1) - A

+
TLS_ECDHE_RSA_CON_AES_128_CBC_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_CON_AES_128_GCM_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_CON_AES_128_GCM_SHA256 (sect571r1) - A

+
TLS_ECDHE_RSA_CON_AES_256_CBC_SHA384 (sección 571r1) - A

+
TLS_ECDHE_RSA_CON_AES_256_CBC_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_CON_AES_256_GCM_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_CON_AES_256_GCM_SHA384 (sección 571r1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C

+
TLS_RSA_CON_AES_128_CBC_SHA (rsa 2048) - A

+
TLS_RSA_CON_AES_128_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_CON_AES_128_GCM_SHA256 (rsa 2048) - A

+
TLS_RSA_CON_AES_256_CBC_SHA (rsa 2048) - A

+
TLS_RSA_CON_AES_256_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_CON_AES_256_GCM_SHA384 (rsa 2048) - A





== Encuentra más información

xref:task_system_manage_fips_enable_fips_140_2_for_https.adoc[Habilite FIPS 140-2 para HTTPS en su clúster.]
