---
permalink: storage/task_per_node_run_system_utilities.html 
sidebar: sidebar 
keywords: storage nodes, running system utilities, system utilities, network settings, testing changes, reboot the node, power cycle, shuts down the node 
summary: Puede utilizar la interfaz de usuario por nodo para el nodo de almacenamiento para crear o eliminar paquetes de soporte, restablecer la configuración de las unidades y reiniciar los servicios de red o de clúster. 
---
= Ejecute las utilidades del sistema mediante la interfaz de usuario de cada nodo.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la interfaz de usuario por nodo para el nodo de almacenamiento para crear o eliminar paquetes de soporte, restablecer la configuración de las unidades y reiniciar los servicios de red o de clúster.

Has iniciado sesión en la interfaz de usuario por nodo para el nodo de almacenamiento.

. Haz clic en *Utilidades del sistema*.
. Haz clic en el botón de la utilidad del sistema que deseas ejecutar.
+
** *Control de potencia*
+
Reinicia, apaga o desconecta el nodo.

+

IMPORTANT: Esta operación provoca una pérdida temporal de la conectividad de red.

+
Especifique los siguientes parámetros:

+
*** Acción: Las opciones incluyen Reiniciar y Detener (apagar).
*** Retardo de activación: Cualquier tiempo adicional antes de que el nodo vuelva a estar en línea.


** *Recopilar registros de nodos*
+
Crea un paquete de soporte en el directorio /tmp/bundles del nodo.

+
Especifique los siguientes parámetros:

+
*** Nombre del paquete: Nombre único para cada paquete de soporte creado.  Si no se proporciona ningún nombre, se utilizará "supportbundle" y el nombre del nodo como nombre de archivo.
*** Argumentos adicionales: Este parámetro se pasa al script sf_make_support_bundle.  Este parámetro solo debe utilizarse a petición del soporte de NetApp .
*** Tiempo de espera (seg.): Especifique el número de segundos que se esperarán para cada respuesta de ping individual.


** *Eliminar registros del nodo*
+
Elimina cualquier paquete de soporte actual en el nodo que se haya creado utilizando *Create Cluster Support Bundle* o el método de API CreateSupportBundle.

** *Restablecer unidades*
+
Inicializa las unidades y elimina todos los datos que residen actualmente en la unidad.  Puedes reutilizar la unidad en un nodo existente o en un nodo actualizado.

+
Especifique el siguiente parámetro:

+
*** Unidades: Lista de nombres de dispositivos (no identificadores de unidad) para restablecer.


** *Restablecer configuración de red*
+
Ayuda a resolver problemas de configuración de red para un nodo individual y restablece la configuración de red de un nodo individual a la configuración predeterminada de fábrica.

** *Reiniciar nodo*
+
Restablece un nodo a la configuración de fábrica.  Durante esta operación se eliminan todos los datos, pero se conservan los ajustes de red del nodo.  Los nodos solo se pueden reiniciar si no están asignados a un clúster y se encuentran en estado Disponible.

+

IMPORTANT: Al utilizar esta opción, se eliminan del nodo todos los datos, paquetes (actualizaciones de software), configuraciones y archivos de registro.

** *Reiniciar la conexión de red*
+
Reinicia todos los servicios de red en un nodo.

+

IMPORTANT: Esta operación puede provocar una pérdida temporal de la conectividad de la red.

** *Reiniciar servicios*
+
Reinicia los servicios de software Element en un nodo.

+

IMPORTANT: Esta operación puede provocar una interrupción temporal del servicio del nodo.  Esta operación solo debe realizarse bajo la dirección del soporte de NetApp .

+
Especifique los siguientes parámetros:

+
*** Servicio: Nombre del servicio que se reiniciará.
*** Acción: Acción a realizar en el servicio.  Las opciones incluyen iniciar, detener y reiniciar.





