---
permalink: storage/task_data_protection_back_up_volume_to_solidfire.html 
sidebar: sidebar 
keywords: volume backup, solidfire storage cluster 
summary: Puede realizar copias de seguridad de los volúmenes que residen en un clúster en un clúster remoto para clústeres de almacenamiento que ejecutan el software Element. 
---
= Realizar una copia de seguridad de un volumen en un clúster de almacenamiento SolidFire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar copias de seguridad de los volúmenes que residen en un clúster en un clúster remoto para clústeres de almacenamiento que ejecutan el software Element.

Asegúrese de que los clústeres de origen y destino estén emparejados.

Verlink:task_replication_pair_clusters.html["Agrupaciones de pares para replicación"] .

Al realizar copias de seguridad o restauraciones de un clúster a otro, el sistema genera una clave que se utilizará para la autenticación entre los clústeres.  Esta clave de escritura de volumen masivo permite que el clúster de origen se autentique con el clúster de destino, proporcionando un nivel de seguridad al escribir en el volumen de destino.  Como parte del proceso de copia de seguridad o restauración, debe generar una clave de escritura de volumen masivo desde el volumen de destino antes de iniciar la operación.

. En el clúster de destino, *Administración* > *Volúmenes*.
. Haz clic en el icono Acciones del volumen de destino.
. En el menú que aparece, haga clic en *Restaurar desde*.
. En el cuadro de diálogo *Restauración integrada*, en *Restaurar desde*, seleccione * SolidFire*.
. Seleccione una opción en *Formato de datos*:
+
** *Nativo*: Un formato comprimido legible únicamente por los sistemas de almacenamiento SolidFire .
** *Sin comprimir*: Un formato sin comprimir compatible con otros sistemas.


. Haz clic en *Generar clave*.
. Copie la clave del cuadro *Clave de escritura de volumen masivo* al portapapeles.
. En el clúster de origen, vaya a *Administración* > *Volúmenes*.
. Haz clic en el icono de Acciones del volumen que deseas respaldar.
. En el menú resultante, haga clic en *Realizar copia de seguridad en*.
. En el cuadro de diálogo *Copia de seguridad integrada*, en *Realizar copia de seguridad en*, seleccione * SolidFire*.
. Seleccione la misma opción que seleccionó anteriormente en el campo *Formato de datos*.
. Introduzca la dirección IP virtual de gestión del clúster del volumen de destino en el campo *MVIP de clúster remoto*.
. Introduzca el nombre de usuario del clúster remoto en el campo *Nombre de usuario del clúster remoto*.
. Introduzca la contraseña del clúster remoto en el campo *Contraseña del clúster remoto*.
. En el campo *Clave de escritura de volumen masivo*, pegue la clave que generó anteriormente en el clúster de destino.
. Haz clic en *Iniciar lectura*.

