---
permalink: storage/task_data_protection_create_a_group_snapshot.html 
sidebar: sidebar 
keywords: group snapshot, create, volumes, schedule, automate group snapshots 
summary: Puede crear una instantánea de un grupo de volúmenes, y también puede crear una programación de instantáneas de grupo para automatizar las instantáneas de grupo.  Una única instantánea de grupo puede capturar de forma consistente hasta 32 volúmenes a la vez. 
---
= Creación de una instantánea de grupo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear una instantánea de un grupo de volúmenes, y también puede crear una programación de instantáneas de grupo para automatizar las instantáneas de grupo.  Una única instantánea de grupo puede capturar de forma consistente hasta 32 volúmenes a la vez.

.Pasos
. Haz clic en *Administración* > *Volúmenes*.
. Utilice las casillas de verificación para seleccionar varios volúmenes para un grupo de volúmenes.
. Haz clic en *Acciones en lote*.
. Haga clic en *Instantánea de grupo*.
. Introduzca un nuevo nombre para la instantánea de grupo en el cuadro de diálogo Crear instantánea de grupo de volúmenes.
. *Opcional:* Seleccione la casilla de verificación *Incluir cada miembro de la instantánea del grupo en la replicación cuando se emparejen* para garantizar que cada instantánea se capture en la replicación cuando se empareje el volumen principal.
. Seleccione una opción de retención para la instantánea del grupo:
+
** Haz clic en *Conservar para siempre* para guardar la instantánea en el sistema indefinidamente.
** Haz clic en *Establecer período de retención* y usa los controles de fecha para elegir el tiempo durante el cual el sistema conservará la instantánea.


. Para tomar una instantánea única e inmediata, siga los siguientes pasos:
+
.. Haz clic en *Tomar instantánea de grupo ahora*.
.. Haz clic en *Crear instantánea de grupo*.


. Para programar la ejecución de la instantánea en un momento futuro, siga los siguientes pasos:
+
.. Haga clic en *Crear programación de instantáneas de grupo*.
.. Ingrese un *Nuevo Nombre de Horario*.
.. Seleccione un *Tipo de horario* de la lista.
.. *Opcional:* Seleccione la casilla de verificación *Programación recurrente* para repetir la instantánea programada periódicamente.
.. Haz clic en *Crear horario*.



