---
permalink: storage/task-element-replication-create-snapmirror-endpoint.html 
sidebar: sidebar 
keywords: ontap, cli, create, snapmirror, endpoint 
summary: Debes crear un punto de conexión SnapMirror antes de poder crear una relación de replicación. Esta tarea solo se puede realizar en la interfaz web del software Element o utilizando los métodos de la API. 
---
= Crea un punto de conexión de SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debes crear un punto de conexión SnapMirror antes de poder crear una relación de replicación. Esta tarea solo se puede realizar en la interfaz web del software Element o utilizando link:../api/reference_element_api_abortsnapmirrorrelationship.html["Métodos de la API de SnapMirror"].

.Antes de empezar
Debes haber habilitado SnapMirror en el clúster Element.

.Pasos
. Haga clic en *Protección de datos* > *Puntos de conexión de SnapMirror *.
. Haz clic en *Crear punto de conexión*.
. En el cuadro de diálogo *Crear un nuevo punto de conexión*, introduzca la dirección IP de administración del clúster ONTAP .
. Introduzca el ID de usuario y la contraseña del administrador del clúster ONTAP .
. Haz clic en *Crear punto de conexión*.

