---
permalink: storage/task_system_manage_virtual_enable_virtual_routing_and_forwarding.html 
sidebar: sidebar 
keywords: virtual routing, forwarding, enable, vrf, storage networks, create a vlan 
summary: 'Puede habilitar el enrutamiento y reenvío virtual (VRF), lo que permite que existan varias instancias de una tabla de enrutamiento en un enrutador y funcionen simultáneamente.  Esta funcionalidad solo está disponible para redes de almacenamiento.' 
---
= Habilitar el enrutamiento y reenvío virtual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar el enrutamiento y reenvío virtual (VRF), lo que permite que existan varias instancias de una tabla de enrutamiento en un enrutador y funcionen simultáneamente.  Esta funcionalidad solo está disponible para redes de almacenamiento.

Solo puedes habilitar VRF al momento de crear una VLAN.  Si desea volver a un modo no VRF, deberá eliminar y volver a crear la VLAN.

. Haga clic en *Clúster* > *Red*.
. Para habilitar VRF en una nueva VLAN, seleccione *Crear VLAN*.
+
.. Introduzca la información pertinente para la nueva VRF/VLAN.  Consulte la sección "Agregar una red virtual".
.. Seleccione la casilla de verificación *Habilitar VRF*.
.. *Opcional*: Introduzca una puerta de enlace.


. Haga clic en *Crear VLAN*.




== Encuentra más información

xref:task_system_manage_virtual_add_a_virtual_network.adoc[Agregar una red virtual]
