---
permalink: storage/task_data_manage_vvol_create_a_storage_container.html 
sidebar: sidebar 
keywords: storage container, create 
summary: Puede crear contenedores de almacenamiento en la interfaz de usuario de Element y descubrirlos en vCenter.  Debe crear al menos un contenedor de almacenamiento para comenzar a aprovisionar máquinas virtuales respaldadas por VVol. 
---
= Crea un contenedor de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear contenedores de almacenamiento en la interfaz de usuario de Element y descubrirlos en vCenter.  Debe crear al menos un contenedor de almacenamiento para comenzar a aprovisionar máquinas virtuales respaldadas por VVol.

Has habilitado la funcionalidad VVols en la interfaz de usuario de Element para el clúster.

. Seleccione *VVols* > *Contenedores de almacenamiento*.
. Haz clic en el botón *Crear contenedores de almacenamiento*.
. Introduzca la información del contenedor de almacenamiento en el cuadro de diálogo *Crear un nuevo contenedor de almacenamiento*:
+
.. Introduzca un nombre para el contenedor de almacenamiento.
.. Configure los secretos de iniciador y destino para CHAP.
+

TIP: Deje en blanco los campos de Configuración CHAP para generar secretos automáticamente.

.. Haz clic en el botón *Crear contenedor de almacenamiento*.


. Verifique que el nuevo contenedor de almacenamiento aparezca en la lista de la subpestaña *Contenedores de almacenamiento*.
+

NOTE: Dado que se crea automáticamente un ID de cuenta de NetApp Element y se asigna al contenedor de almacenamiento, no es necesario crear una cuenta manualmente.


