---
permalink: storage/task_data_manage_vvol_delete_a_virtual_volume.html 
sidebar: sidebar 
keywords: virtual volume, delete, vvols, use Element UI to delete a vvol 
summary: Aunque los volúmenes virtuales siempre deben eliminarse desde la capa de administración de VMware, la funcionalidad para eliminar volúmenes virtuales está habilitada desde la interfaz de usuario de Element.  Solo debes eliminar un volumen virtual desde la interfaz de usuario de Element cuando sea absolutamente necesario, por ejemplo, cuando vSphere no pueda limpiar los volúmenes virtuales en el almacenamiento SolidFire . 
---
= Eliminar un volumen virtual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aunque los volúmenes virtuales siempre deben eliminarse desde la capa de administración de VMware, la funcionalidad para eliminar volúmenes virtuales está habilitada desde la interfaz de usuario de Element.  Solo debes eliminar un volumen virtual desde la interfaz de usuario de Element cuando sea absolutamente necesario, por ejemplo, cuando vSphere no pueda limpiar los volúmenes virtuales en el almacenamiento SolidFire .

. Seleccione *VVols* > *Volúmenes virtuales*.
. Haz clic en el icono Acciones del volumen virtual que deseas eliminar.
. En el menú que aparece, seleccione *Eliminar*.
+

IMPORTANT: Debe eliminar un volumen virtual de la capa de administración de VMware para asegurarse de que el volumen virtual se desvincule correctamente antes de su eliminación.  Solo debes eliminar un volumen virtual desde la interfaz de usuario de Element cuando sea absolutamente necesario, por ejemplo, cuando vSphere no pueda limpiar los volúmenes virtuales en el almacenamiento SolidFire .  Si elimina un volumen virtual desde la interfaz de usuario de Element, el volumen se eliminará inmediatamente.

. Confirma la acción.
. Actualice la lista de volúmenes virtuales para confirmar que el volumen virtual se ha eliminado.
. *Opcional*: Seleccione *Informes* > *Registro de eventos* para confirmar que la purga se ha realizado correctamente.

