---
permalink: storage/task-element-replication-create-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, element, source, destination 
summary: Puede utilizar SnapMirror para replicar copias de instantáneas de un volumen Element en un sistema de destino ONTAP .  En caso de desastre en el sitio de Element, puede proporcionar datos a los clientes desde el sistema ONTAP y luego reactivar el volumen de origen de Element cuando se restablezca el servicio. 
---
= Cree una relación desde un origen Element a un destino ONTAP .
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La relación entre el volumen de origen en el almacenamiento primario y el volumen de destino en el almacenamiento secundario se denomina _relación de protección de datos_.  Puedes usar el `snapmirror create` comando para crear una relación de protección de datos desde una fuente Element a un destino ONTAP , o desde una fuente ONTAP a un destino Element.

Puede utilizar SnapMirror para replicar copias de instantáneas de un volumen Element en un sistema de destino ONTAP .  En caso de desastre en el sitio de Element, puede proporcionar datos a los clientes desde el sistema ONTAP y luego reactivar el volumen de origen de Element cuando se restablezca el servicio.

.Antes de empezar
* El nodo Element que contiene el volumen que se va a replicar debe haber sido hecho accesible para ONTAP.
* El volumen Element debe haber estado habilitado para la replicación SnapMirror .
* Si está utilizando el tipo de política "`mirror-vault`", debe haberse configurado una etiqueta SnapMirror para que se repliquen las copias de instantáneas de Element.
+
[NOTE]
====
Solo puedes realizar esta tarea en ellink:concept_snapmirror_labels.html["Interfaz web del software Element"] o utilizando ellink:../api/concept_element_api_snapshots_overview.html["Métodos API"] .

====


.Acerca de esta tarea
Debe especificar la ruta de origen del elemento en el formulario `<hostip:>/lun/<name>` , donde "`lun`" es la cadena real "`lun`" y `name` es el nombre del volumen de Element.

Un volumen Element es aproximadamente equivalente a un LUN de ONTAP .  SnapMirror crea un LUN con el nombre del volumen de Element cuando se inicializa una relación de protección de datos entre el software Element y ONTAP .  SnapMirror replica los datos a una LUN existente si la LUN cumple los requisitos para la replicación desde el software Element a ONTAP.

Las reglas de replicación son las siguientes:

* Un volumen ONTAP solo puede contener datos de un volumen Element.
* No se pueden replicar datos de un volumen ONTAP a varios volúmenes Element.


En ONTAP 9.3 y versiones anteriores, un volumen de destino puede contener hasta 251 copias de instantáneas.  En ONTAP 9.4 y versiones posteriores, un volumen de destino puede contener hasta 1019 copias de instantáneas.

.Paso
. Desde el clúster de destino, cree una relación de replicación desde un origen Element a un destino ONTAP :
+
`snapmirror create -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume> -type XDP -schedule schedule -policy <policy>`

+
Para conocer la sintaxis completa del comando, consulte la página del manual.

+
El siguiente ejemplo crea una relación de recuperación ante desastres de SnapMirror utilizando la configuración predeterminada. `MirrorLatest` política:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
El siguiente ejemplo crea una relación de replicación unificada utilizando la configuración predeterminada. `MirrorAndVault` política:

+
[listing]
----
cluster_dst:> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
El siguiente ejemplo crea una relación de replicación unificada utilizando `Unified7year` política:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy Unified7year
----
+
El siguiente ejemplo crea una relación de replicación unificada utilizando la opción personalizada. `my_unified` política:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----


.Después de terminar
Utilice el `snapmirror show` comando para verificar que se creó la relación SnapMirror .  Para conocer la sintaxis completa del comando, consulte la página del manual.
