---
permalink: storage/task_system_manage_virtual_add_a_virtual_network.html 
sidebar: sidebar 
keywords: virtual network, add, cluster configuration, cluster nodes, svip, vlans, vrf, view, network details, 
summary: Puede agregar una nueva red virtual a una configuración de clúster para habilitar una conexión de entorno multiinquilino a un clúster que ejecuta el software Element. 
---
= Agregar una red virtual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede agregar una nueva red virtual a una configuración de clúster para habilitar una conexión de entorno multiinquilino a un clúster que ejecuta el software Element.

.Lo que necesitarás
* Identifique el bloque de direcciones IP que se asignarán a las redes virtuales en los nodos del clúster.
* Identifique una dirección IP de red de almacenamiento (SVIP) que se utilizará como punto final para todo el tráfico de almacenamiento de NetApp Element .



IMPORTANT: Para esta configuración, debe tener en cuenta los siguientes criterios:

* Las VLAN que no tienen habilitado VRF requieren que los iniciadores estén en la misma subred que la SVIP.
* Las VLAN que tienen habilitado VRF no requieren que los iniciadores estén en la misma subred que la SVIP, y se admite el enrutamiento.
* La SVIP predeterminada no requiere que los iniciadores estén en la misma subred que la SVIP, y admite el enrutamiento.


Cuando se agrega una red virtual, se crea una interfaz para cada nodo y cada una requiere una dirección IP de red virtual.  El número de direcciones IP que especifique al crear una nueva red virtual debe ser igual o mayor que el número de nodos del clúster.  Las direcciones de red virtuales se aprovisionan de forma masiva y se asignan a nodos individuales automáticamente.  No es necesario asignar manualmente direcciones de red virtuales a los nodos del clúster.

.Pasos
. Haga clic en *Clúster* > *Red*.
. Haga clic en *Crear VLAN*.
. En el cuadro de diálogo *Crear una nueva VLAN*, introduzca los valores en los siguientes campos:
+
** *Nombre de VLAN*
** *Etiqueta VLAN*
** *SVIP*
** *Máscara de red*
** (Opcional) *Descripción*


. Ingrese la dirección *IP inicial* para el rango de direcciones IP en *Bloques de direcciones IP*.
. Ingrese el *Tamaño* del rango de IP como el número de direcciones IP que se incluirán en el bloque.
. Haz clic en *Agregar un bloque* para añadir un bloque no contiguo de direcciones IP para esta VLAN.
. Haga clic en *Crear VLAN*.




== Ver detalles de la red virtual

.Pasos
. Haga clic en *Clúster* > *Red*.
. Revise los detalles.
+
** *ID*: Identificador único de la red VLAN, asignado por el sistema.
** *Nombre*: Nombre único asignado por el usuario para la red VLAN.
** *Etiqueta VLAN*: Etiqueta VLAN asignada cuando se creó la red virtual.
** *SVIP*: Dirección IP virtual de almacenamiento asignada a la red virtual.
** *Máscara de red*: Máscara de red para esta red virtual.
** *Puerta de enlace*: Dirección IP única de una puerta de enlace de red virtual.  VRF debe estar habilitado.
** *VRF habilitado*: Indicación de si el enrutamiento y reenvío virtual está habilitado o no.
** *Direcciones IP utilizadas*: El rango de direcciones IP de red virtual utilizadas para la red virtual.



