---
permalink: storage/task_data_protection_back_up_volume_snapshot_to_solidfire.html 
sidebar: sidebar 
keywords: volume snapshot, backup, solidfire cluster 
summary: Puede realizar copias de seguridad de instantáneas de volumen que residen en un clúster SolidFire en un clúster SolidFire remoto. 
---
= Realizar una copia de seguridad de una instantánea de volumen en un clúster SolidFire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar copias de seguridad de instantáneas de volumen que residen en un clúster SolidFire en un clúster SolidFire remoto.

Asegúrese de que los clústeres de origen y destino estén emparejados.

Al realizar copias de seguridad o restauraciones de un clúster a otro, el sistema genera una clave que se utilizará para la autenticación entre los clústeres.  Esta clave de escritura de volumen masivo permite que el clúster de origen se autentique con el clúster de destino, proporcionando un nivel de seguridad al escribir en el volumen de destino.  Como parte del proceso de copia de seguridad o restauración, debe generar una clave de escritura de volumen masivo desde el volumen de destino antes de iniciar la operación.

. En el clúster de destino, haga clic en *Administración* > *Volúmenes*.
. Haga clic en el icono *Acciones* del volumen de destino.
. En el menú que aparece, haga clic en *Restaurar desde*.
. En el cuadro de diálogo *Restauración integrada*, en *Restaurar desde*, seleccione * SolidFire*.
. Seleccione un formato de datos en *Formato de datos*:
+
** *Nativo*: Un formato comprimido legible únicamente por los sistemas de almacenamiento SolidFire .
** *Sin comprimir*: Un formato sin comprimir compatible con otros sistemas.


. Haz clic en *Generar clave*.
. Copie la clave del cuadro *Clave de escritura de volumen masivo* al portapapeles.
. En el clúster de origen, haga clic en *Protección de datos* > *Instantáneas*.
. Haz clic en el icono Acciones de la instantánea que quieras usar para la copia de seguridad.
. En el menú resultante, haga clic en *Realizar copia de seguridad en*.
. En el cuadro de diálogo **Copia de seguridad integrada**, en *Realizar copia de seguridad en*, seleccione * SolidFire*.
. Seleccione el mismo formato de datos que seleccionó anteriormente en el campo *Formato de datos*.
. Introduzca la dirección IP virtual de gestión del clúster del volumen de destino en el campo *MVIP de clúster remoto*.
. Introduzca el nombre de usuario del clúster remoto en el campo *Nombre de usuario del clúster remoto*.
. Introduzca la contraseña del clúster remoto en el campo *Contraseña del clúster remoto*.
. En el campo *Clave de escritura de volumen masivo*, pegue la clave que generó anteriormente en el clúster de destino.
. Haz clic en *Iniciar lectura*.

