---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'Puede cambiar la contraseña de administrador predeterminada de la interfaz de administración de plataforma inteligente (IPMI) tan pronto como tenga acceso IPMI remoto al nodo.  Es posible que desee hacer esto si hubiera alguna actualización de instalación.' 
---
= Cambiar la contraseña IPMI predeterminada para los nodos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar la contraseña de administrador predeterminada de la interfaz de administración de plataforma inteligente (IPMI) tan pronto como tenga acceso IPMI remoto al nodo.  Es posible que desee hacer esto si hubiera alguna actualización de instalación.

Para obtener detalles sobre la configuración del acceso IPM para los nodos, consultelink:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["Configure IPMI para cada nodo"^] .

Puedes cambiar la contraseña de IPM para estos nodos:

* nodos H410S
* nodos H610S




== Cambiar la contraseña IPMI predeterminada para los nodos H410S

Debe cambiar la contraseña predeterminada de la cuenta de administrador de IPMI en cada nodo de almacenamiento tan pronto como configure el puerto de red IPMI.

.Lo que necesitarás
Deberías haber configurado la dirección IP IPMI para cada nodo de almacenamiento.

.Pasos
. Abra un navegador web en un ordenador que pueda acceder a la red IPMI y navegue hasta la dirección IP IPMI del nodo.
. Introduzca el nombre de usuario `ADMIN` y contraseña `ADMIN` en la pantalla de inicio de sesión.
. Tras iniciar sesión, haga clic en la pestaña *Configuración*.
. Haz clic en *Usuarios*.
. Seleccione el `ADMIN` usuario y haga clic en *Modificar usuario*.
. Seleccione la casilla de verificación *Cambiar contraseña*.
. Introduzca una nueva contraseña en los campos *Contraseña* y *Confirmar contraseña*.
. Haz clic en *Modificar* y luego en *Aceptar*.
. Repita este procedimiento para cualquier otro nodo H410S con contraseñas IPMI predeterminadas.




== Cambiar la contraseña IPMI predeterminada para los nodos H610S

Debe cambiar la contraseña predeterminada de la cuenta de administrador de IPMI en cada nodo de almacenamiento tan pronto como configure el puerto de red IPMI.

.Lo que necesitarás
Deberías haber configurado la dirección IP IPMI para cada nodo de almacenamiento.

.Pasos
. Abra un navegador web en un ordenador que pueda acceder a la red IPMI y navegue hasta la dirección IP IPMI del nodo.
. Introduzca el nombre de usuario `root` y contraseña `calvin` en la pantalla de inicio de sesión.
. Tras iniciar sesión, haga clic en el icono de navegación del menú situado en la parte superior izquierda de la página para abrir el panel lateral.
. Haz clic en *Configuración*.
. Haz clic en *Gestión de usuarios*.
. Seleccione el usuario *Administrador* de la lista.
. Habilite la casilla de verificación *Cambiar contraseña*.
. Introduzca una contraseña nueva y segura en los campos *Contraseña* y *Confirmar contraseña*.
. Haz clic en *Guardar* en la parte inferior de la página.
. Repita este procedimiento para cualquier otro nodo H610S con contraseñas IPMI predeterminadas.




== Encuentra más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

