---
permalink: storage/task-element-replication-update-replication-relationship-manually.html 
sidebar: sidebar 
keywords: update, replication, relationship, manually 
summary: Es posible que deba actualizar manualmente una relación de replicación si una actualización falla debido a un error de red. 
---
= Actualizar manualmente una relación de replicación.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba actualizar manualmente una relación de replicación si una actualización falla debido a un error de red.

.Acerca de esta tarea
Debe especificar la ruta de origen del elemento en el formulario `<hostip:>/lun/<name>` , donde "`lun`" es la cadena real "`lun`" y `name` es el nombre del volumen de Element.

.Pasos
. Actualizar manualmente una relación de replicación:
+
`snapmirror update -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Para conocer la sintaxis completa del comando, consulte la página del manual.

+
[NOTE]
====
El comando falla si no existe una copia de instantánea común en el origen y el destino.  Usar `snapmirror initialize` para reiniciar la relación.

====
+
El siguiente ejemplo actualiza la relación entre el volumen de origen `0005` en la dirección IP 10.0.0.11 y el volumen de destino `volA_dst` en `svm_backup` :

+
[listing]
----
cluster_src::> snapmirror update -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

