---
permalink: storage/task_replication_create_a_target_volume_with_read_write_access.html 
sidebar: sidebar 
keywords: target volume, create, read, write access 
summary: 'El proceso de replicación involucra dos puntos finales: el volumen de origen y el volumen de destino.  Al crear el volumen de destino, este se configura automáticamente en modo de lectura/escritura para aceptar los datos durante la replicación.' 
---
= Cree un volumen de destino con acceso de lectura o escritura.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El proceso de replicación involucra dos puntos finales: el volumen de origen y el volumen de destino.  Al crear el volumen de destino, este se configura automáticamente en modo de lectura/escritura para aceptar los datos durante la replicación.

. Seleccione *Administración* > *Volúmenes*.
. Haz clic en *Crear volumen*.
. En el cuadro de diálogo Crear un nuevo volumen, introduzca el nombre del volumen.
. Ingrese el tamaño total del volumen, seleccione un tamaño de bloque para el volumen y seleccione la cuenta que debe tener acceso al volumen.
. Haz clic en *Crear volumen*.
. En la ventana Activa, haga clic en el icono Acciones del volumen.
. Haga clic en *Editar*.
. Cambie el nivel de acceso de la cuenta a Destino de replicación.
. Haz clic en *Guardar cambios*.

