---
permalink: storage/task_data_protection_back_up_volume_to_amazon_s3.html 
sidebar: sidebar 
keywords: volume backup, amazon s3 object store 
summary: Puede realizar copias de seguridad de volúmenes en almacenes de objetos externos que sean compatibles con Amazon S3. 
---
= Realizar una copia de seguridad de un volumen en un almacenamiento de objetos de Amazon S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar copias de seguridad de volúmenes en almacenes de objetos externos que sean compatibles con Amazon S3.

. Haz clic en *Administración* > *Volúmenes*.
. Haz clic en el icono Acciones del volumen que deseas respaldar.
. En el menú resultante, haga clic en *Realizar copia de seguridad en*.
. En el cuadro de diálogo *Copia de seguridad integrada*, en *Realizar copia de seguridad en*, seleccione *S3*.
. Seleccione una opción en *Formato de datos*:
+
** *Nativo*: Un formato comprimido legible únicamente por los sistemas de almacenamiento SolidFire .
** *Sin comprimir*: Un formato sin comprimir compatible con otros sistemas.


. Introduzca un nombre de host para acceder al almacén de objetos en el campo *Nombre de host*.
. Introduzca un ID de clave de acceso para la cuenta en el campo *ID de clave de acceso*.
. Introduzca la clave de acceso secreta de la cuenta en el campo *Clave de acceso secreta*.
. Introduzca el bucket de S3 en el que se almacenará la copia de seguridad en el campo *Bucket de S3*.
. Introduzca una etiqueta de identificación para añadir al prefijo en el campo *Etiqueta de identificación*.
. Haz clic en *Iniciar lectura*.

