---
permalink: storage/task_replication_pair_volumes_using_a_volume_id.html 
sidebar: sidebar 
keywords: volume pairings, volume id, replication 
summary: Puede emparejar un volumen con otro volumen en un clúster remoto si dispone de credenciales de administrador del clúster remoto. 
---
= Emparejar volúmenes utilizando un ID de volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede emparejar un volumen con otro volumen en un clúster remoto si tiene acceso de administrador de clúster a ambos clústeres en los que se van a emparejar los volúmenes. Este método utiliza el ID del volumen en el clúster remoto para iniciar una conexión.

.Lo que necesitarás
* Asegúrese de que los clústeres que contienen los volúmenes estén emparejados.
* Cree un nuevo volumen en el clúster remoto.
+

NOTE: Puede asignar un origen y un destino de replicación después del proceso de emparejamiento.  Una fuente o destino de replicación puede ser cualquiera de los volúmenes de un par de volúmenes.  Debe crear un volumen de destino que no contenga datos y tenga las características exactas del volumen de origen, como el tamaño, la configuración del tamaño de bloque para los volúmenes (ya sea 512e o 4k) y la configuración de QoS.  Si asigna un volumen existente como destino de replicación, los datos de ese volumen se sobrescribirán.  El volumen objetivo puede ser mayor o igual en tamaño que el volumen de origen, pero no puede ser menor.

* Conozca el ID del volumen de destino.


.Pasos
. Seleccione *Administración* > *Volúmenes*.
. Haz clic en el icono *Acciones* del volumen que deseas emparejar.
. Haga clic en *Emparejar*.
. En el cuadro de diálogo *Emparejar volumen*, seleccione *Iniciar emparejamiento*.
. Seleccione *Sí* para indicar que tiene acceso al clúster remoto.
. Seleccione un *Modo de replicación* de la lista:
+
** *Tiempo real (asíncrono)*: Las escrituras se confirman al cliente después de que se hayan confirmado en el clúster de origen.
** *En tiempo real (síncrono)*: Las escrituras se confirman al cliente después de que se hayan confirmado tanto en el clúster de origen como en el de destino.
** *Solo instantáneas*: Solo se replican las instantáneas creadas en el clúster de origen.  Las escrituras activas desde el volumen de origen no se replican.


. Seleccione un clúster remoto de la lista.
. Seleccione un ID de volumen remoto.
. Haga clic en *Iniciar emparejamiento*.
+
El sistema abre una pestaña del navegador web que se conecta a la interfaz de usuario Element del clúster remoto.  Es posible que se le solicite iniciar sesión en el clúster remoto con las credenciales de administrador del clúster.

. En la interfaz de usuario de Element del clúster remoto, seleccione *Completar emparejamiento*.
. Confirme los detalles en *Confirmar emparejamiento de volumen*.
. Haga clic en *Completar emparejamiento*.
+
Una vez confirmado el emparejamiento, los dos grupos inician el proceso de conexión de los volúmenes para el emparejamiento.  Durante el proceso de emparejamiento, puede ver mensajes en la columna *Estado del volumen* de la ventana *Pares de volúmenes*.  El par de pantallas de volumen `PausedMisconfigured` hasta que se asignen el origen y el destino del par de volúmenes.

+
Una vez completado correctamente el emparejamiento, se recomienda actualizar la tabla Volúmenes para eliminar la opción *Emparejar* de la lista *Acciones* del volumen emparejado.  Si no actualiza la tabla, la opción *Par* seguirá disponible para su selección.  Si vuelve a seleccionar la opción *Emparejar*, se abrirá una nueva pestaña y, dado que el volumen ya está emparejado, el sistema informará de un `StartVolumePairing Failed: xVolumeAlreadyPaired` Mensaje de error en la ventana *Emparejar volumen* de la página de la interfaz de usuario de Element.





== Encuentra más información

* xref:reference_replication_volume_pairing_messages.adoc[Mensajes de emparejamiento de volumen]
* xref:reference_replication_volume_pairing_warnings.adoc[Advertencias de emparejamiento de volumen]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[Asignar una fuente y un destino de replicación a los volúmenes emparejados.]

