---
permalink: storage/task_system_manage_cluster_ntp_configure.html 
sidebar: sidebar 
keywords: ntp, cluster, query, fqdn, dns server 
summary: 'Puede instruir a cada nodo de un clúster para que consulte a un servidor de Protocolo de Tiempo de Red (NTP) para obtener actualizaciones.  El clúster solo contacta con los servidores configurados y les solicita información NTP.' 
---
= Configure los servidores del Protocolo de Tiempo de Red (NTP) para que el clúster los consulte.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede instruir a cada nodo de un clúster para que consulte a un servidor de Protocolo de Tiempo de Red (NTP) para obtener actualizaciones.  El clúster solo contacta con los servidores configurados y les solicita información NTP.

El protocolo NTP se utiliza para sincronizar los relojes a través de una red.  La conexión a un servidor NTP interno o externo debe formar parte de la configuración inicial del clúster.

Configure NTP en el clúster para que apunte a un servidor NTP local.  Puede utilizar la dirección IP o el nombre de host FQDN.  El servidor NTP predeterminado al momento de la creación del clúster se establece en us.pool.ntp.org; sin embargo, no siempre se puede establecer una conexión con este sitio dependiendo de la ubicación física del clúster SolidFire .

El uso del FQDN depende de si la configuración DNS del nodo de almacenamiento individual está implementada y operativa.  Para ello, configure los servidores DNS en cada nodo de almacenamiento y asegúrese de que los puertos estén abiertos consultando la página de Requisitos de puertos de red.

Puedes introducir hasta cinco servidores NTP diferentes.


NOTE: Puedes utilizar direcciones IPv4 e IPv6.

.Lo que necesitarás
Para configurar este ajuste, debe tener privilegios de administrador de clúster.

.Pasos
. Configure una lista de direcciones IP y/o nombres de dominio completos (FQDN) en la configuración del servidor.
. Asegúrese de que el DNS esté configurado correctamente en los nodos.
. Haz clic en *Clúster* > *Configuración*.
. En Configuración del protocolo de tiempo de red, seleccione *No*, que utiliza la configuración NTP estándar.
. Haz clic en *Guardar cambios*.




== Encuentra más información

* link:../storage/task_system_manage_cluster_ntp_configure_to_listen_for_ntp_broadcasts.html["Configure el clúster para que escuche las transmisiones NTP."]
* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

