---
permalink: storage/task_system_manage_fips_enable_fips_140_2_for_https.html 
sidebar: sidebar 
keywords: FIPS 140-2, enable fips, federal information processing standards, ncsm 
summary: Puede utilizar el método API EnableFeature para habilitar el modo de funcionamiento FIPS 140-2 para comunicaciones HTTPS. 
---
= Habilite FIPS 140-2 para HTTPS en su clúster.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el método API EnableFeature para habilitar el modo de funcionamiento FIPS 140-2 para comunicaciones HTTPS.

Con el software NetApp Element , puede optar por habilitar el modo de funcionamiento de los Estándares Federales de Procesamiento de Información (FIPS) 140-2 en su clúster.  Habilitar este modo activa el Módulo de Seguridad Criptográfica de NetApp (NCSM) y aprovecha el cifrado certificado FIPS 140-2 Nivel 1 para todas las comunicaciones a través de HTTPS con la interfaz de usuario y la API de NetApp Element .


IMPORTANT: Una vez habilitado el modo FIPS 140-2, no se puede deshabilitar.  Cuando se habilita el modo FIPS 140-2, cada nodo del clúster se reinicia y ejecuta una autocomprobación para garantizar que el NCSM esté correctamente habilitado y funcionando en el modo certificado FIPS 140-2.  Esto provoca una interrupción tanto en las conexiones de gestión como en las de almacenamiento del clúster.  Debe planificar cuidadosamente y habilitar este modo solo si su entorno necesita el mecanismo de cifrado que ofrece.

Para obtener más información, consulte la información de la API de Element.

El siguiente es un ejemplo de la solicitud a la API para habilitar FIPS:

[listing]
----
{
  "method": "EnableFeature",
    "params": {
        "feature" : "fips"
    },
    "id": 1
}
----
Una vez habilitado este modo de funcionamiento, todas las comunicaciones HTTPS utilizan los cifrados aprobados por FIPS 140-2.



== Encuentra más información

* xref:reference_system_manage_fips_ssl_cipher_changes.adoc[cifrados SSL]
* link:../api/concept_element_api_about_the_api.html["Gestiona el almacenamiento con la API de Element"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

