---
permalink: storage/task_monitor_volume_performance.html 
sidebar: sidebar 
keywords: volume performance, view, view alerts 
summary: Puede consultar información detallada sobre el rendimiento de todos los volúmenes del clúster. Esta información se puede ordenar por ID de volumen o por cualquier otra de las columnas de rendimiento.  También puedes filtrar la información según ciertos criterios. 
---
= Rendimiento del volumen de visualización
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede consultar información detallada sobre el rendimiento de todos los volúmenes del clúster. Esta información se puede ordenar por ID de volumen o por cualquier otra de las columnas de rendimiento.  También puedes filtrar la información según ciertos criterios.

Puedes cambiar la frecuencia con la que el sistema actualiza la información de rendimiento en la página haciendo clic en la lista *Actualizar cada* y eligiendo un valor diferente.  El intervalo de actualización predeterminado es de 10 segundos si el clúster tiene menos de 1000 volúmenes; de lo contrario, el valor predeterminado es de 60 segundos.  Si selecciona el valor Nunca, la actualización automática de la página se desactiva.

Puedes volver a habilitar la actualización automática haciendo clic en *Activar actualización automática*.

. En la interfaz de usuario de Element, seleccione *Informes* > *Rendimiento de volumen*.
. En la lista de volúmenes, haga clic en el icono Acciones de un volumen.
. Haga clic en *Ver detalles*.
+
En la parte inferior de la página se muestra una bandeja con información general sobre el volumen.

. Para ver información más detallada sobre el volumen, haga clic en *Ver más detalles*.
+
El sistema muestra información detallada, así como gráficos de rendimiento del volumen.





== Encuentra más información

xref:reference_monitor_volume_performance_details.adoc[Detalles del rendimiento del volumen]
