---
permalink: setup/task_setup_fc_create_a_new_cluster_with_fibre_channel_nodes.html 
sidebar: sidebar 
keywords:  
summary: Puede crear un nuevo clúster después de haber configurado los nodos Fibre Channel individuales. Cuando se crea un clúster, también se crea automáticamente una cuenta de usuario de administrador de clúster.  El administrador del clúster tiene permiso para gestionar todos los atributos del clúster y puede crear otras cuentas de administrador del clúster. 
---
= Cree un nuevo clúster con nodos Fibre Channel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear un nuevo clúster después de haber configurado los nodos Fibre Channel individuales. Cuando se crea un clúster, también se crea automáticamente una cuenta de usuario de administrador de clúster.  El administrador del clúster tiene permiso para gestionar todos los atributos del clúster y puede crear otras cuentas de administrador del clúster.

Durante la configuración de un nuevo nodo, se asignan direcciones IP de gestión (MIP) de 1G o 10G a cada nodo.  Debe utilizar una de las direcciones IP de nodo creadas durante la configuración para abrir la página Crear un nuevo clúster.  La dirección IP que utilice dependerá de la red que haya elegido para la gestión del clúster.

.Lo que necesitarás
Has configurado los nodos Fibre Channel individuales.

.Pasos
. En una ventana del navegador, introduzca una dirección MIP del nodo.
. En Crear un nuevo clúster, ingrese la siguiente información:
+
** VIP de gestión: IP virtual enrutable en la red 1GbE o 10GbE para tareas de gestión de red.
** VIP iSCSI (almacenamiento): IP virtual en la red 10GbE para almacenamiento y descubrimiento iSCSI.
+

NOTE: No se puede cambiar la SVIP después de crear el clúster.

** Nombre de usuario: El nombre de usuario del administrador principal del clúster para el acceso autenticado al clúster.  Debe guardar el nombre de usuario para futuras consultas.
+

NOTE: Para el nombre de usuario puedes utilizar letras mayúsculas y minúsculas, caracteres especiales y números.

** Contraseña: Contraseña para el acceso autenticado al clúster.  Debe guardar el nombre de usuario para futuras consultas.  La protección de datos bidireccional está habilitada por defecto.  No puedes cambiar esta configuración.


. Lea el Acuerdo de Licencia de Usuario Final y haga clic en *Acepto*.
. *Opcional*: En la lista de nodos, asegúrese de que no estén seleccionadas las casillas de verificación de los nodos que no deben incluirse en el clúster.
. Haz clic en *Crear clúster*.
+
El sistema podría tardar varios minutos en crear el clúster, dependiendo del número de nodos que lo componen.  En una red correctamente configurada, un pequeño clúster de cinco nodos debería tardar menos de un minuto.  Una vez creado el clúster, la ventana Crear un nuevo clúster se redirige a la dirección URL de MVIP del clúster y muestra la interfaz de usuario web.





== Encuentra más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

