---
permalink: setup/task_post_deploy_access_the_element_software_user_interface.html 
sidebar: sidebar 
keywords:  
summary: 'Puede acceder a la interfaz de usuario de Element utilizando la dirección IP virtual de administración (MVIP) del nodo principal del clúster.' 
---
= Acceda a la interfaz de usuario del software Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede acceder a la interfaz de usuario de Element utilizando la dirección IP virtual de administración (MVIP) del nodo principal del clúster.

Debes asegurarte de que los bloqueadores de ventanas emergentes y la configuración de NoScript estén desactivados en tu navegador.

Puede acceder a la interfaz de usuario utilizando direcciones IPv4 o IPv6, según la configuración realizada durante la creación del clúster.

.Pasos
. Elija una de las siguientes opciones:
+
** IPv6: Introducir `https://[IPv6_MVIP_address]` . Por ejemplo:
+
[listing]
----
https://[fd20:8b1e:b256:45a::1234]/
----
** IPv4: Introducir `https://[IPv4 MVIP address]` . Por ejemplo:
+
[listing]
----
https://10.123.456.789/
----


. Para DNS, introduzca el nombre del host.
. Ignore cualquier mensaje de certificado de autenticación.




== Para más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

