---
permalink: api/concept_element_api_virtual_network_naming_conventions.html 
sidebar: sidebar 
keywords: storage,system,naming,convention,virtual,network 
summary: Los sistemas de almacenamiento NetApp Element utilizan números que aumentan de forma monótona como identificadores únicos para todos los objetos del sistema. 
---
= Convenciones de nomenclatura de redes virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas de almacenamiento NetApp Element utilizan números que aumentan de forma monótona como identificadores únicos para todos los objetos del sistema.

Cuando se crea un nuevo volumen, el nuevo ID de volumen es un incremento de exactamente 1.  Esta convención también se aplica a las redes virtuales en clústeres de almacenamiento que ejecutan el software Element.  La primera red virtual que cree en un clúster de Element tiene un VirtualNetworkID de 1.  Este ID no es lo mismo que un número de etiqueta VLAN.

Puedes usar VirtualNetworkID y VirtualNetworkTag (etiqueta VLAN) indistintamente donde se indique en los métodos de la API.



== Encuentra más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de los productos NetApp SolidFire y Element"^]

