---
permalink: api/concept_element_api_asynchronous_methods.html 
sidebar: sidebar 
keywords: async,asynchronous,methods,API 
summary: Algunos métodos de la API son asíncronos, lo que significa que la operación que realizan podría no estar completa cuando el método devuelve un valor.  Los métodos asíncronos devuelven un identificador que se puede consultar para ver el estado de la operación; la información de estado de algunas operaciones puede incluir un porcentaje de finalización. 
---
= Métodos asíncronos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Algunos métodos de la API son asíncronos, lo que significa que la operación que realizan podría no estar completa cuando el método devuelve un valor.  Los métodos asíncronos devuelven un identificador que se puede consultar para ver el estado de la operación; la información de estado de algunas operaciones puede incluir un porcentaje de finalización.

Cuando se consulta una operación asíncrona, su resultado puede ser de uno de los siguientes tipos:

* `DriveAdd`El sistema está añadiendo una unidad al clúster.
* `BulkVolume`El sistema está realizando una operación de copia entre volúmenes, como una copia de seguridad o una restauración.
* `Clone`El sistema está clonando un volumen.
* `DriveRemoval`El sistema está copiando datos de una unidad como preparación para eliminarla del clúster.
* `RtfiPendingNode`El sistema está instalando software compatible en un nodo antes de agregarlo al clúster.


Tenga en cuenta los siguientes puntos al utilizar métodos asíncronos o al obtener el estado de una operación asíncrona en ejecución:

* Los métodos asíncronos se indican en la documentación de cada método.
* Los métodos asíncronos devuelven un "`asyncHandle`", que es un identificador conocido por el método API que lo emite.  Puede utilizar el identificador para consultar el estado o el resultado de la operación asíncrona.
* Puedes obtener el resultado de métodos asíncronos individuales con el método GetAsyncResult.  Cuando se utiliza GetAsyncResult para consultar una operación completada, el sistema devuelve el resultado y lo elimina automáticamente del sistema.  Cuando se utiliza GetAsyncResult para consultar una operación incompleta, el sistema devuelve el resultado pero no lo elimina.
* Puede obtener el estado y los resultados de todos los métodos asíncronos en ejecución o completados mediante el método ListAsyncResults.  En este caso, el sistema no elimina los resultados de las operaciones completadas.




== Encuentra más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de los productos NetApp SolidFire y Element"^]

