---
permalink: api/concept_element_api_ldap_api_methods.html 
sidebar: sidebar 
keywords: ldap,api,methods 
summary: 'Puede utilizar el Protocolo ligero de acceso a directorios (LDAP) para autenticar el acceso al almacenamiento de Element.  Los métodos de la API LDAP descritos en esta sección le permiten configurar el acceso LDAP al clúster de almacenamiento.' 
---
= Métodos de la API LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el Protocolo Ligero de Acceso a Directorios (LDAP) para autenticar el acceso al almacenamiento de Element.  Los métodos de la API LDAP descritos en esta sección le permiten configurar el acceso LDAP al clúster de almacenamiento.

* xref:reference_element_api_addldapclusteradmin.adoc[Agregar administrador de clúster Ldap]
* xref:reference_element_api_enableldapauthentication.adoc[Habilitar autenticación LDAP]
* xref:reference_element_api_disableldapauthentication.adoc[Deshabilitar la autenticación LDAP]
* xref:reference_element_api_getldapconfiguration.adoc[Obtener configuración LDAP]
* xref:reference_element_api_testldapauthentication.adoc[Prueba de autenticación LDAP]




== Encuentra más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de los productos NetApp SolidFire y Element"^]

