---
permalink: api/reference_element_api_listactiveauthsessions.html 
sidebar: sidebar 
keywords: active,sessions,authentication session,list 
summary: Puedes utilizar el método ListActiveAuthSessions para listar todas las sesiones autenticadas activas.  Solo los usuarios con derechos de acceso administrativo pueden llamar a este método. 
---
= ListarSesionesDeAutenticaciónActivas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListActiveAuthSessions` Método para listar todas las sesiones autenticadas activas.  Solo los usuarios con derechos de acceso administrativo pueden llamar a este método.



== Parámetros

Este método no tiene parámetros de entrada.



== Valores de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
sesiones
 a| 
Información de sesión para las sesiones de autenticación.
 a| 
link:reference_element_api_authsessioninfo.html["información de sesión de autenticación"]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "ListActiveAuthSessions"
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nueva versión

12,0
