---
permalink: api/reference_element_api_listdrivestats.html 
sidebar: sidebar 
keywords: cluster,list,listing,drive,drives,stats,statistics,listdrivestats 
summary: Puede utilizar el método ListDriveStats para enumerar las mediciones de actividad de alto nivel para varias unidades en el clúster.  Por defecto, este método devuelve estadísticas para todas las unidades del clúster, y estas mediciones son acumulativas desde la adición de la unidad al clúster.  Algunos valores que devuelve este método son específicos de las unidades de bloques, y otros son específicos de las unidades de metadatos. 
---
= ListDriveStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListDriveStats` Método para listar las mediciones de actividad de alto nivel para múltiples unidades en el clúster.  Por defecto, este método devuelve estadísticas para todas las unidades del clúster, y estas mediciones son acumulativas desde la adición de la unidad al clúster.  Algunos valores que devuelve este método son específicos de las unidades de bloques, y otros son específicos de las unidades de metadatos.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
unidades
 a| 
Lista de identificadores de unidad (driveID) para los que se devolverán las estadísticas de la unidad.  Si omite este parámetro, se devolverán las mediciones de todas las unidades.
 a| 
matriz de enteros
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
Estadísticas de la unidad
 a| 
Lista de información de actividad de cada unidad.
 a| 
xref:reference_element_api_drivestats.adoc[Estadísticas de la unidad]formación



 a| 
errores
 a| 
Esta lista contiene el ID de la unidad y el mensaje de error asociado.  Siempre está presente y vacío si no hay errores.
 a| 
matriz de objetos JSON

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "method": "ListDriveStats",
  "params": {
    "drives":[22,23]
  }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": [
      {
        "driveID": 22,
        "failedDieCount": 0,
        "lifeRemainingPercent": 84,
        "lifetimeReadBytes": 30171004403712,
        "lifetimeWriteBytes": 103464755527680,
        "powerOnHours": 17736,
        "readBytes": 14656542,
         "readOps": 3624,
        "reallocatedSectors": 0,
        "reserveCapacityPercent": 100,
        "timestamp": "2016-03-01T00:19:24.782735Z",
        "totalCapacity": 300069052416,
        "usedCapacity": 1783735635,
        "usedMemory": 879165440,
        "writeBytes": 2462169894,
        "writeOps": 608802
      }
    ],
    "errors": [
      {
        "driveID": 23,
        "exception": {
          "message": "xStatCheckpointDoesNotExist",
          "name": "xStatCheckpointDoesNotExist"
        }
      }
    ]
  }
}
----


== Nueva versión

9,6



== Encuentra más información

xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
