---
permalink: api/reference_element_api_listvolumestatsbyaccount.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,account,listvolumestatsbyaccount,activity 
summary: Puede utilizar el método ListVolumeStatsByAccount para enumerar las mediciones de actividad de volumen de alto nivel para cada cuenta.  Los valores se suman a partir de todos los volúmenes que posee la cuenta. 
---
= ListVolumeStatsByAccount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListVolumeStatsByAccount` Método para listar las mediciones de actividad de alto nivel para cada cuenta.  Los valores se suman a partir de todos los volúmenes que posee la cuenta.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
incluir volúmenes virtuales
 a| 
Los volúmenes virtuales se incluyen en la respuesta de forma predeterminada.  Para excluir volúmenes virtuales, establezca el valor en falso.
 a| 
booleano
 a| 
verdadero
 a| 
No



 a| 
cuentas
 a| 
Una lista de identificadores de cuenta para los que se devolverán las estadísticas de volumen.  Si se omite, se devuelven las estadísticas de todas las cuentas.
 a| 
matriz de enteros
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
estadísticas de volumen
 a| 
Lista de información de actividad de volumen para cada cuenta.*Nota:* El miembro volumeID es 0 para cada entrada, ya que los valores representan la suma de todos los volúmenes que posee la cuenta.
 a| 
xref:reference_element_api_volumestats.adoc[estadísticas de volumen]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
"method": "ListVolumeStatsByAccount",
  "params": {"accounts": [3]},
  "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 3,
        "nonZeroBlocks": 155040175,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T20:42:26.231661Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [],
        "volumeID": 0,
        "volumeSize": 1127428915200,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 120211025
      }
    ]
  }
}
----


== Nueva versión

9,6
