---
permalink: api/reference_element_api_deleteinitiators.html 
sidebar: sidebar 
keywords: delete,deleting,initiator,initiators,DeleteInitiators 
summary: 'Puede utilizar DeleteInitiators para eliminar uno o más iniciadores del sistema (y de cualquier volumen o grupo de acceso a volúmenes asociado).' 
---
= EliminarIniciadores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar `DeleteInitiators` eliminar uno o más iniciadores del sistema (y de cualquier volumen o grupo de acceso a volúmenes asociado).

Si `DeleteInitiators` Si no se puede eliminar uno de los iniciadores proporcionados en el parámetro, el sistema devuelve un error y no elimina ningún iniciador (no es posible la finalización parcial).



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
iniciadores
 a| 
Una matriz de identificadores de iniciadores a eliminar.
 a| 
matriz de enteros
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método no devuelve ningún valor.



== Error

Este método puede devolver el siguiente error:

|===


| Nombre | Descripción 


 a| 
xIniciadorNoExiste
 a| 
Se devuelve si el nombre del iniciador que ha elegido no existe.

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "id": 5101,
  "method": "DeleteInitiators",
  "params": {
    "initiators": [
      145,
      147
    ]
  }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 5101,
  "result": {}
}
----


== Nueva versión

9,6
