---
permalink: api/reference_element_api_getstoragecontainerefficiency.html 
sidebar: sidebar 
keywords: volume,virtual,container,volumes,get,getting,efficiency,vvol,GetStorageContainerEfficiency 
summary: Puede utilizar el método GetStorageContainerEfficiency para recuperar información sobre la eficiencia de un contenedor de almacenamiento de volumen virtual. 
---
= Obtener la eficiencia del contenedor de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetStorageContainerEfficiency` Método para recuperar información sobre la eficiencia de un contenedor de almacenamiento de volumen virtual.



== Parámetros

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID del contenedor de almacenamiento
 a| 
El identificador del contenedor de almacenamiento del que se recuperará la información de eficiencia.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
compresión
 a| 
Cantidad de espacio ahorrado mediante la compresión de datos para todos los volúmenes virtuales en el contenedor de almacenamiento.  Se expresa como una relación donde un valor de 1 significa que los datos se han almacenado sin compresión.
 a| 
flotar



 a| 
deduplicación
 a| 
La cantidad de espacio ahorrado al no duplicar los datos de todos los volúmenes virtuales en el contenedor de almacenamiento.  Expresado como una proporción.
 a| 
flotar



 a| 
volúmenes faltantes
 a| 
Los volúmenes virtuales que no se pudieron consultar para obtener datos de eficiencia.  La falta de volúmenes puede deberse a que el ciclo de recolección de basura (GC) tenga menos de una hora de antigüedad, a una pérdida temporal de conectividad de red o a servicios reiniciados desde el ciclo de GC.
 a| 
matriz de enteros



 a| 
aprovisionamiento ligero
 a| 
La proporción de espacio utilizado con respecto a la cantidad de espacio asignado para almacenar datos.  Expresado como una proporción.
 a| 
flotar



 a| 
marca de tiempo
 a| 
La última vez que se recopilaron datos de eficiencia después de GC.
 a| 
cadena de datos ISO 8601

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "GetStorageContainerEfficiency",
  "params": {
    "storageContainerID" : "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1"
  },
  "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "compression": 1,
    "deduplication": 1,
    "missingVolumes": [],
    "thinProvisioning": 1,
    "timestamp": "2016-04-12T15:39:49Z"
  }
}
----


== Nueva versión

9,6
