---
permalink: api/reference_element_api_listaccounts.html 
sidebar: sidebar 
keywords: account,accounts,list,listing,all,listaccounts 
summary: Puede utilizar ListAccounts para obtener la lista completa de cuentas de inquilinos de almacenamiento, con soporte de paginación opcional.  Las cuentas de elementos permiten el acceso a los volúmenes. 
---
= Lista de cuentas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar `ListAccounts` Para obtener la lista completa de cuentas de inquilinos de almacenamiento, con soporte de paginación opcional.  Las cuentas de elementos permiten el acceso a los volúmenes.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
incluir contenedores de almacenamiento
 a| 
Los contenedores de almacenamiento de volúmenes virtuales se incluyen en la respuesta de forma predeterminada.  Para excluir los contenedores de almacenamiento, establezca el valor en falso.
 a| 
booleano
 a| 
verdadero
 a| 
No



 a| 
ID de cuenta de inicio
 a| 
ID de cuenta inicial a devolver.  Si no existe ninguna cuenta con este ID de cuenta, se utiliza la siguiente cuenta en orden de ID de cuenta como inicio de la lista.  Para navegar por la lista, pase el accountID de la última cuenta en la respuesta anterior + 1.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
límite
 a| 
Número máximo de objetos de cuenta a devolver.
 a| 
entero
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
cuentas
 a| 
La lista de cuentas.
 a| 
xref:reference_element_api_account.adoc[cuenta]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ListAccounts",
   "params": {
     "startAccountID"  : 0,
     "limit" : 1000
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "result" : {
    "accounts": [
	{
        "attributes": {},
        "username": "jamesw",
        "targetSecret": "168#5A757ru268)",
        "volumes": [],
        "enableChap": false,
        "status": "active",
        "accountID": 16,
        "storageContainerID": "abcdef01-1234-5678-90ab-cdef01234567",
        "initiatorSecret": "168#5A757ru268)"
    },
    {
        "attributes": {},
        "username": "jimmyd",
        "targetSecret": "targetsecret",
        "volumes": [],
        "enableChap": true,
        "status": "active",
        "accountID": 5,
        "storageContainerID": "abcdef01-1234-5678-90ab-cdef01234567",
        "initiatorSecret": "initiatorsecret"
    }
  ]
}
}
----


== Nueva versión

9,6
