---
permalink: api/reference_element_api_snapmirrornetworkinterface.html 
sidebar: sidebar 
keywords: object,objects,snapMirrorNetworkInterface 
summary: 'El objeto snapMirrorNetworkInterface contiene información sobre las interfaces lógicas intercluster \(LIFs\).' 
---
= snapMirrorInterfazDeRed
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El objeto snapMirrorNetworkInterface contiene información sobre las interfaces lógicas (LIF) entre clústeres.



== miembros del objeto

Este objeto contiene los siguientes miembros:

|===
| Nombre | Descripción | Tipo 


 a| 
Estado administrativo
 a| 
Si la interfaz lógica (LIF) está habilitada o deshabilitada administrativamente. Valores posibles:

* arriba
* abajo

 a| 
cadena



 a| 
ID de punto final de SnapMirror
 a| 
El identificador del sistema ONTAP de destino.
 a| 
entero



 a| 
nombre de interfaz
 a| 
El nombre LIF.
 a| 
cadena



 a| 
dirección de red
 a| 
La dirección IP del LIF.
 a| 
cadena



 a| 
máscara de red
 a| 
La máscara de red del LIF.
 a| 
cadena



 a| 
rol de interfaz
 a| 
El papel del LIF. Valores posibles:

* indefinido
* clúster
* data
* gestión de nodos
* intercluster
* gestión de clústeres

 a| 
cadena



 a| 
Estado operativo
 a| 
El estado operativo del LIF (si ha establecido o no una conexión exitosa).  Este estado puede diferir del estado administrativo si existe un problema de red que impide el funcionamiento de la interfaz. Valores posibles:

* arriba
* abajo

 a| 
cadena



 a| 
vserverName
 a| 
El nombre del servidor virtual.
 a| 
cadena

|===