---
permalink: api/reference_element_api_snapmirrorluninfo.html 
sidebar: sidebar 
keywords: object,objects,snapMirrorLunInfo 
summary: El objeto snapMirrorLunInfo contiene información sobre el objeto LUN de ONTAP . 
---
= snapMirrorLunInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El objeto snapMirrorLunInfo contiene información sobre el objeto LUN de ONTAP .



== miembros del objeto

Este objeto contiene los siguientes miembros:

|===
| Nombre | Descripción | Tipo 


 a| 
ID de punto final de SnapMirror
 a| 
El identificador del sistema ONTAP de destino.
 a| 
entero



 a| 
marca de tiempo de creación
 a| 
El tiempo de creación del LUN.
 a| 
cadena de fecha ISO 8601



 a| 
nombre de lun
 a| 
El nombre del LUN.
 a| 
cadena



 a| 
camino
 a| 
La trayectoria del LUN.
 a| 
cadena



 a| 
tamaño
 a| 
Tamaño de la LUN en bytes.
 a| 
entero



 a| 
tamañoUsado
 a| 
Número de bytes utilizados por la LUN.
 a| 
entero



 a| 
estado
 a| 
Estado de acceso actual de la LUN. Valores posibles:

* en línea
* desconectado
* error_lun_extranjero
* nvfail
* error_espacio

 a| 
cadena



 a| 
volume
 a| 
El nombre del volumen que contiene el LUN.
 a| 
cadena



 a| 
vserver
 a| 
El servidor virtual que contiene la LUN.
 a| 
cadena

|===