---
permalink: api/reference_element_api_createcluster.html 
sidebar: sidebar 
keywords: CreateCluster,cluster,create,creating,initialize,initializing 
summary: 'Puede utilizar el método CreateCluster para inicializar el nodo en un clúster que tenga la propiedad de las direcciones "mvip" y "svip".  Cada nuevo clúster se inicializa utilizando la IP de gestión (MIP) del primer nodo del clúster.  Este método también agrega automáticamente todos los nodos que se están configurando al clúster.  Solo necesitas usar este método una vez cada vez que se inicialice un nuevo clúster.' 
---
= CrearClúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `CreateCluster` Método para inicializar el nodo en un clúster que tiene la propiedad de las direcciones "mvip" y "svip".  Cada nuevo clúster se inicializa utilizando la IP de gestión (MIP) del primer nodo del clúster.  Este método también agrega automáticamente todos los nodos que se están configurando al clúster.  Solo necesitas usar este método una vez cada vez que se inicialice un nuevo clúster.


NOTE: Después de iniciar sesión en el nodo maestro del clúster y ejecutar elxref:reference_element_api_getbootstrapconfig.adoc[Obtener configuración de Bootstrap] Para obtener las direcciones IP del resto de los nodos que desea incluir en el clúster, puede ejecutar el método CreateCluster en el nodo maestro del clúster.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
aceptar el EULA
 a| 
Indique su aceptación del Acuerdo de Licencia de Usuario Final al crear este clúster.  Para aceptar el CLUF, configure este parámetro en verdadero.
 a| 
booleano
 a| 
Ninguno
 a| 
Sí



 a| 
atributos
 a| 
Lista de pares nombre-valor en formato de objeto JSON.
 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No



 a| 
habilitar el cifrado de software en reposo
 a| 
Habilite este parámetro para utilizar el cifrado basado en software en reposo.  Valor predeterminado: falso en todos los clústeres.  Una vez habilitada la encriptación de software en reposo, no se puede deshabilitar en el clúster.
 a| 
booleano
 a| 
verdadero
 a| 
No



 a| 
MVIP
 a| 
Dirección IP flotante (virtual) para el clúster en la red de administración.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
nodos
 a| 
Direcciones CIP/SIP del conjunto inicial de nodos que componen el clúster.  La IP de este nodo debe estar en la lista.
 a| 
matriz de cadenas
 a| 
Ninguno
 a| 
Sí



 a| 
número de orden
 a| 
Número de pedido de venta alfanumérico.  Requerido en plataformas basadas en software.
 a| 
cadena
 a| 
Ninguno
 a| 
No (plataformas basadas en hardware)

Sí (plataformas basadas en software)



 a| 
contraseña
 a| 
Contraseña inicial para la cuenta de administrador del clúster.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
número de serie
 a| 
Número de serie alfanumérico de nueve dígitos.  Puede ser necesario en plataformas basadas en software.
 a| 
cadena
 a| 
Ninguno
 a| 
No (plataformas basadas en hardware)

Sí (plataformas basadas en software)



 a| 
svip
 a| 
Dirección IP flotante (virtual) para el clúster en la red de almacenamiento (iSCSI).
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
nombre de usuario
 a| 
Nombre de usuario del administrador del clúster.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "CreateCluster",
  "params": {
    "acceptEula": true,
    "mvip": "10.0.3.1",
    "svip": "10.0.4.1",
    "username": "Admin1",
    "password": "9R7ka4rEPa2uREtE",
    "attributes": {
      "clusteraccountnumber": "axdf323456"
    },
    "nodes": [
      "10.0.2.1",
      "10.0.2.2",
      "10.0.2.3",
      "10.0.2.4"
    ]
  },
  "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
"id" : 1,
"result" : {}
}
----


== Nueva versión

9,6

[discrete]
== Encuentra más información

* link:reference_element_api_getbootstrapconfig.html["Obtener configuración de Bootstrap"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de los productos NetApp SolidFire y Element"^]

