---
permalink: api/reference_element_api_deleteauthsessionsbyusername.html 
sidebar: sidebar 
keywords: auth sessions,username,delete,authentication sessions 
summary: Puede utilizar el método DeleteAuthSessionsByUsername para eliminar todas las sesiones de autenticación de un usuario o usuarios determinados.  Un usuario que no pertenezca al grupo de acceso ClusterAdmins/Administrator solo puede eliminar sus propias sesiones.  Un usuario con privilegios de ClusterAdmins/Administrator puede eliminar las sesiones pertenecientes a cualquier usuario.  Para ver la lista de sesiones que podrían eliminarse, utilice ListAuthSessionsByUsername con los mismos parámetros.  Para ver una lista de sesiones para su posible eliminación, utilice el método ListAuthSessionsByUsername con el mismo parámetro. 
---
= EliminarSesionesDeAutenticaciónPorNombreDeUsuario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `DeleteAuthSessionsByUsername` Método para eliminar todas las sesiones de autenticación de un usuario o usuarios determinados.  Un usuario que no pertenezca al grupo de acceso ClusterAdmins/Administrator solo puede eliminar sus propias sesiones.  Un usuario con privilegios de ClusterAdmins/Administrator puede eliminar las sesiones pertenecientes a cualquier usuario.  Para ver la lista de sesiones que podrían eliminarse, utilice `ListAuthSessionsByUsername` con los mismos parámetros.  Para ver una lista de sesiones para su posible eliminación, utilice la `ListAuthSessionsByUsername` método con el mismo parámetro.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
método de autenticación
 a| 
Método de autenticación de las sesiones de usuario que se van a eliminar.  Solo un usuario perteneciente al grupo de acceso ClusterAdmins/Administrator puede proporcionar este parámetro.  Los valores posibles son:

* *authMethod=Cluster* especifica el nombre de usuario ClusterAdmin.
* *authMethod=Ldap* especifica el DN LDAP del usuario.
* *authMethod=Idp* especifica el UUID o el NameID del IdP del usuario.  Si el IdP no está configurado para devolver ninguna de las dos opciones, esto especifica un UUID aleatorio emitido cuando se creó la sesión.

 a| 
método de autenticación
 a| 
Ninguno
 a| 
No



 a| 
nombre de usuario
 a| 
Identificador único del usuario.
 a| 
cadena
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
sesiones
 a| 
Información de sesión para las sesiones de autenticación eliminadas.
 a| 
link:reference_element_api_authsessioninfo.html["información de sesión de autenticación"]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "DeleteAuthSessionsByUsername",
  "params": {
    "authMethod": "Cluster",
    "username": "admin"
  }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nueva versión

12,0
