---
permalink: api/reference_element_api_updateidpconfiguration.html 
sidebar: sidebar 
keywords: IdP,idp,configuration,update 
summary: Puede utilizar el método UpdateIdpConfiguration para actualizar una configuración existente con un IdP de terceros para el clúster. 
---
= Actualizar configuración de IDp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `UpdateIdpConfiguration` Método para actualizar una configuración existente con un IdP de terceros para el clúster.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
generarNuevoCertificado
 a| 
Cuando se especifica como verdadero, se genera una nueva clave y certificado SAML que reemplaza al par existente.  Nota: Reemplazar el certificado existente interrumpirá la confianza establecida entre el clúster y el IdP hasta que se vuelvan a cargar los metadatos del proveedor de servicios del clúster en el IdP.  Si no se proporcionan o se establecen en falso, el certificado y la clave SAML permanecen sin cambios.
 a| 
booleano
 a| 
Ninguno
 a| 
No



 a| 
idpConfigurationID
 a| 
UUID para la configuración del IdP de terceros.
 a| 
UUID
 a| 
Ninguno
 a| 
No



 a| 
idpMetadata
 a| 
Metadatos del IdP para detalles de configuración e integración para el inicio de sesión único SAML 2.0.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
idpName
 a| 
Nombre utilizado para identificar y recuperar un proveedor de identidad (IdP) para el inicio de sesión único (SSO) SAML 2.0.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
nuevoIdpName
 a| 
Si se especifica, este nombre reemplaza al nombre anterior del IdP.
 a| 
cadena
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
idpConfigInfo
 a| 
Información relativa a la configuración del IdP de terceros.
 a| 
link:reference_element_api_idpconfiginfo.html["idpConfigInfo"]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
"method": "UpdateIdpConfiguration",
"params": {
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "generateNewCertificate": true
    }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
    "result": {
        "idpConfigInfo": {
        "enabled": true,
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n
        <EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"\r\n
        xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"\r\n
        xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"\r\n
        xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n
        ...</Organization>\r\n
        </EntityDescriptor>",
        "idpName": "https://privider.name.url.com",
        "serviceProviderCertificate": "-----BEGIN CERTIFICATE-----\n
        MI...BHi\n
        -----END CERTIFICATE-----\n",
        "spMetadataUrl": "https://10.193.100.100/auth/ui/saml2"
        }
    }
}
----


== Nueva versión

12,0
