---
permalink: api/reference_element_api_disableencryptionatrest.html 
sidebar: sidebar 
keywords: element, api, encryption, disable, disabling, at rest, rest, DisableEncryptionAtRest 
summary: Puede utilizar el método DisableEncryptionAtRest para eliminar el cifrado que se aplicó previamente al clúster mediante el método EnableEncryptionAtRest.  Este método de desactivación es asíncrono y devuelve una respuesta antes de que se desactive el cifrado.  Puede utilizar el método GetClusterInfo para consultar el sistema y ver cuándo ha finalizado el proceso. 
---
= Deshabilitar el cifrado en reposo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `DisableEncryptionAtRest` método para eliminar el cifrado que se aplicó previamente al clúster utilizando el `EnableEncryptionAtRest` método.  Este método de desactivación es asíncrono y devuelve una respuesta antes de que se desactive el cifrado.  Puedes usar el `GetClusterInfo` Método para consultar al sistema y comprobar cuándo ha finalizado el proceso.


TIP: Para ver el estado actual del cifrado en reposo y/o del cifrado de software en reposo en el clúster, utilice la siguiente información:link:../api/reference_element_api_getclusterinfo.html["método para obtener información del clúster"] . Puedes usar el `GetSoftwareEncryptionAtRestInfo` link:../api/reference_element_api_getsoftwareencryptionatrestinfo.html["Método para obtener información sobre el clúster que utiliza para cifrar los datos en reposo."].


NOTE: No puede utilizar este método para deshabilitar el cifrado de software en reposo.  Para deshabilitar el cifrado de software en reposo, necesitalink:reference_element_api_createcluster.html["crear un nuevo clúster"] con el cifrado de software en reposo desactivado.



== Parámetros

Este método no tiene parámetros de entrada.



== Valores de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "DisableEncryptionAtRest",
   "params": {},
   "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id" : 1,
  "result" : {}
}
----


== Nueva versión

9,6

[discrete]
== Encuentra más información

* link:../api/reference_element_api_getclusterinfo.html["Obtener información del clúster"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de los productos NetApp SolidFire y Element"^]

