---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: Puede utilizar el método StartVolumePairing para crear una clave codificada a partir de un volumen que se utilice para emparejarlo con otro volumen.  La clave que crea este método se utiliza en el método CompleteVolumePairing para establecer un emparejamiento de volúmenes. 
---
= Emparejamiento de volumen inicial
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `StartVolumePairing` Método para crear una clave codificada a partir de un volumen que se utiliza para emparejarlo con otro volumen.  La clave que crea este método se utiliza en el `CompleteVolumePairing` método para establecer un emparejamiento de volúmenes.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
modo
 a| 
El modo del volumen en el que se inicia el proceso de emparejamiento.  Este modo solo se puede configurar si el volumen es el volumen de origen. Valores posibles:

* `Async`Los trabajos se confirman cuando se completan localmente.  El clúster no espera a que las escrituras se repliquen en el clúster de destino.  (Valor predeterminado si no se especifica ningún parámetro de modo).
* `Sync`La fuente confirma la escritura cuando los datos se almacenan localmente y en el clúster remoto.
* `SnapshotsOnly`Solo se replican las instantáneas creadas en el clúster de origen.  Las escrituras activas desde el volumen de origen no se replican.

 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
ID de volumen
 a| 
El identificador del volumen en el que se iniciará el proceso de emparejamiento.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
clave de emparejamiento de volumen
 a| 
Una cadena de caracteres que utiliza elxref:reference_element_api_completevolumepairing.adoc[Emparejamiento de volumen completo] Método API.
 a| 
cadena

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== Nueva versión

9,6



== Encuentra más información

xref:reference_element_api_completevolumepairing.adoc[Emparejamiento de volumen completo]
