---
permalink: api/reference_element_api_getpendingoperation.html 
sidebar: sidebar 
keywords: get,getting,pending,operation,getpendingoperation 
summary: Puede utilizar el método GetPendingOperation para detectar una operación en un nodo que actualmente está en curso.  Este método también puede utilizarse para informar cuando una operación ha finalizado. 
---
= ObtenerOperaciónPendiente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetPendingOperation` Método para detectar una operación en un nodo que se encuentra actualmente en curso.  Este método también puede utilizarse para informar cuando una operación ha finalizado.



== Parámetros

Este método no tiene parámetros de entrada.



== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
pendiente
 a| 
Valores posibles:

* Es cierto: la operación aún está en curso.
* FALSO:
+
La operación ya no está en curso.


 a| 
booleano



 a| 
operación
 a| 
Nombre de la operación que está en curso o que ha finalizado.
 a| 
cadena

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "GetPendingOperation",
   "params": {},
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id" : 1,
   "result" : {
      "pendingOperation" : {
         "pending" : "true",
         "operation" : "TestDrivesInternal",
      }
   }
}
----


== Nueva versión

9,6
