---
permalink: api/reference_element_api_getremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,hosts,host,get,getting,getremotelogginghosts 
summary: Puede utilizar el método GetRemoteLoggingHosts para obtener la lista actual de servidores de registro. 
---
= Obtener hosts de registro remoto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetRemoteLoggingHosts` Método para obtener la lista actual de servidores de registro.



== Parámetros

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
hosts remotos
 a| 
Lista de direcciones IP e información de puertos de los hosts configurados para recibir información de registro reenviada.
 a| 
xref:reference_element_api_loggingserver.adoc[servidor de registro]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "id": 3386609,
   "method": "GetRemoteLoggingHosts",
   "params": {}
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id": 3386609,
   "result": {
      "remoteHosts": [
         {
           "host": "172.16.1.20",
           "port": 10514
         },
         {
           "host": "172.16.1.25"
         }
      ]
   }
}
----


== Nueva versión

9,6



== Encuentra más información

xref:reference_element_api_setremotelogginghosts.adoc[Configurar hosts de registro remoto]
