---
permalink: api/reference_element_api_setclusterstructure.html 
sidebar: sidebar 
keywords: storage,cluster,configuration,info,restore,set,setting,setclusterstructure 
summary: Puede utilizar el método SetClusterStructure para restaurar la información de configuración del clúster de almacenamiento desde una copia de seguridad.  Cuando llamas al método, pasas el objeto clusterStructure que contiene la información de configuración que deseas restaurar como parámetro params. 
---
= Establecer estructura de clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `SetClusterStructure` Método para restaurar la información de configuración del clúster de almacenamiento a partir de una copia de seguridad.  Cuando llamas al método, pasas el objeto clusterStructure que contiene la información de configuración que deseas restaurar como parámetro params.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo 


 a| 
parámetros
 a| 
Un objeto JSON que contiene la información de configuración actual del clúster de almacenamiento.
 a| 
xref:reference_element_api_clusterstructure.adoc[Estructura del clúster]

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
resultado
 a| 
Manejador de resultados asíncronos.
 a| 
manejador asíncrono

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "SetClusterStructure",
  "params": <insert clusterStructure object here>,
  "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
	"id": 1,
	"result" : {
	"asyncHandle": 1
	}
}
----


== Nueva versión

10,3
