---
permalink: api/reference_element_api_setloginsessioninfo.html 
sidebar: sidebar 
keywords: authentication,login,session,info,timeout,setloginsessioninfo 
summary: Puede utilizar el método SetLoginSessionInfo para establecer el período de tiempo durante el cual es válida la autenticación de inicio de sesión para una sesión.  Una vez transcurrido el período de inicio de sesión sin actividad en el sistema, la autenticación caduca.  Se requieren nuevas credenciales de inicio de sesión para continuar accediendo al clúster una vez transcurrido el período de inicio de sesión. 
---
= SetLoginSessionInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `SetLoginSessionInfo` método para establecer el período de tiempo durante el cual es válida la autenticación de inicio de sesión para una sesión.  Una vez transcurrido el período de inicio de sesión sin actividad en el sistema, la autenticación caduca.  Se requieren nuevas credenciales de inicio de sesión para continuar accediendo al clúster una vez transcurrido el período de inicio de sesión.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
se acabó el tiempo
 a| 
Periodo de expiración de la autenticación del clúster.  Formateado en HH:mm:ss.  Por ejemplo: 01:30:00, 00:90:00 y 00:00:5400 se pueden usar para igualar un período de tiempo de espera de 90 minutos.  El tiempo de espera mínimo es de 1 minuto.  Cuando no se proporciona un valor, o se establece en cero, la sesión de inicio de sesión no tiene valor de tiempo de espera.
 a| 
cadena
 a| 
30 minutos
 a| 
No

|===


== Valor de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "SetLoginSessionInfo",
  "params": {
    "timeout" : "01:30:00"
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Nueva versión

9,6
