---
permalink: api/reference_element_api_startclusterpairing.html 
sidebar: sidebar 
keywords: cluster,pair,pairing,start,starting,startclusterpairing 
summary: Puede utilizar el método StartClusterPairing para crear una clave codificada a partir de un clúster que se utilice para emparejarlo con otro clúster.  La clave creada a partir de este método de la API se utiliza en el método CompleteClusterPairing para establecer un emparejamiento de clústeres.  Puedes emparejar un clúster con un máximo de otros cuatro clústeres. 
---
= Iniciar emparejamiento de clústeres
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `StartClusterPairing` Método para crear una clave codificada a partir de un clúster que se utiliza para emparejarse con otro clúster.  La clave creada a partir de este método de la API se utiliza en el `CompleteClusterPairing` Método para establecer un emparejamiento de clústeres.  Puedes emparejar un clúster con un máximo de otros cuatro clústeres.



== Parámetro

Este método no tiene parámetros de entrada.



== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
clave de emparejamiento de clúster
 a| 
Una cadena de caracteres que utiliza elxref:reference_element_api_completeclusterpairing.adoc[Emparejamiento de clústeres completo] Método API.
 a| 
cadena



 a| 
clusterPairID
 a| 
Identificador único para el par de clústeres.
 a| 
entero

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "StartClusterPairing",
   "params": {
      },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id": 1,
   "result": {
     "clusterPairID": 1,
     "clusterPairingKey": "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
   }
}
----


== Nueva versión

9,6



== Encuentra más información

xref:reference_element_api_completeclusterpairing.adoc[Emparejamiento de clústeres completo]
