---
permalink: api/reference_element_api_listsnapmirrorendpoints.html 
sidebar: sidebar 
keywords: snapmirror,endpoint,endpoints,list,listing,listsnapmirrorendpoints 
summary: La interfaz web del software Element utiliza el método ListSnapMirrorEndpoints para enumerar todos los puntos de conexión de SnapMirror con los que se comunica el clúster de almacenamiento de Element. 
---
= ListSnapMirrorEndpoints
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz web del software Element utiliza `ListSnapMirrorEndpoints` Método para listar todos los puntos de conexión de SnapMirror con los que se comunica el clúster de almacenamiento de Element.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
IDs de punto final de SnapMirror
 a| 
Devuelve únicamente los objetos asociados a estos identificadores.  Si no se proporcionan identificadores o la matriz está vacía, el método devuelve todos los identificadores de punto final de SnapMirror .
 a| 
matriz de enteros
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
snapMirrorEndpoints
 a| 
Una lista de los endpoints de SnapMirror existentes.
 a| 
xref:reference_element_api_snapmirrorendpoint.adoc[snapMirrorEndpoint]formación

|===


== Nueva versión

10,0
