---
permalink: api/reference_element_api_setsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,info,setting,set,setsnmpinfo 
summary: Puede utilizar el método SetSnmpInfo para configurar SNMP versión 2 y versión 3 en los nodos del clúster.  Los valores que establezca con esta interfaz se aplicarán a todos los nodos del clúster, y los valores que se pasen reemplazarán todos los valores establecidos en cualquier llamada anterior a SetSnmpInfo. 
---
= SetSnmpInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `SetSnmpInfo` Método para configurar SNMP versión 2 y versión 3 en nodos de clúster.  Los valores que establezca con esta interfaz se aplicarán a todos los nodos del clúster, y los valores que se pasen reemplazarán todos los valores establecidos en cualquier llamada anterior a `SetSnmpInfo` .



== Parámetros


NOTE: SetSnmpInfo está obsoleto para las versiones 6.0 y posteriores de Element.  Utilice elxref:reference_element_api_enablesnmp.adoc[Habilitar SNMP] yxref:reference_element_api_setsnmpacl.adoc[SetSnmpACL] métodos en su lugar.

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
redes
 a| 
Lista de redes y el tipo de acceso que tienen a los servidores SNMP que se ejecutan en los nodos del clúster.  Consulte el SNMP.xref:reference_element_api_network_snmp.adoc[red] objeto para valores posibles.  Este parámetro solo es necesario para SNMP v2.
 a| 
xref:reference_element_api_network_snmp.adoc[red]formación
 a| 
Ninguno
 a| 
No



 a| 
activado
 a| 
Si se establece en verdadero, SNMP se habilita en cada nodo del clúster.
 a| 
booleano
 a| 
FALSO
 a| 
No



 a| 
snmpV3Enabled
 a| 
Si se establece en verdadero, SNMP v3 se habilita en cada nodo del clúster.
 a| 
booleano
 a| 
FALSO
 a| 
No



 a| 
usuarios de usm
 a| 
Si SNMP v3 está habilitado, este valor debe pasarse en lugar del parámetro de redes.  Este parámetro solo es necesario para SNMP v3.
 a| 
xref:reference_element_api_usmuser.adoc[usmUser]
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud con SNMP v3 habilitado

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":true,
    "usmUsers":[
      {
        "name":"user1",
        "access":"rouser",
        "secLevel":"auth",
        "password":"namex1",
        "passphrase":"yourpassphrase"
      }
    ]
  },
 "id":1
}
----


== Ejemplo de solicitud con SNMP v2 habilitado

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":false,
    "networks":[
      {
        "community":"public",
        "access":"ro",
        "network":"localhost",
      }
    ]
  },
  "id":1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id" : 1
  "result" :{
  }
}
----


== Nueva versión

9,6
