---
permalink: api/reference_element_api_listdeletedvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,marked,delete,deleted,deletion,list,listing,listdeletedvolumes 
summary: Puede utilizar el método ListDeletedVolumes para recuperar la lista de volúmenes que han sido marcados para su eliminación y purgados del sistema. 
---
= Lista de volúmenes eliminados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListDeletedVolumes` Método para recuperar la lista de volúmenes que han sido marcados para su eliminación y purgados del sistema.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
incluir volúmenes virtuales
 a| 
Los volúmenes virtuales se incluyen en la respuesta de forma predeterminada.  Para excluir volúmenes virtuales, establezca el valor en falso.
 a| 
booleano
 a| 
verdadero
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
volúmenes
 a| 
Lista de volúmenes eliminados.
 a| 
xref:reference_element_api_volume.adoc[volume]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ListDeletedVolumes",
   "params": {},
   "id" : 1
}
----


== Ejemplo de respuesta

Las respuestas para este método son similares al siguiente ejemplo:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 2,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2018-06-24T03:13:13Z",
                "deleteTime": "2018-07-22T16:12:39Z",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:0oto.deletethis.23",
                "name": "deleteThis",
                "purgeTime": "2016-07-23T00:12:39Z",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "306f746f00000017f47acc0100000000",
                "scsiNAADeviceID": "6f47acc100000000306f746f00000017",
                "sliceCount": 1,
                "status": "deleted",
                "totalSize": 1396703232,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 23,
                "volumePairs": []
            }
        ]
    }
}
----


== Nueva versión

9,6
