---
permalink: api/reference_element_api_getsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,information,info,get,getting 
summary: 'Puede utilizar el método GetSnmpInfo para obtener la información de configuración actual del protocolo simple de administración de red (SNMP).' 
---
= Obtener información SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetSnmpInfo` Método para obtener la información de configuración actual del protocolo simple de administración de red (SNMP).



== Parámetros


NOTE: GetSnmpInfo está obsoleto para versiones posteriores a la versión 8.0 de Element.  Elxref:reference_element_api_getsnmpstate.adoc[Obtener estado SNMP] yxref:reference_element_api_setsnmpacl.adoc[SetSnmpACL] Estos métodos reemplazan al método GetSnmpInfo.

Este método no tiene parámetros de entrada.



== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
redes
 a| 
Lista de redes y tipos de acceso habilitados para SNMP.  *Nota:* La opción "Redes" solo se muestra si SNMP v3 está deshabilitado.
 a| 
xref:reference_element_api_network_snmp.adoc[red]



 a| 
activado
 a| 
Indica si los nodos del clúster están configurados para SNMP. Valores posibles:

* verdadero
* FALSO

 a| 
booleano



 a| 
snmpV3Enabled
 a| 
Si el nodo del clúster está configurado para SNMP v3. Valores posibles:

* verdadero
* FALSO

 a| 
booleano



 a| 
usuarios de usm
 a| 
Si SNMP v3 está habilitado, el clúster devuelve una lista de parámetros de acceso de usuario para SNMP.  Esto se devuelve en lugar del parámetro de redes.
 a| 
xref:reference_element_api_usmuser.adoc[usmUser]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "GetSnmpInfo",
   "params": {},
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id" : 1,
   "result" : {
      "enabled" : true,
      "networks" : [
         {
            "access" : "rosys",
            "cidr" : 0,
            "community" : "public",
            "network" : "localhost"
         }
      ]
   }
}
----


== Nueva versión

9,6



== Encuentra más información

* xref:reference_element_api_getsnmpstate.adoc[Obtener estado SNMP]
* xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL]

