---
permalink: api/reference_element_api_modifyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volume,access,group,modify,modifying,updating,changing,change,update,edit,editing,modifyvolumeaccessgroup 
summary: Puede utilizar el método ModifyVolumeAccessGroup para actualizar los iniciadores y agregar o eliminar volúmenes de un grupo de acceso a volúmenes. 
---
= Modificar grupo de acceso al volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ModifyVolumeAccessGroup` Método para actualizar los iniciadores y agregar o eliminar volúmenes de un grupo de acceso a volúmenes.

Si un iniciador o volumen especificado es un duplicado de lo que existe actualmente, el grupo de acceso al volumen se deja tal cual.  Si no especifica un valor para volúmenes o iniciadores, la lista actual de iniciadores y volúmenes no se modifica.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===


| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de grupo de acceso al volumen
 a| 
El ID del grupo de acceso al volumen que se va a modificar.
 a| 
entero
 a| 
Ninguno
 a| 
Sí



 a| 
nombre
 a| 
El nuevo nombre para este grupo de acceso por volumen.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
atributos
 a| 
Lista de pares nombre-valor en formato de objeto JSON.
 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No



 a| 
iniciadores
 a| 
Lista de identificadores o nombres de iniciador (IQN y WWPN) que se incluirán en el grupo de acceso por volumen.  Si se proporciona una lista de nombres de iniciadores, estos se crearán si aún no existen.  Si se pasa una lista de identificadores de iniciadores, el método devuelve un error si alguno de los iniciadores no existe.  El uso de nombres de iniciadores está obsoleto; debe utilizar identificadores de iniciador siempre que sea posible.
 a| 
matriz de enteros (recomendado) o matriz de cadenas (obsoleto)
 a| 
Ninguno
 a| 
No



 a| 
eliminarIniciadoresHuérfanos
 a| 
Especifica si se deben eliminar los objetos iniciadores después de que se eliminen de un grupo de acceso a volúmenes o no. Valores posibles:

* verdadero: Eliminar los objetos iniciadores después de que se eliminen de un grupo de acceso a volúmenes.
* falso: No elimine los objetos iniciadores después de que se eliminen de un grupo de acceso a volúmenes. Este es el valor predeterminado.

 a| 
booleano
 a| 
FALSO
 a| 
No



 a| 
volúmenes
 a| 
Lista de identificadores de volumen de los volúmenes que se van a modificar.
 a| 
matriz de enteros
 a| 
Ninguno
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[volumeAccessGroup]

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
volumeAccessGroup
 a| 
Un objeto que contiene información sobre el grupo de acceso a volúmenes recientemente modificado.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[volumeAccessGroup]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ModifyVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "name": "accessgrouptest",
      "initiators": [115,114],
      "volumes": [
         346
    ],
      "attributes": {}
   }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": null,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [
        114,
        115
      ],
      "initiators": [
        "iqn.1998-01.com.vmware:desk1-esx1-577b283a",
        "iqn.1998-01.com.vmware:donesq-esx1-421b281b"
      ],
      "name": "accessgrouptest",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== Nueva versión

9,6



== Encuentra más información

* xref:reference_element_api_addinitiatorstovolumeaccessgroup.adoc[AgregarIniciadoresAlGrupoDeAccesoPorVolumen]
* xref:reference_element_api_addvolumestovolumeaccessgroup.adoc[Agregar volúmenes al grupo de acceso a volúmenes]
* xref:reference_element_api_removeinitiatorsfromvolumeaccessgroup.adoc[EliminarIniciadoresDelGrupoDeAccesoPorVolumen]
* xref:reference_element_api_removevolumesfromvolumeaccessgroup.adoc[Eliminar volúmenes del grupo de acceso a volúmenes]

