---
permalink: api/reference_element_api_updatesnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,relationships,update,updating,destination,volume,updatesnapmirrorrelationship 
summary: La interfaz web del software Element utiliza el método UpdateSnapMirrorRelationship para convertir el volumen de destino en una relación SnapMirror en una réplica actualizada del volumen de origen. 
---
= ActualizarRelaciónSnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz web del software Element utiliza `UpdateSnapMirrorRelationship` Método para convertir el volumen de destino en una relación SnapMirror en una réplica actualizada del volumen de origen.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de punto final de SnapMirror
 a| 
El ID del punto final del sistema de almacenamiento ONTAP remoto que se comunica con el clúster de almacenamiento Element.
 a| 
entero
 a| 
Ninguno
 a| 
Sí



 a| 
volumen de destino
 a| 
El volumen de destino en la relación SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Ninguno
 a| 
Sí



 a| 
tasa de transferencia máxima
 a| 
Especifica la velocidad máxima de transferencia de datos entre los volúmenes en kilobytes por segundo.  El valor predeterminado, 0, es ilimitado y permite que la relación SnapMirror utilice completamente el ancho de banda de red disponible.
 a| 
entero
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
snapMirrorRelationship
 a| 
Un objeto que contiene información sobre la relación SnapMirror actualizada.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== Nueva versión

10,1
