---
permalink: api/reference_element_api_listpendingnodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,pending,nodes,node,listpendingnodes 
summary: Puede utilizar el método ListPendingNodes para listar los nodos de almacenamiento pendientes en el sistema.  Los nodos pendientes son nodos de almacenamiento que están en ejecución y configurados para unirse al clúster de almacenamiento, pero que aún no se han agregado mediante el método de la API AddNodes. 
---
= Lista de nodos pendientes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListPendingNodes` Método para listar los nodos de almacenamiento pendientes en el sistema.  Los nodos pendientes son nodos de almacenamiento que están en ejecución y configurados para unirse al clúster de almacenamiento, pero que aún no se han agregado mediante el método de la API AddNodes.



== direcciones de gestión IPv4 e IPv6

Tenga en cuenta que `ListPendingNodes` No enumera los nodos pendientes que tienen diferentes tipos de direcciones para la dirección IP de administración (MIP) y la dirección IP virtual de administración (MVIP).  Por ejemplo, si un nodo pendiente tiene una dirección IPv6 multi-IP (MVIP) y una dirección IPv4 multi-IP (MIP), `ListPendingNodes` No incluirá el nodo como parte del resultado.



== Parámetros

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
nodos pendientes
 a| 
Lista de nodos pendientes en el clúster.
 a| 
xref:reference_element_api_pendingnode.adoc[nodo pendiente]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ListPendingNodes",
   "params": {},
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 3,
  "result": {
    "pendingNodes": [
      {
        "assignedNodeID": 0,
        "cip": "10.26.65.101",
        "cipi": "Bond10G",
        "compatible": true,
        "mip": "172.26.65.101",
        "mipi": "Bond1G",
        "name": "VWC-EN101",
        "pendingNodeID": 1,
        "platformInfo": {
          "chassisType": "R620",
          "cpuModel": "Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz",
          "nodeMemoryGB": 72,
          "nodeType": "SF3010"
        },
        "sip": "10.26.65.101",
        "sipi": "Bond10G",
        "softwareVersion": "9.0.0.1554",
        "uuid": "4C4C4544-0048-4410-8056-C7C04F395931"
      }
    ]
  }
}
----


== Nueva versión

9,6



== Encuentra más información

xref:reference_element_api_addnodes.adoc[Agregar nodos]
