---
permalink: api/reference_element_api_setnodesupplementaltlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,set,setting,list,supplemental,setnodesupplementaltlsciphers,node 
summary: Puede utilizar el método SetNodeSupplementalTlsCiphers para especificar la lista de cifrados TLS suplementarios.  Puedes usar este comando en los nodos de administración. 
---
= SetNodeSupplementalTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `SetNodeSupplementalTlsCiphers` Método para especificar la lista de cifrados TLS suplementarios.  Puedes usar este comando en los nodos de administración.



== Parámetro


NOTE: Debes llamar a este método contra el nodo de administración. Por ejemplo:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
Cifrados suplementarios
 a| 
Los nombres de los conjuntos de cifrado suplementarios utilizan el esquema de nomenclatura de OpenSSL.  El uso de nombres de conjuntos de cifrado no distingue entre mayúsculas y minúsculas.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
Cifrados obligatorios
 a| 
Lista de conjuntos de cifrado TLS obligatorios para el nodo.  Se trata de cifrados que están siempre activos en el nodo.
 a| 
cadena



 a| 
Cifrados suplementarios
 a| 
Lista de conjuntos de cifrado TLS suplementarios para el nodo.
 a| 
cadena

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "SetNodeSupplementalTlsCiphers",
   "params": {
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
   },
   "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id" : 1,
  "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----