---
permalink: api/reference_element_api_clonevolume.html 
sidebar: sidebar 
keywords: volumes,volume,cloning,clone,CloneVolume 
summary: Puede utilizar el método CloneVolume para crear una copia de un volumen.  Este método es asíncrono y puede tardar un tiempo variable en completarse. 
---
= Clonar volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `CloneVolume` Método para crear una copia de un volumen.  Este método es asíncrono y puede tardar un tiempo variable en completarse.

El proceso de clonación comienza inmediatamente cuando realizas la `CloneVolume` La solicitud es representativa del estado del volumen cuando se emite el método de la API.  Puedes usar elxref:reference_element_api_getasyncresult.adoc[ObtenerResultadoAsíncrono] método para determinar cuándo finaliza el proceso de clonación y el nuevo volumen está disponible para conexiones.  Puedes usarxref:reference_element_api_listsyncjobs.adoc[ListSyncJobs] para ver el progreso de la creación del clon.  Los atributos iniciales y la configuración de calidad de servicio del volumen se heredan del volumen que se está clonando.  Puedes cambiar estos ajustes conxref:reference_element_api_modifyvolume.adoc[Modificar volumen] .


NOTE: Los volúmenes clonados no heredan la pertenencia al grupo de acceso al volumen del volumen de origen.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
acceso
 a| 
Se ha permitido el acceso al nuevo volumen.  Si no se especifica un valor, el valor de acceso no cambia. Valores posibles:

* `readOnly`: (Opcional) Solo se permiten operaciones de lectura.
* `readWrite`(Opcional) Se permiten lecturas y escrituras.
* `locked`(Opcional) No se permiten lecturas ni escrituras.  Si no se especifica, se utiliza el valor de acceso del volumen que se está clonando.
* `replicationTarget`: (Opcional) Identifique un volumen como el volumen objetivo para un conjunto de volúmenes emparejados.  Si el volumen no está emparejado, el estado de acceso queda bloqueado.

 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
atributos
 a| 
Lista de pares nombre-valor en formato de objeto JSON.
 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No



 a| 
enable512e
 a| 
Especifica si el nuevo volumen debe utilizar la emulación de sectores de 512 bytes.  Si no se especifica, se utiliza la configuración del volumen que se está clonando.
 a| 
booleano
 a| 
Ajuste del volumen original
 a| 
No



 a| 
habilitarSnapMirrorReplication
 a| 
Determina si el volumen se puede utilizar para la replicación con puntos de conexión SnapMirror . Valores posibles:

* verdadero
* FALSO

 a| 
booleano
 a| 
FALSO
 a| 
No



 a| 
nombre
 a| 
Nombre del nuevo volumen clonado; debe tener entre 1 y 64 caracteres de longitud.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
nuevo ID de cuenta
 a| 
ID de cuenta del propietario del nuevo volumen.  Si no se especifica, se utiliza el ID de cuenta del propietario del volumen que se está clonando.
 a| 
entero
 a| 
ID de cuenta del propietario del volumen original
 a| 
No



 a| 
nuevoTamaño
 a| 
Nuevo tamaño del volumen, en bytes.  Podría ser mayor o menor que el tamaño del volumen que se está clonando.  Si no se especifica, el tamaño del volumen no se modifica.  El tamaño se redondea al MB más cercano.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
ID de instantánea
 a| 
Identificador de la instantánea que se utiliza como fuente del clon.  Si no se proporciona un ID, se utiliza el volumen activo actual.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
ID de volumen
 a| 
ID del volumen que se va a clonar.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
manejador asíncrono
 a| 
El valor del identificador utilizado para obtener el resultado de la operación.
 a| 
entero



 a| 
ID de clon
 a| 
El ID del clon para el volumen recién clonado.
 a| 
entero



 a| 
curva
 a| 
Los valores de la curva QoS aplicados al clon.
 a| 
Objeto JSON



 a| 
volume
 a| 
Un objeto que contiene información sobre el volumen recién clonado.
 a| 
xref:reference_element_api_volume.adoc[volume]



 a| 
ID de volumen
 a| 
ID del volumen recién clonado.
 a| 
entero

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "CloneVolume",
   "params": {
      "volumeID" : 5,
      "name"  : "mysqldata-snapshot1",
      "access" : "readOnly"
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
      "asyncHandle": 42,
      "cloneID": 37,
      "volume": {
          "access": "readOnly",
          "accountID": 1,
          "attributes": {},
          "blockSize": 4096,
          "createTime": "2016-03-31T22:26:03Z",
          "deleteTime": "",
          "enable512e": true,
          "iqn": "iqn.2010-01.com.solidfire:jyay.mysqldata-snapshot1.680",
          "name": "mysqldata-snapshot1",
          "purgeTime": "",
          "qos": {
              "burstIOPS": 100,
              "burstTime": 60,
              "curve": {
                  "4096": 100,
                  "8192": 160,
                  "16384": 270,
                  "32768": 500,
                  "65536": 1000,
                  "131072": 1950,
                  "262144": 3900,
                  "524288": 7600,
                  "1048576": 15000
              },
              "maxIOPS": 100,
              "minIOPS": 50
          },
          "scsiEUIDeviceID": "6a796179000002a8f47acc0100000000",
          "scsiNAADeviceID": "6f47acc1000000006a796179000002a8",
          "sliceCount": 0,
          "status": "init",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeAccessGroups": [],
          "volumeID": 680,
          "volumePairs": []
      },
      "volumeID": 680
  }
}
----


== Nueva versión

9,6



== Encuentra más información

* xref:reference_element_api_getasyncresult.adoc[ObtenerResultadoAsíncrono]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]
* xref:reference_element_api_modifyvolume.adoc[Modificar volumen]

