---
permalink: api/reference_element_api_completeclusterpairing.html 
sidebar: sidebar 
keywords: CompleteClusterPairing,cluster,pair,pairing,complete,completing 
summary: El método CompleteClusterPairing es el segundo paso en el proceso de emparejamiento de clústeres.  Utilice este método con la clave codificada recibida del método StartClusterPairing para completar el proceso de emparejamiento de clústeres. 
---
= Emparejamiento de clústeres completo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El `CompleteClusterPairing` Este método es el segundo paso en el proceso de emparejamiento de clústeres.  Utilice este método con la clave codificada recibida de `StartClusterPairing` Método para completar el proceso de emparejamiento de clústeres.



== Parámetros

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
clave de emparejamiento de clúster
 a| 
Una cadena de caracteres que se devuelve desde elxref:reference_element_api_startclusterpairing.adoc[Iniciar emparejamiento de clústeres] Método API.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
clusterPairID
 a| 
Identificador único para el par de clústeres.
 a| 
entero

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "CompleteClusterPairing",
   "params": {
        "clusterPairingKey" : "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id" : 1,
   "result" : {
       "clusterPairID" : 1
   }
}
----


== Nueva versión

9,6



== Encuentra más información

xref:reference_element_api_startclusterpairing.adoc[Iniciar emparejamiento de clústeres]
