---
permalink: api/reference_element_api_createclusterinterfacepreference.html 
sidebar: sidebar 
keywords: cluster,interface,preferences,create,creating,CreateClusterInterfacePreference 
summary: El método CreateClusterInterfacePreference permite que los sistemas integrados con clústeres de almacenamiento que ejecutan el software Element creen y almacenen información arbitraria en el clúster de almacenamiento.  Este método es para uso interno. 
---
= CrearPreferenciaDeInterfazDeClúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El `CreateClusterInterfacePreference` Este método permite que los sistemas integrados con clústeres de almacenamiento que ejecutan el software Element creen y almacenen información arbitraria en el clúster de almacenamiento.  Este método es para uso interno.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
nombre
 a| 
El nombre de la preferencia de interfaz del clúster.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
valor
 a| 
El valor de la preferencia de interfaz del clúster.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
		"method": "CreateClusterInterfacePreference",
		"params": {
			"name": "prefname",
			"value": "testvalue"
		},
	"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
	"id": 1,
	"result": {}
}
----


== Nueva versión

11,0
