---
permalink: api/reference_element_api_getnodehardwareinfo.html 
sidebar: sidebar 
keywords: node,hardware,info,get,getting,getnodehardwareinfo 
summary: Puede utilizar el método GetNodeHardwareInfo para obtener toda la información y el estado del hardware del nodo especificado.  Esto generalmente incluye fabricantes, vendedores, versiones y otra información de identificación de hardware asociada. 
---
= Información del hardware del nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetNodeHardwareInfo` Método para devolver toda la información de hardware y el estado del nodo especificado.  Esto generalmente incluye fabricantes, vendedores, versiones y otra información de identificación de hardware asociada.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de nodo
 a| 
El identificador del nodo para el que se solicita información de hardware.  Si se especifica un nodo Fibre Channel, se devuelve información sobre él.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
nodoHardwareInfo
 a| 
Información de hardware para el nodeID especificado.  Cada objeto en esta salida está etiquetado con el nodeID del nodo dado.
 a| 
xref:reference_element_api_hardwareinfo.adoc[Información de hardware]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "GetNodeHardwareInfo",
   "params": {
     "nodeID": 1
   },
"id" : 1
}
----


== Ejemplo de respuesta

Debido a la extensión de este ejemplo de respuesta, se documenta en un tema complementario.



== Nueva versión

9,6



== Encuentra más información

xref:reference_element_api_response_example_getnodehardwareinfo_fibre_channel.adoc[GetNodeHardwareInfo (salida para nodos Fibre Channel)]

xref:reference_element_api_response_example_getnodehardwareinfo.adoc[GetNodeHardwareInfo (salida para iSCSI)]
