---
permalink: api/reference_element_api_removeclusteradmin.html 
sidebar: sidebar 
keywords: cluster,admin,remove,removing,removeclusteradmin 
summary: 'Puede utilizar el método RemoveClusterAdmin para eliminar un administrador de clúster, un administrador de clúster LDAP o un administrador de clúster de proveedor de identidad (IdP) de terceros.  No se puede eliminar la cuenta de administrador del clúster "admin".' 
---
= Eliminar administrador del clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `RemoveClusterAdmin` Método para eliminar un administrador de clúster, un administrador de clúster LDAP o un administrador de clúster de proveedor de identidad (IdP) de terceros.  No puedes eliminar la cuenta de administrador del clúster "admin".



== Parámetro

Cuando se elimina un administrador de clúster IdP que tiene sesiones autenticadas asociadas con un proveedor de identidad IdP de terceros, esas sesiones se cerrarán o posiblemente experimentarán una pérdida de derechos de acceso dentro de su sesión actual.  La pérdida de derechos de acceso dependerá de si el administrador del clúster IdP eliminado coincidía con alguno de los múltiples administradores del clúster IdP de los atributos SAML de un usuario determinado.  El conjunto restante de administradores de clúster IdP coincidentes da como resultado un conjunto reducido de derechos de acceso agregados.  Los demás tipos de usuarios administradores del clúster se desconectan cuando se eliminan sus administradores del clúster.

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de administrador del clúster
 a| 
ID de administrador del clúster para eliminar.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "RemoveClusterAdmin",
   "params": {
     "clusterAdminID"  : 2
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
 "id" : 1
 "result" : { }
}
----


== Nueva versión

9,6
