---
permalink: api/reference_element_api_getnodeactivetlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,ciphers,get,getting,getnodeactivetlsciphers,accepted 
summary: Puede utilizar el método GetNodeActiveTlsCiphers en un solo nodo para obtener una lista de los cifrados TLS que se aceptan actualmente en este nodo.  Puedes utilizar este método en nodos de gestión y almacenamiento. 
---
= ObtenerCifrasTlsActivasDeNodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetNodeActiveTlsCiphers` Método en un solo nodo para obtener una lista de los cifrados TLS que actualmente se aceptan en este nodo.  Puedes utilizar este método en nodos de gestión y almacenamiento.



== Parámetro

Este método no tiene parámetros de entrada.



== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
Cifrados obligatorios
 a| 
Lista de conjuntos de cifrado TLS obligatorios para el nodo.  Se trata de cifrados que están siempre activos en el nodo.
 a| 
cadena



 a| 
Cifrados suplementarios
 a| 
Lista de conjuntos de cifrado TLS suplementarios para el nodo.
 a| 
cadena

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "GetNodeActiveTlsCiphers",
  "params": {},
  "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
      "id" : 1,
      "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----