---
permalink: api/reference_element_api_getqospolicy.html 
sidebar: sidebar 
keywords: qos,policy,policies,get,getting,getqospolicy 
summary: Puede utilizar el método GetQoSPolicy para obtener detalles sobre una política QoS específica del sistema. 
---
= Obtener política de QoS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetQoSPolicy` Método para obtener detalles sobre una política QoS específica del sistema.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de política de qos
 a| 
El ID de la póliza que se va a recuperar.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
Política de calidad de servicio
 a| 
Detalles de la política de QoS solicitada.
 a| 
xref:reference_element_api_qospolicy.adoc[Política de QoS]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
	"method": "GetQoSPolicy",
    "params": {
    	"qosPolicyID": 2
    },
    "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "qosPolicy": {
      "name": "bronze",
      "qos": {
        "burstIOPS": 15002,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 15002,
        "minIOPS": 51
      },
      "qosPolicyID": 2,
      "volumeIDs": [
          2
      ]
    }
  }
}
----


== Nueva versión

10,0
