---
permalink: api/reference_element_api_testnetworkconfig.html 
sidebar: sidebar 
keywords: test,testing,network,config,configuration,testnetworkconfig 
summary: Puede utilizar el método TestNetworkConfig para comprobar que la configuración de red configurada coincide con la configuración de red que se está utilizando en el sistema. 
---
= Configuración de red de prueba
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `TestNetworkConfig` Método para comprobar que la configuración de red configurada coincide con la configuración de red que se está utilizando en el sistema.



== Parámetros

Cuando configura un nodo con el método SetNetworkConfig, en la interfaz de usuario o en la interfaz de usuario de texto, la configuración se valida y se almacena.  La prueba de la API TestNetworkConfig utiliza la configuración almacenada para la lógica posterior a la validación.  Por ejemplo, en caso de un corte de energía o una falla de red, puede usar este método de API para asegurarse de que un nodo esté funcionando con la configuración de red almacenada más reciente.  Esto valida que no hay errores en la configuración y que se está utilizando la configuración actual.

Esta prueba está diseñada para mostrar únicamente los fallos en la respuesta.  Si no hay errores, esta prueba no devuelve ningún resultado.  Vea los siguientes ejemplos de respuesta.

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
detalles
 a| 
Contiene cualquier error encontrado al validar la configuración de red almacenada actualmente con la configuración de red en ejecución.
 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "TestNetworkConfig",
   "params": {},
   "id" : 1
}
----


== Ejemplo de respuesta 1

Si no se detectan errores, no se devuelve ninguna respuesta.

[listing]
----
{
   "id" : 1,
   "result": {
   "details": {
   "network": {...}
  },
   "duration": "00:00:00.144514",
   "result": "Passed"
  }
}
----


== Ejemplo de respuesta 2

Ejemplo de una discrepancia de MTU.

[listing]
----
{
  "id" : 1,
  "result":
  {
	 "details" :
	 {
		"error":
		{
		   "message" : "Network configuration mismatch on Bond10G: Incorrect MTU expectedMTU=[1500]  actualMTU=[9600]", name: "xAssertionFailure"
		}
	 },
	 "duration": "0.125213sec",
	 "result": "Failed"
  }
}
----


== Ejemplo de respuesta 3

Ejemplo de una ruta estática faltante.

[listing]
----
{
  "id": 1,
  "result":
  {
	 "details" :
	 {
	 "error":
		{
		"message" : "Network configuration mismatch on Bond1G: Routing table missing route=[192.168.137.2 via 192.168.159.254 dev Bond1G]", name: "xAssertionFailure"
		}
	 },
	 "duration" : "0.128547sec",
	 "result" : "Failed"
  }
}
----


== Nueva versión

9,6



== Encuentra más información

xref:reference_element_api_setnetworkconfig.adoc[Configurar configuración de red]
