---
permalink: api/reference_element_api_listkeyserverskmip.html 
sidebar: sidebar 
keywords: KMIP,key server,key,server,listing,list,listkeyserverskmip 
summary: 'Puede utilizar el método ListKeyServersKmip para enumerar todos los servidores de claves del Protocolo de interoperabilidad de gestión de claves (KMIP) que se han creado.  Puede filtrar los resultados especificando parámetros adicionales.' 
---
= Lista de servidores clave Kmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListKeyServersKmip` Método para listar todos los servidores de claves del Protocolo de Interoperabilidad de Gestión de Claves (KMIP) que se han creado.  Puede filtrar los resultados especificando parámetros adicionales.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID del proveedor de clave
 a| 
Cuando se especifica, el método solo devuelve los servidores de claves KMIP que están asignados al proveedor de claves KMIP especificado.  Si se omite, los servidores de claves KMIP devueltos no se filtrarán en función de si están asignados al proveedor de claves KMIP especificado.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
kmipAssignedProviderIsActive
 a| 
Los filtros devolvieron objetos de servidor de claves KMIP en función de si están activos o no. Valores posibles:

* verdadero: Devuelve solo los servidores de claves KMIP que están activos (proporcionando claves que se están utilizando actualmente).
* false: Devuelve solo los servidores de claves KMIP que están inactivos (no proporcionan ninguna clave y pueden ser eliminados).


Si se omite, los servidores de claves KMIP devueltos no se filtran en función de si están activos o no.
 a| 
booleano
 a| 
Ninguno
 a| 
No



 a| 
kmipTieneProveedorAsignado
 a| 
Los filtros devolvieron servidores de claves KMIP en función de si tenían asignado un proveedor de claves KMIP. Valores posibles:

* verdadero: Devuelve solo los servidores de claves KMIP que tienen asignado un proveedor de claves KMIP.
* false: Devuelve solo los servidores de claves KMIP que no tienen asignado un proveedor de claves KMIP.


Si se omite, los servidores de claves KMIP devueltos no se filtran en función de si tienen asignado un proveedor de claves KMIP.
 a| 
booleano
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
Servidores de claves kmip
 a| 
La lista completa de servidores clave KMIP que se han creado.
 a| 
link:reference_element_api_keyserverkmip.html["KeyServerKmip"]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "ListKeyServersKmip",
  "params": {},
"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
    "kmipKeyServers": [
        {
            "kmipKeyServerName": "keyserverName",
            "kmipClientCertificate": "dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "keyServerID": 15,
            "kmipAssignedProviderIsActive": true,
            "kmipKeyServerPort": 5696,
            "kmipCaCertificate": "MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames": [
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID": 1
        }
    ]
}
----


== Nueva versión

11,7
