---
permalink: api/reference_element_api_disablefeature.html 
sidebar: sidebar 
keywords: SNMP,disable,disabling,DisableFeature,vvols,virtual volumes 
summary: Puede utilizar el método DisableFeature para deshabilitar VolumeLoadBalanceOnActualIOPS. 
---
= Deshabilitar función
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `DisableFeature` método para deshabilitar el `VolumeLoadBalanceOnActualIOPS` característica. `VolumeLoadBalanceOnActualIOPS` está desactivado por defecto.

[NOTE]
====
Si intenta desactivar otra función, como VVols, aparece el siguiente mensaje de error:

[listing]
----
{"error":{"code":500,"message":"VolumeLoadBalanceOnActualIOPS is the only feature that can be disabled","name":"xAPINotPermitted"},"id":null}
----
====


== Parámetro

Este método tiene el siguiente parámetro de entrada.

[cols="1a,3a,1a,1a,1a"]
|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
característica
 a| 
Deshabilitar una función del clúster.  Valor posible:

* `VolumeLoadBalanceOnActualIOPS`Deshabilitar el balanceo de segmentos en IOPS reales en lugar de IOPS mínimas.

 a| 
cadena
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "DisableFeature",
    "params": {
        "feature" : "VolumeLoadBalanceOnActualIOPS"
    },
    "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Nueva versión

12,8
