---
permalink: api/reference_element_api_protectionschemetolerance.html 
sidebar: sidebar 
keywords: object,objects,protectionSchemeTolerance 
summary: El objeto protectionSchemeTolerance contiene información sobre si un clúster de almacenamiento, para un esquema de protección específico, puede continuar leyendo y escribiendo datos después de fallos. 
---
= Tolerancia del esquema de protección
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El objeto protectionSchemeTolerance contiene información sobre si un clúster de almacenamiento, para un esquema de protección específico, puede continuar leyendo y escribiendo datos después de fallos.



== miembros del objeto

Este objeto contiene los siguientes miembros:

|===
| Nombre | Descripción | Tipo 


 a| 
Esquema de protección
 a| 
El esquema de protección actual de este clúster de almacenamiento.  El único valor posible es doubleHelix.
 a| 
cadena



 a| 
Fracasos sostenibles para BlockData
 a| 
El número actual de fallos simultáneos que pueden producirse sin perder la disponibilidad de datos de bloque para el esquema de protección asociado.
 a| 
entero



 a| 
fallos sostenibles para los metadatos
 a| 
El número actual de fallos simultáneos que pueden producirse sin perder la disponibilidad de metadatos para el esquema de protección asociado.
 a| 
entero

|===