---
permalink: api/reference_element_api_listauthsessionbyusername.html 
sidebar: sidebar 
keywords: username,sessions,authentication sessions,list 
summary: Puede utilizar el método ListAuthSessionsByUsername para listar todas las sesiones de autenticación del usuario especificado.  Un usuario que no tenga privilegios de administrador o del grupo de acceso ClusterAdmins solo podrá listar sus propias sesiones.  Un usuario con privilegios de Administrador de clúster puede listar las sesiones pertenecientes a cualquier usuario. 
---
= Listar sesiones de autenticación por nombre de usuario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListAuthSessionsByUsername` Método para listar todas las sesiones de autenticación del usuario especificado.  Un usuario que no tenga privilegios de administrador o del grupo de acceso ClusterAdmins solo podrá listar sus propias sesiones.  Un usuario con privilegios de Administrador de clúster puede listar las sesiones pertenecientes a cualquier usuario.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
método de autenticación
 a| 
Método de autenticación de las sesiones de usuario que se mostrarán.  Solo un usuario perteneciente al grupo de acceso ClusterAdmins/Administrator puede proporcionar este parámetro.  Los valores posibles son:

* *authMethod=Cluster* especifica el nombre de usuario ClusterAdmin.
* *authMethod=Ldap* especifica el DN LDAP del usuario.
* *authMethod=Idp* especifica el UUID o el NameID del IdP del usuario.  Si el IdP no está configurado para devolver ninguna de las dos opciones, esto especifica un UUID aleatorio emitido cuando se creó la sesión.

 a| 
método de autenticación
 a| 
Ninguno
 a| 
Sí



 a| 
nombre de usuario
 a| 
Identificador único del usuario.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
sesiones
 a| 
Lista de información de sesión para las sesiones de autenticación.
 a| 
link:reference_element_api_authsessioninfo.html["información de sesión de autenticación"]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
    "method": "ListAuthSessionsByUsername",
    "authMethod": "Cluster",
    "username": "admin"
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nueva versión

12,0
