---
permalink: api/reference_element_api_createvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volume,access,groups,group,create,creating,CreateVolumeAccessGroup 
summary: Puede utilizar CreateVolumeAccessGroup para crear un nuevo grupo de acceso a volúmenes.  Al crear el grupo de acceso a volúmenes, debe darle un nombre y, opcionalmente, puede introducir iniciadores y volúmenes. 
---
= Crear grupo de acceso a volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar `CreateVolumeAccessGroup` para crear un nuevo grupo de acceso a volúmenes.  Al crear el grupo de acceso a volúmenes, debe darle un nombre y, opcionalmente, puede introducir iniciadores y volúmenes.

Cualquier IQN iniciador que agregue al grupo de acceso a volúmenes podrá acceder a cualquier volumen del grupo sin autenticación CHAP.


NOTE: Los volúmenes clonados no heredan la pertenencia al grupo de acceso al volumen del volumen de origen.

Tenga en cuenta lo siguiente al crear grupos de acceso a volúmenes:

* Un grupo de acceso por volumen puede contener hasta 64 IQN de iniciador.
* Un iniciador solo puede pertenecer a un grupo de acceso a volúmenes.
* Un grupo de acceso a volúmenes puede contener hasta 2000 volúmenes.
* Cada grupo de acceso a volúmenes puede pertenecer a un máximo de cuatro grupos de acceso a volúmenes.




== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
iniciadores
 a| 
Lista de identificadores o nombres de iniciador (IQN y WWPN) que se incluirán en el grupo de acceso por volumen.  Si se proporciona una lista de nombres de iniciadores, estos se crearán si aún no existen.  Si se pasa una lista de identificadores de iniciadores, el método devuelve un error si alguno de los iniciadores no existe.  El uso de nombres de iniciadores está obsoleto; debe utilizar identificadores de iniciador siempre que sea posible.
 a| 
matriz de enteros o matriz de cadenas (obsoleto)
 a| 
 a| 
No



 a| 
nombre
 a| 
Nombre del grupo de acceso al volumen.  No es necesario que sea único, pero es recomendable.  Debe tener entre 1 y 64 caracteres de longitud.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
volúmenes
 a| 
Lista de ID de volumen que se incluirán en el grupo de acceso a volúmenes.
 a| 
matriz de enteros
 a| 
 a| 
No



 a| 
atributos
 a| 
Lista de pares nombre-valor en formato de objeto JSON.
 a| 
Objeto JSON
 a| 
{}
 a| 
No

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
volumeAccessGroup
 a| 
Un objeto que contiene información sobre el grupo de acceso a volúmenes recién creado.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[volumeAccessGroup]



 a| 
ID de grupo de acceso al volumen
 a| 
El ID del grupo de acceso a volúmenes recién creado.
 a| 
entero

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "CreateVolumeAccessGroup",
   "params": {
      "name": "myaccessgroup",
      "initiators": ["iqn.1993-08.org.debian: 01: a31b1d799d5c"],
      "volumes": [327],
      "attributes": {}
   }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": null,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [],
      "initiatorIDs": [
        95
      ],
      "initiators": [
        "iqn.1993-08.org.debian: 01: a31b1d799d5c"
      ],
      "name": "myaccessgroup",
      "volumeAccessGroupID": 96,
      "volumes": [
        327
      ]
    },
    "volumeAccessGroupID": 96
  }
}
----


== Nueva versión

9,6



== Encuentra más información

* xref:reference_element_api_getasyncresult.adoc[ObtenerResultadoAsíncrono]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]
* xref:reference_element_api_modifyvolume.adoc[Modificar volumen]

