---
permalink: api/reference_element_api_getsnmpacl.html 
sidebar: sidebar 
keywords: snmp,acl,get,getting,getsnmpacl 
summary: Puede utilizar el método GetSnmpACL para obtener los permisos de acceso SNMP actuales en los nodos del clúster. 
---
= Obtener ACL SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetSnmpACL` Método para obtener los permisos de acceso SNMP actuales en los nodos del clúster.



== Parámetros

Este método no tiene parámetros de entrada.



== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
redes
 a| 
Lista de redes y el tipo de acceso que tienen a los servidores SNMP que se ejecutan en los nodos del clúster.  Este valor está presente si SNMP v3 está deshabilitado.
 a| 
xref:reference_element_api_network_snmp.adoc[red]formación



 a| 
usuarios de usm
 a| 
Lista de usuarios y el tipo de acceso que tienen a los servidores SNMP que se ejecutan en los nodos del clúster.  Este valor está presente si SNMP v3 está habilitado.
 a| 
xref:reference_element_api_usmuser.adoc[usmUser]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
"method": "GetSnmpACL",
"params": {},
"id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id" : 1,
  "result" : {
     "usmUsers"  : [
       {
          "name": "jdoe",
          "access": "rouser",
          "secLevel": "priv",
          "password": "mypassword",
          "passphrase": "mypassphrase",
       }
     ]
   }
}
----


== Nueva versión

9,6
