---
permalink: api/reference_element_api_startbulkvolumewrite.html 
sidebar: sidebar 
keywords: volume,bulk,start,starting,write,session,startbulkvolumewrite 
summary: Puede utilizar el método StartBulkVolumeWrite para iniciar una sesión de escritura masiva de volumen en un volumen específico. 
---
= Iniciar escritura masiva de volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `StartBulkVolumeWrite` Método para iniciar una sesión de escritura masiva de volumen en un volumen especificado.

Solo dos procesos de volumen masivo pueden ejecutarse simultáneamente en un volumen.  Al inicializar la sesión, los datos se escriben en un volumen de almacenamiento de Element desde una fuente de copia de seguridad externa.  Se accede a los datos externos mediante un servidor web que se ejecuta en un nodo de almacenamiento Element.  La información de interacción con el servidor para el acceso a datos externos se transmite mediante un script que se ejecuta en el sistema de almacenamiento.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
formato
 a| 
El formato de los datos de volumen.  Puede ser cualquiera de los siguientes:

* `uncompressed`Se devuelve cada byte del volumen sin compresión alguna.
* `native`Se devuelven datos opacos que son más pequeños y se almacenan y escriben de manera más eficiente en una escritura de volumen masivo posterior.

 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
ID de volumen
 a| 
El identificador del volumen en el que se va a escribir.
 a| 
entero
 a| 
Ninguno
 a| 
Sí



 a| 
guion
 a| 
El nombre de un script ejecutable.  Si no se proporciona un nombre de script, la clave y la URL son necesarias para acceder a los nodos de almacenamiento de Element.  El script se ejecuta en el nodo primario y la clave y la URL se devuelven al script para que se pueda contactar con el servidor web local.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
Parámetros del script
 a| 
Parámetros JSON para pasar al script.
 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No



 a| 
atributos
 a| 
Lista de pares nombre-valor en formato de objeto JSON. link:reference_element_api_attributes.html["Más información"].
 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
manejador asíncrono
 a| 
El ID del proceso asíncrono que se comprobará para verificar su finalización.
 a| 
entero



 a| 
llave
 a| 
Clave opaca que identifica de forma única la sesión.
 a| 
cadena



 a| 
URL
 a| 
URL para acceder al servidor web del nodo.
 a| 
cadena

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "StartBulkVolumeWrite",
   "params": {
      "volumeID" : 5,
      "format"  : "native",
   },
   "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id" : 1,
   "result" : {
      "asyncHandle" : 1,
      "key" : "11eed8f086539205beeaadd981aad130",
      "url" : "https://127.0.0.1:44000/"
   }
}
----


== Nueva versión

9,6
