---
permalink: api/reference_element_api_checkproposednodeadditions.html 
sidebar: sidebar 
keywords: proposed,node,additions,CheckProposedNodeAdditions,storage,checking 
summary: Puede utilizar el método CheckProposedNodeAdditions para probar un conjunto de nodos de almacenamiento y comprobar si puede agregarlos a un clúster de almacenamiento sin errores ni violaciones de las mejores prácticas. 
---
= Verificar adiciones de nodos propuestas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `CheckProposedNodeAdditions` Método para probar un conjunto de nodos de almacenamiento para comprobar si se pueden agregar a un clúster de almacenamiento sin errores ni violaciones de las mejores prácticas.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
nodos
 a| 
Una lista de direcciones IP de almacenamiento de nodos de almacenamiento que están listos para ser agregados a un clúster de almacenamiento.
 a| 
matriz de cadenas
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
Cluster propuesto válido
 a| 
Indica si los nodos de almacenamiento propuestos conformarían o no un clúster de almacenamiento válido. Valores posibles:

* verdadero
* FALSO

 a| 
booleano



 a| 
Errores de clúster propuestos
 a| 
Errores que se producirían si se creara un clúster de almacenamiento utilizando los nodos de almacenamiento propuestos.  Posibles códigos de error:

* `nodesNoCapacity`Los nodos no tenían capacidad utilizable.
* `nodesTooLarge`Los nodos constituyen una porción demasiado grande de la capacidad del clúster para el esquema de protección activa.
* `nodesConnectFailed`No se pudo conectar con los nodos para consultar la configuración del hardware.
* `nodesQueryFailed`No se pudo consultar la configuración de hardware de los nodos.
* `nodesClusterMember`Las direcciones IP para los nodos ya están en uso en el clúster.
* `nonFipsNodeCapable`No se puede agregar un nodo no compatible con FIPS al clúster de almacenamiento mientras la función de cifrado de unidad FIPS 140-2 está habilitada.
* `nonFipsDrivesCapable`No se puede agregar un nodo con unidades no compatibles con FIPS al clúster mientras la función de cifrado de unidades FIPS 140-2 está habilitada.

 a| 
matriz de cadenas

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
	"method": "CheckProposedNodeAdditions",
	"params": {
	"nodes": [
		"192.168.1.11",
		"192.168.1.12",
		"192.168.1.13",
		"192.168.1.14"
	]
},
	"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
	"id": 1,
	"result": {
		"proposedClusterValid": true,
		"proposedClusterErrors": [ ]
	}
}
----


== Nueva versión

11,0
