---
permalink: api/reference_element_api_listinitiators.html 
sidebar: sidebar 
keywords: initiators,initiator,list,listing,listinitiators,iqn,wwpn,iqns,wwpns 
summary: 'Puede utilizar el método ListInitiators para obtener la lista de IQN de iniciadores o nombres de puerto mundial (WWPN).' 
---
= Iniciadores de listas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListInitiators` Método para obtener la lista de IQN de iniciadores o nombres de puertos mundiales (WWPN).



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
iniciadores
 a| 
Una lista de identificadores de iniciador para recuperar.  Puede proporcionar este parámetro o el parámetro startInitiatorID, pero no ambos.
 a| 
matriz de enteros
 a| 
Ninguno
 a| 
No



 a| 
ID de iniciador de inicio
 a| 
El ID del iniciador desde el cual comenzar la lista.  Puede proporcionar este parámetro o el parámetro de iniciadores, pero no ambos.
 a| 
entero
 a| 
0
 a| 
No



 a| 
límite
 a| 
El número máximo de objetos iniciadores que se devolverán.
 a| 
entero
 a| 
(ilimitado)
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
iniciadores
 a| 
Lista de información del iniciador.
 a| 
xref:reference_element_api_initiator.adoc[iniciador]formación

|===


== Excepciones

Este método puede tener la siguiente excepción:

|===


| Nombre | Descripción 


 a| 
xParámetro no válido
 a| 
Se produce un error si se incluyen los parámetros startInitiatorID e initiators en la misma llamada al método.

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ListInitiators",
   "params": {},
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "initiators": [
      {
        "alias": "",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:c84ffd71216",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== Nueva versión

9,6
