---
permalink: api/reference_element_api_resetdrives.html 
sidebar: sidebar 
keywords: drive,drives,remove,removing,data,reset,resetting,resetdrives,erase 
summary: Puede utilizar el método ResetDrives para inicializar de forma proactiva las unidades y eliminar todos los datos que residen actualmente en una unidad.  Posteriormente, la unidad se puede reutilizar en un nodo existente o utilizarse en un nodo actualizado. 
---
= Restablecer unidades
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ResetDrives` Método para inicializar de forma proactiva las unidades y eliminar todos los datos que residen actualmente en una unidad.  Posteriormente, la unidad se puede reutilizar en un nodo existente o utilizarse en un nodo actualizado.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
unidades
 a| 
Lista de nombres de dispositivos (no identificadores de unidad) para restablecer.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
fuerza
 a| 
Establezca el valor en verdadero para reiniciar la unidad.
 a| 
booleano
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
detalles
 a| 
Detalles de las unidades que se están reiniciando.
 a| 
matriz de objetos JSON

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ResetDrives",
   "params": {
      "drives" : "slot3",
      "force" : true
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
   "details": {
    "drives": [
    {
      "drive": "slot3",
      "returnCode": 0,
      "stderr": " * Unlocking /dev/slot9 .[ ok ]\ * Setting master password /dev/slot9 .[ ok ]\ * Secure erasing /dev/slot9 (hdparm) [tries=0/1] ...........................[ ok ]",
      "stdout": ""
    }
   ]
  },
  "duration": "00:00:28.501269",
  "result": "Passed"
  }
}
----


== Nueva versión

9,6
