---
permalink: api/reference_element_api_snapmirrornode.html 
sidebar: sidebar 
keywords: object,objects,snapMirrorNode 
summary: El objeto snapMirrorNode contiene información sobre los nodos del clúster ONTAP de destino en una relación SnapMirror . 
---
= snapMirrorNode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El objeto snapMirrorNode contiene información sobre los nodos del clúster ONTAP de destino en una relación SnapMirror .



== miembros del objeto

Este objeto contiene los siguientes miembros:

|===
| Nombre | Descripción | Tipo 


 a| 
ID de punto final de SnapMirror
 a| 
El identificador del sistema ONTAP de destino.
 a| 
entero



 a| 
nombre
 a| 
El nombre del nodo ONTAP .
 a| 
cadena



 a| 
modelo
 a| 
Modelo del nodo ONTAP .
 a| 
cadena



 a| 
número de serie
 a| 
El número de serie del nodo ONTAP .
 a| 
cadena



 a| 
Versión del producto
 a| 
La versión del producto ONTAP .
 a| 
cadena



 a| 
¿El nodo está sano?
 a| 
El estado de salud de un nodo en el clúster ONTAP . Valores posibles:

* verdadero
* FALSO

 a| 
cadena



 a| 
esNodoElegible
 a| 
Si el nodo es elegible o no para participar en un clúster ONTAP . Valores posibles:

* verdadero
* FALSO

 a| 
cadena

|===