---
permalink: api/reference_element_api_protectiondomaintolerance.html 
sidebar: sidebar 
keywords: object,objects,protectionDomainTolerance 
summary: El objeto protectionDomainTolerance contiene información sobre la capacidad del clúster de almacenamiento para continuar leyendo y escribiendo datos en caso de una o más fallas dentro de un único dominio de protección de su tipo de dominio de protección asociado. 
---
= protecciónDominioTolerancia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El objeto protectionDomainTolerance contiene información sobre la capacidad del clúster de almacenamiento para continuar leyendo y escribiendo datos en caso de una o más fallas dentro de un único dominio de protección de su tipo de dominio de protección asociado.



== miembros del objeto

Este objeto contiene los siguientes miembros:

|===
| Nombre | Descripción | Tipo 


 a| 
Tolerancias del esquema de protección
 a| 
Una lista de objetos (uno por cada esquema de protección) que contiene información sobre la tolerancia a fallos para el tipo de dominio de protección asociado.
 a| 
xref:reference_element_api_protectionschemetolerance.adoc[Tolerancia del esquema de protección]formación



 a| 
Fracasos sostenibles para el conjunto
 a| 
El número de fallos simultáneos dentro del dominio de protección de tipo asociado que pueden ocurrir sin perder el quórum del conjunto.
 a| 
entero

|===