---
permalink: api/reference_element_api_setconfig.html 
sidebar: sidebar 
keywords: config,configuration,set,setting,node,setconfig,network,cluster 
summary: Puede utilizar el método SetConfig para configurar la información de red y clúster para el nodo.  Este método incluye la misma configuración en un único método API que está disponible utilizando los métodos SetClusterConfig y SetNetworkConfig.  Con este método solo deben incluirse los campos que desee modificar. 
---
= Configurar
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `SetConfig` Método para configurar la información de red y clúster para el nodo.  Este método incluye la misma configuración en un único método de API que está disponible utilizando ambos. `SetClusterConfig` y `SetNetworkConfig` métodos.  Con este método solo deben incluirse los campos que desee modificar.



== Parámetro

PRECAUCIÓN:

Cambiar el modo de enlace en un nodo puede provocar una pérdida temporal de la conectividad de la red.

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
clúster
 a| 
Información del clúster que identifica cómo se comunica el nodo de almacenamiento con el clúster de almacenamiento con el que está asociado.
 a| 
xref:reference_element_api_cluster.adoc[clúster]
 a| 
Ninguno
 a| 
No



 a| 
red
 a| 
Tipos de conexión de red y configuración actual para cada interfaz de red del nodo.
 a| 
xref:reference_element_api_network_all_interfaces.adoc[red (todas las interfaces)]
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
configuración
 a| 
La configuración nueva y actual del nodo.  Este objeto contiene:

* xref:reference_element_api_cluster.adoc[clúster]Información del clúster que identifica cómo se comunica el nodo de almacenamiento con el clúster de almacenamiento con el que está asociado.
* xref:reference_element_api_network_all_interfaces.adoc[red (todas las interfaces)]Tipos de conexión de red y configuración actual para cada interfaz de red del nodo.

 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
	"method": "SetConfig",
	"params": {
		"cluster": {
			"name": "MyHostname"
		},
		"network": {
			"Bond10G": {
				"bond-mode": "ALB"
			}
		}
	}
}
----


== Ejemplo de respuesta

La respuesta de este método es la misma que la que devuelve el método GetConfig.  Cuando se utiliza SetConfig, se pueden ver todos los campos para la visualización del objeto y los valores actualizados.



== Nueva versión

9,6



== Encuentra más información

* xref:reference_element_api_setclusterconfig.adoc[ConfigurarClúster]
* xref:reference_element_api_setnetworkconfig.adoc[Configurar configuración de red]
* xref:reference_element_api_response_example_getconfig.adoc[Obtener configuración]

