---
permalink: api/reference_element_api_liststoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,containers,list,listing,liststoragecontainers 
summary: Puede utilizar el método ListStorageContainers para recuperar información sobre todos los contenedores de almacenamiento de volúmenes virtuales conocidos por el sistema. 
---
= Listar contenedores de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListStorageContainers` Método para recuperar información sobre todos los contenedores de almacenamiento de volúmenes virtuales conocidos por el sistema.



== Parámetros

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
IDs de contenedores de almacenamiento
 a| 
Una lista de identificadores de contenedores de almacenamiento de los que se recuperará información.  Si se omite este parámetro, el método devuelve información sobre todos los contenedores de almacenamiento del sistema.
 a| 
matriz UUID
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
contenedores de almacenamiento
 a| 
Lista de objetos que contienen información sobre todos los contenedores de almacenamiento del sistema.
 a| 
xref:reference_element_api_storagecontainer.adoc[contenedor de almacenamiento]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ListStorageContainers",
   "params": {
      "storageContainerIDs": ["efda8307-b916-4424-979e-658a3f16894d"]
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 6395,
  "result": {
    "storageContainers": [
      {
        "accountID": 64,
        "initiatorSecret": "EJ:08An1MyNQmL!7",
        "name": "VvolContainer",
        "protocolEndpointType": "SCSI",
        "status": "active",
        "storageContainerID": "efda8307-b916-4424-979e-658a3f16894d",
        "targetSecret": "g38}zWBK%206jQr~",
        "virtualVolumes": []
      }
    ]
  }
}
----


== Nueva versión

9,6
