---
permalink: api/reference_element_api_setsnmptrapinfo.html 
sidebar: sidebar 
keywords: snmp,trap,information,info,setting,set,setsnmptrapinfo 
summary: 'Puede utilizar el método SetSnmpTrapInfo para habilitar y deshabilitar la generación de notificaciones SNMP de clúster (traps) y para especificar el conjunto de hosts que reciben las notificaciones.  Los valores que se pasan con cada llamada al método SetSnmpTrapInfo reemplazan todos los valores establecidos en cualquier llamada anterior.' 
---
= SetSnmpTrapInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `SetSnmpTrapInfo` Método para habilitar y deshabilitar la generación de notificaciones SNMP de clúster (traps) y para especificar el conjunto de hosts que reciben las notificaciones.  Los valores que pasas con cada `SetSnmpTrapInfo` La llamada al método reemplaza todos los valores establecidos en cualquier llamada anterior.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo 


 a| 
Receptores de trampas
 a| 
Lista de hosts que recibirán las alertas generadas por el clúster de almacenamiento.  Se requiere al menos un objeto si se habilita cualquiera de los tipos de trampa.  Este parámetro solo es necesario si algún parámetro booleano está configurado como verdadero.  (Sin valor predeterminado.  (No es obligatorio.)
 a| 
xref:reference_element_api_snmptraprecipient.adoc[Destinatario de trampa SNMP]formación



 a| 
clusterFaultTrapsEnabled
 a| 
Si se establece en verdadero, se envía una notificación de fallo de clúster correspondiente a la lista configurada de destinatarios de traps cuando se registra un fallo de clúster.  (Valor predeterminado: falso.  (No es obligatorio.)
 a| 
booleano



 a| 
Trampas de resolución de fallos de clúster habilitadas
 a| 
Si se establece en verdadero, se envía una notificación de resolución de fallo de clúster correspondiente a la lista configurada de destinatarios de traps cuando se resuelve un fallo de clúster.  (Valor predeterminado: falso.  (No es obligatorio.)
 a| 
booleano



 a| 
clusterEventTrapsEnabled
 a| 
Si se establece en verdadero, se envía una notificación de evento de clúster correspondiente a la lista configurada de destinatarios de trampas cuando se registra un evento de clúster.  (Valor predeterminado: falso.  (No es obligatorio.)
 a| 
booleano

|===


== Valores de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
"method":"SetSnmpTrapInfo",
"params":{
    "clusterFaultTrapsEnabled":true,
    "clusterFaultResolvedTrapsEnabled":true,
    "clusterEventTrapsEnabled":true,
    "trapRecipients":[
    {
      "host":"192.30.0.10",
      "port":162,
      "community":"public"
    }
   ]
  },
  "id":1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
    "id" : 1,
    "result" : {}
}
----


== Nueva versión

9,6
