---
permalink: api/reference_element_api_listclusterpairs.html 
sidebar: sidebar 
keywords: cluster,pair,pairs,paired,list,listing,listclusterpairs 
summary: 'Puede utilizar el método ListClusterPairs para listar todos los clústeres que están emparejados con el clúster actual.  Este método devuelve información sobre los emparejamientos de clústeres activos y pendientes, como estadísticas sobre el emparejamiento actual, así como la conectividad y la latencia (en milisegundos) del emparejamiento de clústeres.' 
---
= ListClusterPairs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListClusterPairs` Método para listar todos los clústeres que están emparejados con el clúster actual.  Este método devuelve información sobre los emparejamientos de clústeres activos y pendientes, como estadísticas sobre el emparejamiento actual, así como la conectividad y la latencia (en milisegundos) del emparejamiento de clústeres.



== Parámetro

Este método no tiene parámetros de entrada:



== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
clusterPairs
 a| 
Información sobre cada grupo emparejado.
 a| 
xref:reference_element_api_clusterpair.adoc[clusterPair]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ListClusterPairs",
   "params": {
      },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
 "id": 1,
 "result": {
   "clusterPairs": [
     {
      "clusterName": "cluster2",
      "clusterPairID": 3,
      "clusterPairUUID": "9866fbeb-c2f8-4df3-beb9-58a5c4e49c9b",
      "clusterUUID": 5487,
      "latency": 1,
      "mvip": "172.1.1.5",
      "status": "Connected"
      "version": "8.0.0.1361"
     },
     {
      "clusterName": "cluster3",
      "clusterPairID": 2,
      "clusterPairUUID": "8132a699-ce82-41e0-b406-fb914f976042",
      "clusterUUID": 1383,
      "latency": 1,
      "mvip": "172.1.1.6",
      "status": "Connected"
      "version": "8.0.0.1361"
     }
   ]
 }
----


== Nueva versión

9,6
