---
permalink: api/reference_element_api_clusterconfig.html 
sidebar: sidebar 
keywords: objects,object,clusterConfig 
summary: El objeto clusterConfig devuelve información que el nodo utiliza para comunicarse con el clúster. 
---
= configuración del clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El `clusterConfig` El objeto devuelve información que el nodo utiliza para comunicarse con el clúster.



== miembros del objeto

Este objeto contiene los siguientes miembros:

|===
| Nombre | Descripción | Tipo 


 a| 
`cipi`
 a| 
Interfaz de red utilizada para la comunicación del clúster.
 a| 
cadena



 a| 
`cluster`
 a| 
Nombre único del clúster.
 a| 
cadena



 a| 
`encryptionCapable`
 a| 
Especifica si el nodo admite cifrado.
 a| 
booleano



 a| 
`ensemble`
 a| 
Nodos que participan en el clúster.
 a| 
matriz de cadenas



 a| 
`fipsDriveConfiguration`
 a| 
Especifica si el nodo admite unidades con certificación FIPS 140-2.
 a| 
booleano



 a| 
`hasLocalAdmin`
 a| 
Especifica si el clúster tiene un administrador local.
 a| 
booleano



 a| 
`mipi`
 a| 
Interfaz de red utilizada para la gestión de nodos.
 a| 
cadena



 a| 
`name`
 a| 
Identificador único del clúster.
 a| 
cadena



 a| 
`nodeID`
 a| 
Identificador único del nodo.
 a| 
entero



 a| 
`pendingNodeID`
 a| 
Identificador único para el nodo pendiente.
 a| 
entero



 a| 
`role`
 a| 
Identifica la función del nodo.
 a| 
cadena



 a| 
`sipi`
 a| 
Interfaz de red utilizada para el almacenamiento.
 a| 
cadena



 a| 
`state`
 a| 
Indica el estado del nodo.
 a| 
cadena



 a| 
`version`
 a| 
Indica la versión del nodo.
 a| 
cadena

|===