---
permalink: api/reference_element_api_volume.html 
sidebar: sidebar 
keywords: object,objects,volume 
summary: El objeto de volumen contiene información de configuración sobre volúmenes no emparejados o emparejados.  No incluye información sobre el tiempo de ejecución o el uso, ni contiene información sobre volúmenes virtuales. 
---
= volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El objeto de volumen contiene información de configuración sobre volúmenes no emparejados o emparejados.  No incluye información sobre el tiempo de ejecución o el uso, ni contiene información sobre volúmenes virtuales.



== miembros del objeto

Este objeto contiene los siguientes miembros:

|===
| Nombre | Descripción | Tipo 


 a| 
acceso
 a| 
El tipo de acceso permitido para el volumen. Valores posibles:

* `readOnly`Solo se permiten operaciones de lectura.
* `readWrite`Se permiten lecturas y escrituras.
* `locked`No se permiten lecturas ni escrituras.
* `replicationTarget`: Designado como volumen objetivo en un par de volúmenes replicados.

 a| 
cadena



 a| 
ID de cuenta
 a| 
El ID de la cuenta que contiene el volumen.
 a| 
entero



 a| 
atributos
 a| 
Lista de pares nombre-valor en formato de objeto JSON.
 a| 
Objeto JSON



 a| 
tamaño del bloque
 a| 
El tamaño de los bloques en el volumen.
 a| 
entero



 a| 
crearTiempo
 a| 
Hora de creación del volumen en formato UTC+0.
 a| 
Cadena ISO 8601



 a| 
esquema de protección actual
 a| 
El esquema de protección que se está utilizando para este volumen.  Si un volumen se está convirtiendo de un régimen de protección a otro, este miembro refleja el régimen de protección al que se está convirtiendo el volumen.
 a| 
cadena



 a| 
Tiempo de eliminación
 a| 
Hora en formato UTC+0 en que se eliminó el volumen.
 a| 
Cadena ISO 8601



 a| 
enable512e
 a| 
Si se establece en verdadero, el volumen proporciona emulación de sector de 512 bytes.
 a| 
booleano



 a| 
habilitarSnapMirrorReplication
 a| 
Si el volumen se puede utilizar o no para la replicación con puntos de conexión SnapMirror .
 a| 
booleano



| fifoSize | Especifica el número máximo de instantáneas del volumen que se mantendrán simultáneamente si se utiliza el modo de retención de instantáneas Primero en entrar, primero en salir (FIFO). | entero 


 a| 
iqn
 a| 
El nombre calificado iSCSI del volumen.
 a| 
cadena



 a| 
última hora de acceso
 a| 
La última vez que se produjo algún acceso (incluida la E/S) al volumen (formateado como UTC+0).  Si se desconoce la hora del último acceso, este valor es nulo.
 a| 
Cadena ISO 8601



 a| 
últimoAccesoHoraIO
 a| 
La última vez que se produjo alguna operación de E/S en el volumen (formateada como UTC+0).  Si se desconoce la hora del último acceso, este valor es nulo.
 a| 
Cadena ISO 8601



| tamaño mínimo de Fifo | Especifica el número mínimo de ranuras de instantáneas First-In-First-Out (FIFO) reservadas simultáneamente por el volumen si se utiliza el modo de retención de instantáneas First-In-First-Out (FIFO). | entero 


 a| 
nombre
 a| 
El nombre del volumen tal como se proporcionó en el momento de su creación.
 a| 
cadena



 a| 
esquema de protección anterior
 a| 
Si un volumen se está convirtiendo de un régimen de protección a otro, este miembro refleja el régimen de protección del que se está convirtiendo el volumen.  Este miembro no cambia hasta que se inicia una conversión.  Si un volumen nunca se ha convertido, este miembro es nulo.
 a| 
cadena



 a| 
tiempo de purga
 a| 
Hora en formato UTC+0 en que se eliminó el volumen del sistema.
 a| 
Cadena ISO 8601



 a| 
QoS
 a| 
Configuración de calidad de servicio para este volumen.
 a| 
xref:reference_element_api_qos.adoc[Calidad de servicio]



 a| 
ID de política de qos
 a| 
El ID de la política QoS asociada al volumen.  El valor es nulo si el volumen no está asociado a una póliza.
 a| 
entero



 a| 
scsiEUIDeviceID
 a| 
Identificador de dispositivo SCSI único a nivel mundial para el volumen en formato de 16 bytes basado en EUI-64.
 a| 
cadena



 a| 
scsiNAADeviceID
 a| 
Identificador de dispositivo SCSI único a nivel mundial para el volumen en formato NAA IEEE Registered Extended.
 a| 
cadena



 a| 
sliceCount
 a| 
El número de porciones del volumen.  Este valor siempre es "1".
 a| 
entero



 a| 
estado
 a| 
Estado actual del volumen. Valores posibles:

* init: Un volumen que se está inicializando y no está listo para conexiones.
* activo: Un volumen activo listo para conexiones.
* eliminado: Un volumen que ha sido marcado para su eliminación, pero que aún no se ha purgado.

 a| 
cadena



 a| 
tamaño total
 a| 
El total de bytes de capacidad aprovisionada.
 a| 
entero



 a| 
ID de volumen virtual
 a| 
El identificador único de volumen virtual asociado al volumen, si lo hubiera.
 a| 
UUID



 a| 
grupos de acceso de volumen
 a| 
Lista de identificadores de los grupos de acceso a volúmenes a los que pertenece un volumen.  Este valor es una lista vacía si un volumen no pertenece a ningún grupo de acceso a volúmenes.
 a| 
matriz de enteros



 a| 
UUID del grupo de consistencia de volumen
 a| 
El identificador único universal del grupo de consistencia de volumen al que pertenece el volumen.
 a| 
UUID



 a| 
ID de volumen
 a| 
El ID de volumen único para el volumen.
 a| 
entero



 a| 
volúmenesPares
 a| 
Información sobre un volumen emparejado.  Solo visible si hay un volumen emparejado.  Este valor es una lista vacía si el volumen no está emparejado.
 a| 
xref:reference_element_api_volumepair.adoc[volumenPar]formación



 a| 
UUID del volumen
 a| 
El identificador único universal del volumen.
 a| 
UUID

|===


== Encuentra más información

* xref:reference_element_api_listactivevolumes.adoc[Listar volúmenes activos]
* xref:reference_element_api_listdeletedvolumes.adoc[Lista de volúmenes eliminados]
* xref:reference_element_api_listvolumes.adoc[Lista de volúmenes]
* xref:reference_element_api_listvolumesforaccount.adoc[Listar volúmenes para la cuenta]
* xref:reference_element_api_qos.adoc[Calidad de servicio]

