---
permalink: api/reference_element_api_quiescesnapmirrorrelationship.html 
sidebar: sidebar 
keywords: snapmirror,relationship,relationships,quiesce,quiescing,quiescescnapmirrorrelationship 
summary: 'La interfaz web del software Element utiliza el método QuiesceSnapMirrorRelationship para deshabilitar futuras transferencias de datos para una relación SnapMirror .  Si hay una transferencia en curso, el estado de la relación pasa a ser "en pausa" hasta que se complete la transferencia.  Si se interrumpe la transferencia actual, no se reiniciará.  Puede volver a habilitar las transferencias de datos para la relación utilizando el método API ResumeSnapMirrorRelationship.' 
---
= Relación de espejo de QuiesceSnap
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz web del software Element utiliza `QuiesceSnapMirrorRelationship` Método para deshabilitar futuras transferencias de datos para una relación SnapMirror .  Si hay una transferencia en curso, el estado de la relación pasa a ser "en pausa" hasta que se complete la transferencia.  Si se interrumpe la transferencia actual, no se reiniciará.  Puede volver a habilitar las transferencias de datos para la relación utilizando `ResumeSnapMirrorRelationship` Método API.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de punto final de SnapMirror
 a| 
El ID del punto final del sistema de almacenamiento ONTAP remoto que se comunica con el clúster de almacenamiento Element.
 a| 
entero
 a| 
Ninguno
 a| 
Sí



 a| 
volumen de destino
 a| 
El volumen de destino en la relación SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
snapMirrorRelationship
 a| 
Un objeto que contiene información sobre la relación SnapMirror quiescente.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== Nueva versión

10,1
