---
permalink: api/reference_element_api_listbackuptargets.html 
sidebar: sidebar 
keywords: backup,target,targets,info,list,listing,listbackuptargets 
summary: Puede utilizar el método ListBackupTargets para obtener información sobre todos los destinos de copia de seguridad que se han creado. 
---
= ListBackupTargets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListBackupTargets` Método para obtener información sobre todos los destinos de copia de seguridad que se han creado.



== Parámetros

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
destinos de respaldo
 a| 
Objetos devueltos para cada destino de copia de seguridad.  Objetos incluidos:

* atributos: Lista de pares nombre-valor en formato de objeto JSON.  (Objeto JSON)
* backupTargetID: Identificador único asignado al destino de la copia de seguridad.  (entero)
* nombre: Nombre del destino de la copia de seguridad.  (cadena)

 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ListBackupTargets",
   "params": {},
   "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id": 1,
   "result": {
     "backupTargets": [
       {
        "attributes" : {},
        "backupTargetID" : 1,
        "name" : "mytargetbackup"
       }
    ]
  }
}
----


== Nueva versión

9,6
