---
permalink: api/reference_element_api_setdefaultqos.html 
sidebar: sidebar 
keywords: qos,value,configure,configuring,default,set,setting,setdefaultqos 
summary: 'Puede utilizar el método SetDefaultQoS para configurar los valores predeterminados de Calidad de Servicio (QoS) (medidos en entradas y salidas por segundo, o IOPS) para un volumen.' 
---
= Establecer QoS predeterminado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `SetDefaultQoS` método para configurar los valores predeterminados de Calidad de Servicio (QoS) (medidos en entradas y salidas por segundo, o IOPS) para un volumen.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
minIOPS
 a| 
El número mínimo de IOPS sostenidas que el clúster proporciona a un volumen.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
IOPS máximas
 a| 
El número máximo de IOPS sostenidas que el clúster proporciona a un volumen.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
ráfaga IOPS
 a| 
La cantidad máxima de IOPS permitida en un escenario de ráfaga corta.
 a| 
entero
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
minIOPS
 a| 
El número mínimo de IOPS sostenidas que el clúster proporciona a un volumen.
 a| 
entero



 a| 
IOPS máximas
 a| 
El número máximo de IOPS sostenidas que el clúster proporciona a un volumen.
 a| 
entero



 a| 
ráfaga IOPS
 a| 
La cantidad máxima de IOPS permitida en un escenario de ráfaga corta.
 a| 
entero

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "SetDefaultQoS",
    "params": {
        "burstIOPS":8000,
        "maxIOPS":1000,
        "minIOPS":200
    },
    "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
    "id":1,
    "result": {
        "burstIOPS":8000,
        "maxIOPS":1000,
        "minIOPS":200
    ​}
}
----


== Nueva versión

9,6
