---
permalink: api/reference_element_api_addkeyservertoproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,assigning to key provider,assign,addkeyservertoproviderkmip 
summary: 'Puede utilizar el método AddKeyServerToProviderKmip para asignar un servidor de claves del Protocolo de interoperabilidad de gestión de claves (KMIP) al proveedor de claves especificado.  Durante la asignación, se contacta con el servidor para verificar su funcionalidad.  Si el servidor de claves especificado ya está asignado al proveedor de claves especificado, no se realiza ninguna acción y no se devuelve ningún error.  Puede eliminar la asignación utilizando el método RemoveKeyServerFromProviderKmip.' 
---
= Agregar servidor de claves al proveedor Kmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `AddKeyServerToProviderKmip` método para asignar un servidor de claves del Protocolo de Interoperabilidad de Gestión de Claves (KMIP) al proveedor de claves especificado.  Durante la asignación, se contacta con el servidor para verificar su funcionalidad.  Si el servidor de claves especificado ya está asignado al proveedor de claves especificado, no se realiza ninguna acción y no se devuelve ningún error.  Puedes eliminar la asignación usando el `RemoveKeyServerFromProviderKmip` método.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID del proveedor de clave
 a| 
El ID del proveedor de claves al que se asignará el servidor de claves.
 a| 
entero
 a| 
Ninguno
 a| 
Sí



 a| 
ID del servidor de claves
 a| 
El ID del servidor de claves a asignar.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método no devuelve ningún valor.  La tarea se considera exitosa siempre y cuando no se devuelva ningún error.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "AddKeyServerToProviderKmip",
  "params": {
    "keyProviderID": 1,
    "keyServerID": 15
    },
"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
}
----


== Nueva versión

11,7
