---
permalink: api/reference_element_api_listdrives.html 
sidebar: sidebar 
keywords: drives,drive,list,listing,listdrives,cluster 
summary: Puede utilizar el método ListDrives para enumerar las unidades que existen en los nodos activos del clúster.  Este método devuelve las unidades que se han agregado como metadatos de volumen o unidades de bloque, así como las unidades que no se han agregado y están disponibles. 
---
= ListDrives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListDrives` Método para listar las unidades que existen en los nodos activos del clúster.  Este método devuelve las unidades que se han agregado como metadatos de volumen o unidades de bloque, así como las unidades que no se han agregado y están disponibles.



== Parámetros

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
unidades
 a| 
Lista de unidades en el clúster.
 a| 
xref:reference_element_api_drive.adoc[conducir]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ListDrives",
   "params": {},
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id" : 1,
   "result" : {
     "drives" : [
       {
         "attributes" : {},
         "capacity" : 299917139968,
         "driveID" : 35,
         "nodeID" : 5,
         "serial" : "scsi-SATA_INTEL_SSDSA2CW6CVPR141502R3600FGN-part2",
         "slot" : 0,
         "status" : "active",
         "type" : "volume"
       },
       {
         "attributes" : {},
         "capacity" : 600127266816,
         "driveID" : 36,
         "nodeID" : 5,
         "serial" : "scsi-SATA_INTEL_SSDSA2CW6CVPR1415037R600FGN",
         "slot" : 6,
         "status" : "active",
         "type" : "block"
       }
     }
   ]
}
----


== Nueva versión

9,6
