---
permalink: api/reference_element_api_getdriveconfig.html 
sidebar: sidebar 
keywords: drive,config,configuration,get,getting,getdriveconfig 
summary: Puede utilizar el método GetDriveConfig para obtener información sobre las unidades, incluyendo el número esperado de unidades de segmento y de bloque, así como la cantidad de unidades de segmento y de bloque que están actualmente conectadas al nodo. 
---
= Obtener configuración de la unidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetDriveConfig` Método para obtener información de la unidad para los recuentos esperados de unidades de segmento y bloque, así como el número de unidades de segmento y bloque que están actualmente conectadas al nodo.



== Parámetros

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
Configuración de la unidad
 a| 
Información sobre las unidades conectadas al nodo.
 a| 
xref:reference_element_api_drive.adoc[conducir]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "GetDriveConfig",
   "params": {},
   "id" : 1
}
----


== Ejemplo de respuesta

Las respuestas para este método son similares al siguiente ejemplo.  Debido a su longitud, la respuesta contiene información solo para una unidad de un nodo de almacenamiento.

[listing]
----
{
	"id": 1,
	"result": {
			"driveConfig": {
					"drives": [
						{
							"canonicalName": "sda",
							"connected": true,
							"dev": 2052,
							"devPath": "/dev/sdimm0p4",
							"driveType": "Slice",
							"name": "scsi-SATA_VRFSD3400GNCVMT205581853-part4",
							"path": "/dev/sda4",
							"pathLink": "/dev/sdimm0p4",
							"product": "VRFSD3400GNCVMTKS1",
							"scsiCompatId": "scsi-SATA_VRFSD3400GNCVMT205581853-part4",
							"scsiState": "Running",
							"securityAtMaximum": false,
							"securityEnabled": false,
							"securityFrozen": true,
							"securityLocked": false,
							"securitySupported": true,
							"serial": "205581853",
							"size": 299988156416,
							"slot": -1,
							"uuid": "9d4b198b-5ff9-4f7c-04fc-3bc4e2f38974",
							"vendor": "Viking",
							"version": "612ABBF0"
						}
					],
					"numBlockActual": 10,
					"numBlockExpected": 10,
					"numSliceActual": 1,
					"numSliceExpected": 1,
					"numTotalActual": 11,
					"numTotalExpected": 11
			}
	}
}
----