---
permalink: api/reference_element_api_getclustercapacity.html 
sidebar: sidebar 
keywords: cluster,capacity,getting,get,measurements,measure,deduplication,GetClusterCapacity 
summary: Puede utilizar GetClusterCapacity para obtener mediciones de capacidad de alto nivel para un clúster de almacenamiento completo.  Este método devuelve campos que puede utilizar para calcular los índices de eficiencia que se muestran en la interfaz web de Element.  Puedes utilizar los cálculos de eficiencia en scripts para obtener los índices de eficiencia para el aprovisionamiento ligero, la deduplicación, la compresión y la eficiencia general. 
---
= Obtener capacidad del clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetClusterCapacity` para devolver mediciones de capacidad de alto nivel para todo un clúster de almacenamiento.  Este método devuelve campos que puede utilizar para calcular los índices de eficiencia que se muestran en la interfaz web de Element.  Puedes utilizar los cálculos de eficiencia en scripts para obtener los índices de eficiencia para el aprovisionamiento ligero, la deduplicación, la compresión y la eficiencia general.



== Cálculos de eficiencia

Utilice las siguientes ecuaciones para calcular el aprovisionamiento ligero, la deduplicación y la compresión.  Estas ecuaciones se aplican al Elemento 8.2 y posteriores.

* Factor de aprovisionamiento delgado = (bloques no nulos + bloques nulos) / bloques no nulos
* Factor de deduplicación = (bloquesnoceros + bloquesnocerosinstantáneos) / bloquesúnicos
* Factor de compresión = (bloques únicos * 4096) / (espacio usado de bloques únicos * 0,93)




== Cálculo de la tasa de eficiencia global

Utilice la siguiente ecuación para calcular la eficiencia general del clúster utilizando los resultados de los cálculos de eficiencia de aprovisionamiento ligero, deduplicación y compresión.

* Factor de eficiencia = Factor de aprovisionamiento ligero * Factor de deduplicación * Factor de compresión




== Parámetros

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
capacidad del clúster
 a| 
Medidas de capacidad del clúster de almacenamiento.
 a| 
xref:reference_element_api_clustercapacity.adoc[capacidad del clúster]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "GetClusterCapacity",
   "params": {},
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "clusterCapacity": {
      "activeBlockSpace": 236015557096,
      "activeSessions": 20,
      "averageIOPS": 0,
      "clusterRecentIOSize": 0,
      "currentIOPS": 0,
      "maxIOPS": 150000,
      "maxOverProvisionableSpace": 259189767127040,
      "maxProvisionedSpace": 51837953425408,
      "maxUsedMetadataSpace": 404984011161,
      "maxUsedSpace": 12002762096640,
      "nonZeroBlocks": 310080350,
      "peakActiveSessions": 20,
      "peakIOPS": 0,
      "provisionedSpace": 1357931085824,
      "snapshotNonZeroBlocks": 0,
      "timestamp": "2016-10-17T21:24:36Z",
      "totalOps": 1027407650,
      "uniqueBlocks": 108180156,
      "uniqueBlocksUsedSpace": 244572686901,
      "usedMetadataSpace": 8745762816,
      "usedMetadataSpaceInSnapshots": 8745762816,
      "usedSpace": 244572686901,
      "zeroBlocks": 352971938
    }
  }
}
----


== Nueva versión

9,6
