---
permalink: api/reference_element_api_modifyvolumepair.html 
sidebar: sidebar 
keywords: volume,pair,pairs,modify,modifying,edit,editing,changing,change,modifyvolumepair,paired 
summary: 'Puede utilizar el método ModifyVolumePair para pausar o reiniciar la replicación entre un par de volúmenes.  Este método se configura en el volumen de origen (el volumen con acceso de lectura/escritura).' 
---
= Modificar par de volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ModifyVolumePair` Método para pausar o reiniciar la replicación entre un par de volúmenes.  Este método se configura en el volumen de origen (el volumen con acceso de lectura/escritura).



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===


| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de volumen
 a| 
Número de identificación del volumen que se va a modificar.
 a| 
entero
 a| 
Ninguno
 a| 
Sí



 a| 
pausa manual
 a| 
La replicación remota se puede pausar o reiniciar en el volumen de origen (lectura/escritura). Valores posibles:

* verdadero: Pausar la replicación de volumen.
* Falso: Reiniciar la replicación de volumen.


Si no se especifica ningún valor, no se realiza ningún cambio en la replicación.
 a| 
booleano
 a| 
Ninguno
 a| 
No



 a| 
modo
 a| 
Modo de replicación de volumen. Valores posibles:

* Asíncrono: Las escrituras se confirman cuando se completan localmente.  El clúster no espera a que las escrituras se repliquen en el clúster de destino.
* Sincronización: La fuente confirma la escritura cuando los datos se almacenan localmente y en el clúster remoto.
* Solo instantáneas: Solo se replican las instantáneas creadas en el clúster de origen.  Las escrituras activas desde el volumen de origen no se replican.

 a| 
cadena
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "ModifyVolumePair",
  "params": {
    "pausedManual": false,
    "volumeID": 5,
    "mode": "sync"
   },
  "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id" : 1,
   "result" : {}
}
----


== Nueva versión

9,6
