---
permalink: api/reference_element_api_testping.html 
sidebar: sidebar 
keywords: ping,test,TestPing 
summary: Puede utilizar el método TestPing para probar la conectividad de red a todos los nodos del clúster en interfaces de 1G y 10G utilizando paquetes ICMP.  La prueba utiliza los tamaños MTU apropiados para cada paquete según la configuración MTU en la configuración de red.  TestPing no crea una interfaz VLAN temporal. 
---
= Prueba de ping
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `TestPing` Método para probar la conectividad de red a todos los nodos del clúster en interfaces de 1G y 10G utilizando paquetes ICMP.  La prueba utiliza los tamaños MTU apropiados para cada paquete según la configuración MTU en la configuración de red. `TestPing` No crea una interfaz VLAN temporal.



== Parámetros

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
intentos
 a| 
Especifica el número de veces que el sistema debe repetir el ping de prueba.
 a| 
entero
 a| 
5
 a| 
No



 a| 
hosts
 a| 
Especifica una lista de direcciones o nombres de host de dispositivos a los que hacer ping, separados por comas.  Si no se especifican hosts, el método realiza un ping a los hosts del clúster de almacenamiento.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
interfaz
 a| 
La interfaz existente (base) desde la cual se deben enviar los pings. Valores posibles:

* `Bond10G`Enviar pings desde la interfaz Bond10G.
* `Bond1G`Enviar pings desde la interfaz Bond1G.

 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
tamaño del paquete
 a| 
Especifica el número de bytes que se enviarán en el paquete ICMP que se envía a cada IP.  El número de bytes debe ser inferior al MTU máximo especificado en la configuración de red.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
Tiempo de espera de ping (milisegundos)
 a| 
Especifica el número de milisegundos que se deben esperar para cada respuesta de ping individual.
 a| 
entero
 a| 
500 milisegundos
 a| 
No



 a| 
prohibir la fragmentación
 a| 
Habilita la bandera DF (No Fragmentar) para los paquetes ICMP.
 a| 
booleano
 a| 
FALSO
 a| 
No



 a| 
sourceAddressV4
 a| 
La dirección IPv4 de origen que se utilizará en los paquetes ping ICMP.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
sourceAddressV6
 a| 
La dirección IPv6 de origen que se utilizará en los paquetes ping ICMP.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
tiempo de espera total en segundos
 a| 
Especifica el tiempo en segundos que el ping debe esperar una respuesta del sistema antes de realizar el siguiente intento de ping o finalizar el proceso.
 a| 
entero
 a| 
5
 a| 
No



 a| 
etiqueta de red virtual
 a| 
El ID de VLAN que se utilizará al enviar los paquetes ping.
 a| 
entero
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
detalles
 a| 
Lista de cada IP con la que el nodo pudo comunicarse y estadísticas de respuesta de ping.
 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
    "method": "TestPing",
    "params": {
        "interface": "Bond1G",
        "hosts": "192.168.0.1"
    },
    "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "192.168.0.1": {
        "individualResponseCodes": [
          "Success",
          "Success",
          "Success",
          "Success",
          "Success"
        ],
        "individualResponseTimes": [
          "00:00:00.000304",
          "00:00:00.000123",
          "00:00:00.000116",
          "00:00:00.000113",
          "00:00:00.000111"
        ],
        "individualStatus": [
          true,
          true,
          true,
          true,
          true
        ],
        "interface": "Bond1G",
        "responseTime": "00:00:00.000154",
        "sourceAddressV4": "192.168.0.5",
        "successful": true
      }
    },
    "duration": "00:00:00.001747",
    "result": "Passed"
  }
}
----


== Nueva versión

5,0
