---
permalink: api/reference_element_api_addldapclusteradmin.html 
sidebar: sidebar 
keywords: LDAP,cluster,admin,add,adding,addldapclusteradmin 
summary: Puede utilizar AddLdapClusterAdmin para agregar un nuevo usuario administrador de clúster LDAP.  Un administrador de clúster LDAP puede gestionar el clúster utilizando la API y las herramientas de gestión.  Las cuentas de administrador del clúster LDAP son completamente independientes y no guardan relación con las cuentas de inquilino estándar. 
---
= Agregar administrador de clúster Ldap
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `AddLdapClusterAdmin` para agregar un nuevo usuario administrador de clúster LDAP.  Un administrador de clúster LDAP puede gestionar el clúster utilizando la API y las herramientas de gestión.  Las cuentas de administrador del clúster LDAP son completamente independientes y no guardan relación con las cuentas de inquilino estándar.



== Parámetros

También puede utilizar este método para agregar un grupo LDAP que se haya definido en Active Directory®.  El nivel de acceso que se otorga al grupo se transmite a los usuarios individuales del grupo LDAP.

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
acceso
 a| 
Controla qué métodos puede usar este administrador de clúster.
 a| 
matriz de cadenas
 a| 
Ninguno
 a| 
Sí



 a| 
aceptar el EULA
 a| 
Acepte el Acuerdo de Licencia de Usuario Final.  Establézcalo en verdadero para agregar una cuenta de administrador de clúster al sistema.  Si se omite o se establece en falso, la llamada al método falla.
 a| 
booleano
 a| 
Ninguno
 a| 
Sí



 a| 
atributos
 a| 
Lista de pares nombre-valor en formato de objeto JSON.
 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No



 a| 
nombre de usuario
 a| 
Nombre de usuario distinguido para el nuevo administrador del clúster LDAP.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "AddLdapClusterAdmin",
  "params": {"username":"cn=mike jones,ou=ptusers,dc=prodtest,dc=solidfire,dc=net",
    "access": ["administrator", "read"
    ]
  },
"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
 "id": 1,
 "result": {}
}
----


== Nueva versión

9,6



== Encuentra más información

xref:reference_element_api_app_b_access_control.adoc[Control de acceso]
