---
permalink: api/reference_element_api_listsnapshots.html 
sidebar: sidebar 
keywords: snapshot,snapshots,list,listing,attributes,listsnapshots 
summary: Puede utilizar ListSnapshots para obtener los atributos de cada instantánea tomada en el volumen. 
---
= Instantáneas de la lista
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar `ListSnapshots` para devolver los atributos de cada instantánea tomada en el volumen.

La información sobre las instantáneas que residen en el clúster de destino se mostrará en el clúster de origen cuando se llame a este método desde el clúster de origen.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de volumen
 a| 
Recupera instantáneas de un volumen.  Si no se proporciona volumeID, se devuelven todas las instantáneas de todos los volúmenes.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
ID de instantánea
 a| 
Recupera información para un ID de instantánea individual.
 a| 
entero
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
instantáneas
 a| 
Información sobre cada instantánea para cada volumen.  Si no se proporciona volumeID, se devuelven todas las instantáneas de todos los volúmenes.  Las instantáneas que se encuentran en un grupo se devuelven con un ID de grupo.
 a| 
xref:reference_element_api_snapshot.adoc[instantánea]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ListSnapshots",
   "params": {
             "volumeID": "1"
       },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "snapshots": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2015-05-08T13:15:00Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2015-05-08T21:15:00Z",
          "groupID": 0,
          "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
          "name": "Hourly",
          "remoteStatuses": [
              {
                "remoteStatus": "Present",
                "volumePairUUID": "237e1cf9-fb4a-49de-a089-a6a9a1f0361e"
              }
         ],
          "snapshotID": 572,
          "snapshotUUID": "efa98e40-cb36-4c20-a090-a36c48296c14",
          "status": "done",
          "totalSize": 10000269312,
          "volumeID": 1
        }
      ]
    }
  }
----


== Nueva versión

9,6
