---
permalink: api/reference_element_api_listvirtualnetworks.html 
sidebar: sidebar 
keywords: virtual,network,networks,listing,list,listvirtualnetworks 
summary: Puede utilizar el método ListVirtualNetworks para listar todas las redes virtuales configuradas para el clúster. 
---
= Lista de redes virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListVirtualNetworks` Método para listar todas las redes virtuales configuradas para el clúster.

Puede utilizar este método para verificar la configuración de la red virtual en el clúster.  Este método no requiere parámetros.  Sin embargo, para filtrar los resultados, puede pasar uno o más valores de virtualNetworkID o virtualNetworkTag.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de red virtual
 a| 
ID de red para filtrar la lista por una única red virtual.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
etiqueta de red virtual
 a| 
Etiqueta de red para filtrar la lista por una única red virtual.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
IDs de red virtuales
 a| 
Identificadores de red para incluir en la lista.
 a| 
matriz de enteros
 a| 
Ninguno
 a| 
No



 a| 
Etiquetas de red virtuales
 a| 
Etiqueta de red para incluir en la lista.
 a| 
matriz de enteros
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
redes virtuales
 a| 
Objeto que contiene direcciones IP de red virtual.
 a| 
xref:reference_element_api_virtualnetwork.adoc[red virtual]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "ListVirtualNetworks",
  "params": {
     "virtualNetworkIDs": [5,6]
   },
"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "virtualNetworks": [
   {
    "addressBlocks": [
   {
    "available": "11000000",
    "size": 8,
    "start": "10.26.250.207"
   }
 ],
    "attributes": null,
    "gateway": "10.26.250.254",
    "name": "2250",
    "namespace": false,
    "netmask": "255.255.255.0",
    "svip": "10.26.250.200",
    "virtualNetworkID": 2250
   },
   {
     "addressBlocks": [
   {
     "available": "11000000",
     "size": 8,
     "start": "10.26.241.207"
   }
  ],
     "attributes": null,
     "gateway": "10.26.241.254",
     "name": "2241",
     "namespace": false,
     "netmask": "255.255.255.0",
     "svip": "10.26.241.200",
     "virtualNetworkID": 2241
   },
  {
     "addressBlocks": [
  {
     "available": "11000000",
     "size": 8,
     "start": "10.26.240.207"
   }
  ],
     "attributes": null,
     "gateway": "10.26.240.254",
     "name": "2240",
     "namespace": false,
     "netmask": "255.255.255.0",
     "svip": "10.26.240.200",
     "virtualNetworkID": 2240
    },
   {
  }
 ]
}
----


== Nueva versión

9,6
