---
permalink: api/reference_element_api_disablebmccoldreset.html 
sidebar: sidebar 
keywords: BMC cold reset,BMC reset,disable BMC 
summary: 'Puede utilizar el método DisableBmcColdReset para deshabilitar la tarea en segundo plano que reinicia periódicamente el controlador de administración de la placa base (BMC) para todos los nodos del clúster.' 
---
= DeshabilitarBmcColdReset
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `DisableBmcColdReset` Método para deshabilitar la tarea en segundo plano que reinicia periódicamente el controlador de administración de la placa base (BMC) para todos los nodos del clúster.



== Parámetro

Este método no tiene parámetros de entrada.



== Valores de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
cBmcResetDurationMinutes
 a| 
Devuelve el tiempo transcurrido entre los intervalos de reinicio.  El intervalo siempre debe ser 0 después de que se complete el comando.
 a| 
entero

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "DisableBmcColdReset",
  "params": {},
  "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
    "id": 1,
    "result": {
        "cBmcResetDurationMinutes": 0
    }
}
----


== Nueva versión

12,0
