---
permalink: api/reference_element_api_listvirtualvolumes.html 
sidebar: sidebar 
keywords: virtual,volume,volumes,vvol,list,listing,listvirtualvolumes 
summary: Puede utilizar el método ListVirtualVolumes para listar los volúmenes virtuales que se encuentran actualmente en el sistema.  Puede utilizar este método para listar todos los volúmenes virtuales, o solo un subconjunto. 
---
= Listar volúmenes virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListVirtualVolumes` Método para listar los volúmenes virtuales que se encuentran actualmente en el sistema.  Puede utilizar este método para listar todos los volúmenes virtuales, o solo un subconjunto.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
detalles
 a| 
El nivel de detalle en la respuesta. Valores posibles:

* Verdadero: Incluya más detalles sobre cada VVol en la respuesta.
* Falso: Incluya el nivel de detalle estándar sobre cada VVol en la respuesta.

 a| 
booleano
 a| 
FALSO
 a| 
No



 a| 
límite
 a| 
Número máximo de volúmenes virtuales a listar.
 a| 
entero
 a| 
10000
 a| 
No



 a| 
recursivo
 a| 
Especifica si se debe incluir o no información sobre los hijos de cada VVol en la respuesta. Valores posibles:

* Verdadero: Incluya información sobre los hijos de cada VVol en la respuesta.
* Falso: No incluya información sobre los hijos de cada VVol en la respuesta.

 a| 
booleano
 a| 
FALSO
 a| 
No



 a| 
startVirtualVolumeID
 a| 
El ID del volumen virtual en el que se debe comenzar la lista en la respuesta.
 a| 
Tipo UUID
 a| 
Ninguno
 a| 
No



 a| 
IDs de volumen virtual
 a| 
Una lista de identificadores de volúmenes virtuales de los que se desea recuperar información.  Si omite este parámetro, el método devuelve información únicamente sobre estos volúmenes virtuales.
 a| 
matriz UUID de virtualVolumeID
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
nextVirtualVolumeID
 a| 
El identificador del siguiente volumen virtual en la lista.
 a| 
UUID



 a| 
volúmenes virtuales
 a| 
Una lista de objetos que describe los volúmenes virtuales que se encuentran actualmente en el sistema.
 a| 
xref:reference_element_api_virtualvolume.adoc[volumen virtual]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "ListVirtualVolumes",
    "params": {
    },
    "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "nextVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
    "virtualVolumes": [
      {
        "bindings": [
          177
        ],
        "children": [],
        "metadata": {
          "SFProfileId": "f4e5bade-15a2-4805-bf8e-52318c4ce443",
          "SFgenerationId": "0",
          "VMW_ContainerId": "abaab415-bedc-44cd-98b8-f37495884db0",
          "VMW_VVolName": "asdf",
          "VMW_VVolType": "Config",
          "VMW_VmID": "502e0676-e510-ccdd-394c-667f6867fcdf",
          "VMW_VvolProfile": "f4e5bade-15a2-4805-bf8e-52318c4ce443:0"
        },
        "parentVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
        "snapshotID": 0,
        "snapshotInfo": null,
        "status": "done",
        "storageContainer": {
          "accountID": 1,
          "initiatorSecret": "B5)D1y10K)8IDN58",
          "name": "test",
          "protocolEndpointType": "SCSI",
          "status": "active",
          "storageContainerID": "abaab415-bedc-44cd-98b8-f37495884db0",
          "targetSecret": "qgae@{o{~8\"2U)U^"
        },
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeType": "config",
        "volumeID": 166,
        "volumeInfo": null
      }
    ]
  }
}
----


== Nueva versión

9,6
