---
permalink: api/reference_element_api_setloginbanner.html 
sidebar: sidebar 
keywords: terms,use,banner,configure,set,setting,setloginbanner,login 
summary: Puede utilizar el método SetLoginBanner para configurar el banner de Términos de uso que los usuarios ven cuando inician sesión en la interfaz web de Element. 
---
= Establecer banner de inicio de sesión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `SetLoginBanner` Método para configurar el banner de Términos de uso que los usuarios ven cuando inician sesión en la interfaz web de Element.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
bandera
 a| 
El texto deseado para el banner de Términos de Uso.  La longitud máxima permitida es de 4.096 caracteres.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
activado
 a| 
Estado del banner de Condiciones de uso. Valores posibles:

* `true`El banner de Condiciones de uso se muestra al iniciar sesión en la interfaz web.
* `false`El banner de Condiciones de uso no se muestra al iniciar sesión en la interfaz web.

 a| 
booleano
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
bandera
 a| 
Texto actual del banner de Condiciones de uso.  Este valor puede contener texto incluso cuando el banner esté desactivado.
 a| 
cadena



 a| 
activado
 a| 
Estado del banner de Condiciones de uso. Valores posibles:

* Verdadero: El banner de Términos de uso se muestra al iniciar sesión en la interfaz web.
* Falso: El banner de Condiciones de uso no se muestra al iniciar sesión en la interfaz web.

 a| 
booleano

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "id": 3920,
  "method": "SetLoginBanner",
  "params": {
    "banner": "Welcome to NetApp!",
    "enabled": true
  }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 3920,
  "result": {
    "loginBanner": {
      "banner": "Welcome to NetApp!",
      "enabled": true
    }
  }
}
----


== Nueva versión

10,0
