---
permalink: api/reference_element_api_purgedeletedvolume.html 
sidebar: sidebar 
keywords: volume,volumes,purging,purge,deleted,purgedeletedvolume 
summary: Puede utilizar el método PurgeDeletedVolume para eliminar de forma inmediata y permanente un volumen que ha sido eliminado.  Debe eliminar un volumen mediante DeleteVolume antes de que pueda ser purgado. 
---
= Purga de volumen eliminado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `PurgeDeletedVolume` Método para eliminar de forma inmediata y permanente un volumen que ha sido borrado.  Debes eliminar un volumen usando `DeleteVolume` antes de que pueda ser purgado.

Los volúmenes se purgan automáticamente después de un período de tiempo, por lo que el uso de este método no suele ser necesario.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


| ID de volumen | El ID del volumen que se va a purgar. | entero | No | Sí 
|===


== Valores de retorno

Este método no devuelve ningún valor.



== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "PurgeDeletedVolume",
   "params": {
      "volumeID"  : 5
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id" : 1,
  "result": {}
}
----


== Nueva versión

9,6



== Encuentra más información

xref:reference_element_api_deletevolume.adoc[Eliminar volumen]
