---
permalink: api/reference_element_api_listsyncjobs.html 
sidebar: sidebar 
keywords: sync,synchronization,job,jobs,list,get,listing,getting,listsyncjobs 
summary: Puede utilizar el método ListSyncJobs para obtener información sobre los trabajos de sincronización que se están ejecutando en un clúster de almacenamiento de Element.  Este método devuelve información sobre trabajos de segmentación, clonación, bloqueo y sincronización remota. 
---
= ListSyncJobs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListSyncJobs` Método para obtener información sobre los trabajos de sincronización que se están ejecutando en un clúster de almacenamiento Element.  Este método devuelve información sobre trabajos de segmentación, clonación, bloqueo y sincronización remota.



== Parámetros

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
sincronizar trabajos
 a| 
Lista de objetos que describen los procesos de sincronización que se están ejecutando actualmente en el sistema.
 a| 
xref:reference_element_api_syncjob.adoc[trabajo de sincronización]formación

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "ListSyncJobs",
   "params": { },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
    "id":1,
    "result":{
      "syncJobs":[
        {
           "bytesPerSecond":275314.8834458956,
           "currentBytes":178257920,
           "dstServiceID":36,
           "elapsedTime":289.4568382049871,
           "percentComplete":8.900523560209423,
           "remainingTime":2962.675921065957,
           "sliceID":5,
           "srcServiceID":16,
           "stage":"whole",
           "totalBytes":2002780160,
           "type":"slice"
       },
       {
           "bytesPerSecond":305461.3198607744,
           "cloneID":1,
           "currentBytes":81788928,
           "dstServiceID":16,
           "dstVolumeID":6,
           "elapsedTime":291.7847648200743,
           "nodeID":1,
           "percentComplete":8.167539267015707,
           "remainingTime":3280.708270981153,
           "sliceID":6,
           "srcServiceID":16,
           "srcVolumeID":5,
           "stage":"whole",
           "totalBytes":1001390080,
           "type":"clone"
        },
        {
           "blocksPerSecond":0,
           "branchType": "snapshot",
           "dstServiceID":8,
           "dstVolumeID":2,
           "elapsedTime":0,
           "percentComplete":0,
           "remainingTime":0,
           "sliceID":2,
           "stage":"metadata",
           "type":"remote"
       }
     ]
   }
}
----


== Nueva versión

9,6
