---
permalink: api/reference_element_api_removeinitiatorsfromvolumeaccessgroup.html 
sidebar: sidebar 
keywords: initiators,initiator,volume,access,group,remove,removing,removeinitiatorsfromvolumeaccessgroup 
summary: Puede utilizar el método RemoveInitiatorsFromVolumeAccessGroup para eliminar iniciadores de un grupo de acceso a volumen específico. 
---
= EliminarIniciadoresDelGrupoDeAccesoPorVolumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `RemoveInitiatorsFromVolumeAccessGroup` Método para eliminar iniciadores de un grupo de acceso a volumen específico.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de grupo de acceso al volumen
 a| 
El ID del grupo de acceso al volumen del que se eliminan los iniciadores.
 a| 
entero
 a| 
Ninguno
 a| 
Sí



 a| 
iniciadores
 a| 
Lista de identificadores o nombres de iniciador (IQN y WWPN) que se incluirán en el grupo de acceso por volumen.  Si se proporciona una lista de nombres de iniciadores, estos se crearán si aún no existen.  Si se pasa una lista de identificadores de iniciadores, el método devuelve un error si alguno de los iniciadores no existe.  El uso de nombres de iniciadores está obsoleto; debe utilizar identificadores de iniciador siempre que sea posible.
 a| 
matriz de enteros (recomendado) o matriz de cadenas (obsoleto)
 a| 
Ninguno
 a| 
No



 a| 
eliminarIniciadoresHuérfanos
 a| 
Especifica si se deben eliminar los objetos iniciadores después de que se eliminen de un grupo de acceso a volúmenes o no. Valores posibles:

* verdadero: Eliminar los objetos iniciadores después de que se eliminen de un grupo de acceso a volúmenes.
* falso: No elimine los objetos iniciadores después de que se eliminen de un grupo de acceso a volúmenes. Este es el valor predeterminado.

 a| 
booleano
 a| 
FALSO
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
volumeAccessGroup
 a| 
Un objeto que contiene información sobre el grupo de acceso a volúmenes recientemente modificado.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[volumeAccessGroup]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "id": 13171,
  "method": "RemoveInitiatorsFromVolumeAccessGroup",
  "params": {
    "initiators": [114,115],
    "volumeAccessGroupID": 96
  }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 13171,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [],
      "initiators": [],
      "name": "test",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== Nueva versión

9,6
