---
permalink: api/reference_element_api_getvolumeaccessgrouplunassignments.html 
sidebar: sidebar 
keywords: volume,access,group,groups,LUN,mapping,assignment,get,getting,GetVolumeAccessGroupLunAssignments 
summary: Puede utilizar el método GetVolumeAccessGroupLunAssignments para recuperar detalles sobre las asignaciones de LUN de un grupo de acceso a volúmenes específico. 
---
= Obtener asignaciones de LUN de acceso al volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetVolumeAccessGroupLunAssignments` Método para recuperar detalles sobre las asignaciones LUN de un grupo de acceso a volúmenes especificado.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de grupo de acceso al volumen
 a| 
Un identificador único de grupo de acceso a volumen utilizado para devolver información.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
Asignaciones de grupo de acceso de volumen
 a| 
Una lista de todos los puertos físicos Fibre Channel, o un puerto para un solo nodo.
 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "GetVolumeAccessGroupLunAssignments",
   "params": {
      "volumeAccessGroupID": 5
    },
  "id" : 1
   }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id" : 1,
  "result" : {
    "volumeAccessGroupLunAssignments" : {
       "volumeAccessGroupID" : 5,
       "lunAssignments" : [
          {"volumeID" : 5, "lun" : 0},
          {"volumeID" : 6, "lun" : 1},
          {"volumeID" : 7, "lun" : 2},
          {"volumeID" : 8, "lun" : 3}
       ],
       "deletedLunAssignments" : [
           {"volumeID" : 44, "lun" : 44}
       ]
    }
  }
}
----


== Nueva versión

9,6
