---
permalink: api/reference_element_api_listauthsessionbyclusteradmin.html 
sidebar: sidebar 
keywords: cluster admin,sessions,auth sessions,list 
summary: Puede utilizar el método ListAuthSessionsByClusterAdmin para listar todas las sesiones de autenticación asociadas con el ClusterAdminID especificado.  Si el ClusterAdminID especificado corresponde a un grupo de usuarios, se mostrarán todas las sesiones de autenticación de todos los miembros de ese grupo. 
---
= ListaAuthSessionsByClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ListAuthSessionsByClusterAdmin` método para listar todas las sesiones de autenticación asociadas con el especificado `ClusterAdminID` .  Si se especifica `ClusterAdminID` Si se asigna a un grupo de usuarios, se mostrarán todas las sesiones de autenticación de todos los miembros de ese grupo.



== Parámetros

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID de administrador del clúster
 a| 
Identificador único para el administrador del clúster.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valores de retorno

Este método tiene el siguiente valor de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
sesiones
 a| 
Lista de información de sesión para las sesiones de autenticación.
 a| 
link:reference_element_api_authsessioninfo.html["información de sesión de autenticación"]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
    "method": "ListAuthSessionsByClusterAdmin",
    "clusterAdminID": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nueva versión

12,0
