---
permalink: api/reference_element_api_enablemaintenancemode.html 
sidebar: sidebar 
keywords: maintenance,enable,mode 
summary: Puede utilizar el método EnableMaintenanceMode para preparar un nodo de almacenamiento para el mantenimiento.  Los escenarios de mantenimiento incluyen cualquier tarea que requiera apagar o reiniciar el nodo. 
---
= Habilitar modo de mantenimiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `EnableMaintenanceMode` Método para preparar un nodo de almacenamiento para mantenimiento.  Los escenarios de mantenimiento incluyen cualquier tarea que requiera apagar o reiniciar el nodo.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
forceWithUnresolvedFaults
 a| 
Se debe habilitar el modo de mantenimiento forzado para este nodo incluso con fallos de clúster que bloqueen el sistema.
 a| 
booleano
 a| 
FALSO
 a| 
No



 a| 
nodos
 a| 
La lista de identificadores de nodo que se pondrán en modo de mantenimiento.  Solo se admite un nodo a la vez.
 a| 
matriz de enteros
 a| 
Ninguno
 a| 
Sí



 a| 
Límite de intercambio primario por minuto
 a| 
Número de porciones primarias a intercambiar por minuto.  Si no se especifica, todas las porciones primarias se intercambiarán a la vez.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
se acabó el tiempo
 a| 
Especifica cuánto tiempo debe permanecer habilitado el modo de mantenimiento antes de que se desactive automáticamente.  Formateado como una cadena de tiempo (por ejemplo, HH:mm:ss).  Si no se especifica, el modo de mantenimiento permanecerá activado hasta que se desactive explícitamente.
 a| 
cadena
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
manejador asíncrono
 a| 
Puede utilizar el método GetAsyncResult para recuperar este asyncHandle y determinar cuándo finaliza la transición al modo de mantenimiento.
 a| 
entero



 a| 
modo actual
 a| 
Estado actual del modo de mantenimiento del nodo. Valores posibles:

* Desactivado: No se ha solicitado ningún mantenimiento.
* Error de recuperación: El nodo no pudo recuperarse del modo de mantenimiento.
* Recuperación tras mantenimiento: El nodo se encuentra en proceso de recuperación tras haber estado en modo de mantenimiento.
* Preparación para el mantenimiento: Se están tomando medidas para preparar un nodo para realizar el mantenimiento.
* ListoParaMantenimiento: El nodo está listo para que se le realice el mantenimiento.

 a| 
Modo de mantenimiento (cadena)



 a| 
modo solicitado
 a| 
Estado del modo de mantenimiento solicitado para el nodo. Valores posibles:

* Desactivado: No se ha solicitado ningún mantenimiento.
* Error de recuperación: El nodo no pudo recuperarse del modo de mantenimiento.
* Recuperación tras mantenimiento: El nodo se encuentra en proceso de recuperación tras haber estado en modo de mantenimiento.
* Preparación para el mantenimiento: Se están tomando medidas para preparar un nodo para realizar el mantenimiento.
* ListoParaMantenimiento: El nodo está listo para que se le realice el mantenimiento.

 a| 
Modo de mantenimiento (cadena)

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "EnableMaintenanceMode",
  "params": {
    "forceWithUnresolvedFaults": False,
    "nodes": [6],
    "perMinutePrimarySwapLimit" : 40,
    "timeout" : "01:00:05"
  },
"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id": 1,
   "result":
      {
        "requestedMode": "ReadyForMaintenance",
        "asyncHandle": 1,
        "currentMode": "Disabled"
    }
}
----


== Nueva versión

12,2



== Encuentra más información

http://docs.netapp.com/us-en/hci/docs/concept_hci_storage_maintenance_mode.html["Conceptos del modo de mantenimiento de almacenamiento NetApp HCI"^]
