---
permalink: api/reference_element_api_modifykeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,modifying,modify,change,edit 
summary: 'Puede utilizar el método ModifyKeyServerKmip para modificar un servidor de claves del Protocolo de interoperabilidad de gestión de claves (KMIP) existente a los atributos especificados.  Aunque el único parámetro obligatorio es el keyServerID, una solicitud que contenga únicamente el keyServerID no realizará ninguna acción ni devolverá ningún error.  Cualquier otro parámetro que especifique reemplazará los valores existentes para el servidor de claves con el keyServerID especificado.  Durante la operación se contacta con el servidor clave para asegurar que funciona correctamente.  Puede proporcionar varios nombres de host o direcciones IP con el parámetro kmipKeyServerHostnames, pero solo si los servidores clave están en una configuración de clúster.' 
---
= ModificarKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `ModifyKeyServerKmip` Método para modificar un servidor de claves KMIP (Key Management Interoperability Protocol) existente a los atributos especificados.  Aunque el único parámetro obligatorio es el keyServerID, una solicitud que contenga únicamente el keyServerID no realizará ninguna acción ni devolverá ningún error.  Cualquier otro parámetro que especifique reemplazará los valores existentes para el servidor de claves con el keyServerID especificado.  Durante la operación se contacta con el servidor clave para asegurar que funciona correctamente.  Puede proporcionar varios nombres de host o direcciones IP con el parámetro kmipKeyServerHostnames, pero solo si los servidores clave están en una configuración de clúster.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===


| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
ID del servidor de claves
 a| 
El ID del servidor de claves KMIP que se va a modificar.
 a| 
entero
 a| 
Ninguno
 a| 
Sí



 a| 
Certificado kmipCa
 a| 
El certificado de clave pública de la CA raíz del servidor de claves externo.  Esto se utilizará para verificar el certificado presentado por el servidor de claves externo en la comunicación TLS.  Para clústeres de servidores clave donde los servidores individuales utilizan diferentes CA, proporcione una cadena concatenada que contenga los certificados raíz de todas las CA.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
Certificado de cliente kmip
 a| 
Un certificado PKCS#10 X.509 codificado en Base64 con formato PEM utilizado por el cliente Solidfire KMIP.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
Nombres de host del servidor de claves kmip
 a| 
Conjunto de nombres de host o direcciones IP asociadas a este servidor de claves KMIP.  Solo se deben proporcionar varios nombres de host o direcciones IP si los servidores clave están en una configuración de clúster.
 a| 
matriz de cadenas
 a| 
Ninguno
 a| 
No



 a| 
kmipKeyServerName
 a| 
El nombre del servidor de claves KMIP.  Este nombre se utiliza únicamente con fines ilustrativos y no necesita ser único.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
kmipKeyServerPort
 a| 
El número de puerto asociado con este servidor de claves KMIP (normalmente 5696).
 a| 
entero
 a| 
Ninguno
 a| 
No

|===


== Valores de retorno

Este método tiene los siguientes valores de retorno:

|===


| Nombre | Descripción | Tipo 


 a| 
Servidor de claves kmip
 a| 
Un objeto que contiene detalles sobre el servidor de claves recientemente modificado.
 a| 
link:reference_element_api_keyserverkmip.html["KeyServerKmip"]

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "ModifyKeyServerKmip",
  "params": {
    "keyServerID": 15
    "kmipCaCertificate": "CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
    "kmipClientCertificate": "kirWmnWXbj9T/UWZYB2oK0z5...",
    "kmipKeyServerHostnames" : ["server1.hostname.com", "server2.hostname.com"],
    "kmipKeyServerName" : "keyserverName",
    "kmipKeyServerPort" : 5696
  },
"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":1
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"kirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== Nueva versión

11,7
