---
permalink: api/reference_element_api_getsoftwareencryptionatrestinfo.html 
sidebar: sidebar 
keywords: system, api, security, get, getting, software encryption at rest 
summary: Puede utilizar el método GetSoftwareEncryptionAtRestInfo para obtener información sobre el método que utiliza el clúster para cifrar los datos en reposo. 
---
= Obtener información de cifrado de software en reposo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `GetSoftwareEncryptionAtRestInfo` Método para obtener información sobre el cifrado de software en reposo que utiliza el clúster para cifrar los datos en reposo.



== Parámetros

Este método no tiene parámetros de entrada.



== Valores de retorno

Este método tiene los siguientes valores de retorno:

[cols="4*"]
|===
| Parámetro | Descripción | Tipo | Opcional 


| Información de clave maestra | Información sobre la clave maestra actual de cifrado en reposo del software. | Información de clave de cifrado | Verdadero 


| rekeyMasterKeyAsyncResultID | El ID del resultado asíncrono de la operación de re-clave actual o más reciente (si la hay), si aún no se ha eliminado. `GetAsyncResult` La salida incluirá un `newKey` campo que contiene información sobre la nueva clave maestra y un `keyToDecommission` campo que contiene información sobre la clave anterior. | entero | Verdadero 


| estado | Estado actual del cifrado de software en reposo.  Los valores posibles son `disabled` o `enabled` . | cadena | FALSO 


| versión | Un número de versión que se incrementa cada vez que se habilita el cifrado de software en reposo. | entero | FALSO 
|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
 "method": "getsoftwareencryptionatrestinfo"
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
    "id": 1,
    "result": {
        "masterKeyInfo": {
            "keyCreatedTime": "2021-09-20T23:15:56Z",
            "keyID": "4d80a629-a11b-40ab-8b30-d66dd5647cfd",
            "keyManagementType": "internal"
        },
        "state": "enabled",
        "version": 1
    }
}
----


== Nueva versión

12,3

[discrete]
== Encuentra más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación del software SolidFire y Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de los productos NetApp SolidFire y Element"^]

