---
permalink: api/reference_element_api_testdrives.html 
sidebar: sidebar 
keywords: drive,drives,test,testing,validating,hardware,testdrives 
summary: Puede utilizar el método TestDrives para ejecutar una validación de hardware en todas las unidades del nodo.  Este método detecta fallos de hardware en las unidades e informa de cualquier fallo en los resultados de las pruebas de validación. 
---
= Pruebas de manejo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `TestDrives` Método para ejecutar una validación de hardware en todas las unidades del nodo.  Este método detecta fallos de hardware en las unidades e informa de cualquier fallo en los resultados de las pruebas de validación.



== Parámetros

Solo puedes usar el `TestDrives` método en nodos que no están "activos" en un clúster.


NOTE: Esta prueba dura aproximadamente 10 minutos.

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Requerido 


 a| 
fuerza
 a| 
Establecer en verdadero para probar las unidades en el nodo.
 a| 
booleano
 a| 
Ninguno
 a| 
Sí



 a| 
minutos
 a| 
Especifica el número de minutos que durará la prueba.
 a| 
entero
 a| 
10
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
detalles
 a| 
Información sobre el éxito o el fracaso de la operación de prueba.
 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
   "method": "TestDrives",
   "params": {
              "force": true,
              "minutes" : 10
             },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una tabla que contiene los resultados de las pruebas para cada unidad del nodo.



== Nueva versión

9,6
