---
permalink: api/reference_element_api_disableclusterssh.html 
sidebar: sidebar 
keywords: SSH,disable,disabling,cluster,DisableClusterSsh 
summary: Puede utilizar el método DisableClusterSsh para deshabilitar el servicio SSH para todo el clúster de almacenamiento.  Cuando agregue nodos al clúster de almacenamiento, los nuevos nodos heredarán esta configuración de todo el clúster. 
---
= Deshabilitar ClusterSsh
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes usar el `DisableClusterSsh` Método para deshabilitar el servicio SSH para todo el clúster de almacenamiento.  Cuando agregue nodos al clúster de almacenamiento, los nuevos nodos heredarán esta configuración de todo el clúster.



== Parámetro

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
resultado
 a| 
Un objeto JSON que contiene el estado del servicio SSH para el clúster de almacenamiento, el tiempo restante hasta que se deshabilite SSH y el estado del servicio SSH para cada nodo.
 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes para este método son similares al siguiente ejemplo:

[listing]
----
{
  "method": "DisableClusterSsh",
  "params": {
      },
  "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
	"id": 1,
	"result" : {
    "enabled": true,
    "timeRemaining": "00:43:21",
    "nodes": [
    {
        "nodeID": 1,
        "enabled": true
    },
    {
        "nodeID": 2,
        "enabled": true
    },
    {
        "nodeID": 3,
        "enabled": false
    },
    {
        "nodeID": 4,
        "enabled": false
    } ]
			}
	}
----


== Nueva versión

10,3
