---
permalink: api/reference_element_api_hardwareinfo.html 
sidebar: sidebar 
keywords: object,objects,hardwareInfo 
summary: El objeto hardwareInfo contiene información detallada sobre el hardware y el estado de cada nodo del clúster.  Puede recuperar esta información con el método API GetHardwareInfo. 
---
= Información de hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El objeto hardwareInfo contiene información detallada sobre el hardware y el estado de cada nodo del clúster.  Puedes recuperar esta información con el `GetHardwareInfo` Método API.



== miembros del objeto

Este objeto contiene los siguientes miembros:

|===
| Nombre | Descripción | Tipo 


 a| 
Serie de la placa
 a| 
El número de serie de la placa DMI.
 a| 
cadena



 a| 
autobús
 a| 
Información del bus multimedia de la placa base.
 a| 
Objeto JSON



 a| 
chasisSerial
 a| 
El número de serie del chasis.
 a| 
cadena



 a| 
Hardware de la unidad
 a| 
Una lista de información para cada unidad en el nodo.
 a| 
matriz de objetos JSON



 a| 
Puertos de canal de fibra
 a| 
Lista de puertos Fibre Channel en el nodo.
 a| 
matriz de enteros



 a| 
configuración de hardware
 a| 
Información de configuración periférica de la placa base.
 a| 
Objeto JSON



 a| 
estado de volcado de memoria del kernel
 a| 
La configuración del volcado de memoria del núcleo del sistema operativo.
 a| 
cadena



 a| 
memoria
 a| 
Información sobre el firmware y el hardware de la memoria del sistema.
 a| 
Objeto JSON



 a| 
red
 a| 
Descripción del hardware de cada una de las interfaces de red del nodo.
 a| 
Objeto JSON



 a| 
interfaces de red
 a| 
El estado de las interfaces de red del nodo.
 a| 
Objeto JSON



 a| 
nodoSlot
 a| 
Para las plataformas HCI, la letra correspondiente a la ranura del chasis en la que se encuentra este nodo ("A", "B", "C" o "D").  Para las plataformas de almacenamiento, este valor es nulo.
 a| 
cadena



 a| 
NVRAM
 a| 
Estadísticas NVRAM para el nodo.
 a| 
Objeto JSON



 a| 
origen
 a| 
El proveedor de la placa base.
 a| 
cadena



 a| 
plataforma
 a| 
Descripción de la plataforma del chasis.
 a| 
Objeto JSON



 a| 
de serie
 a| 
El número de serie del producto.
 a| 
cadena



 a| 
almacenamiento
 a| 
Información del controlador de almacenamiento.
 a| 
Objeto JSON



 a| 
Memoria del sistema
 a| 
Información sobre el uso de memoria y el rendimiento del sistema operativo.
 a| 
Objeto JSON



 a| 
sistema
 a| 
El tipo de chasis del nodo.
 a| 
Objeto JSON



 a| 
UUID
 a| 
El identificador único del nodo.
 a| 
UUID

|===


== Encuentra más información

xref:reference_element_api_gethardwareinfo.adoc[Obtener información de hardware]
